cmd/earthly/satellite_cmds.go

The operations can be long, especially the delete, and the user may not want to wait for it. The backend handles context-cancelled and allows the operation to finish gracefully.

Friendlier message on ctrl-c in satellite launch or rm

---

.buildkite/tests.sh

This displays a final pass/failure on the buildkite test, to make
it obvious when the test passes.
Without this, a user may mistake the output of the fail-test (the test
that validates earthly returns a failure code on errors) as the
buildkite-test failing.

print pass/failure message as final line on test

---

ast/tests/save-artifact-after-push.ast.json
tests/Earthfile
tests/save-artifact-after-push.earth

Improve coverage of save-artifact-after-push test

---

cmd/earthly/build_cmd.go
cmd/earthly/buildkit.go
cmd/earthly/main.go
cmd/earthly/root_cmds.go

This helps prevent those spurious warnings on unrelated commands such as `earthly account login`.
This PR also reduces the frontend initialization error output to a simple message "No frontend initialized". This can be expanded with the `--verbose` flag.

Init frontend only when actually needed

---

.github/workflows/ci.yml
builder/builder.go
earthfile2llb/converter.go
earthfile2llb/wait_block.go
states/states.go

This fixes a WAIT/END related bug that occured in combination with WITH DOCKER commands,
where the `--load` flag could not interpret the loaded target's docker
name, due to SAVE IMAGE not being stored in mts.
This fix introduces a new `allowDoSaves` arg to prepBuildTarget, which
WITH DOCKER commands will set to false, to prevent loaded images from
being exported to the local docker instance.

Fix WITH DOCKER WAIT/END related bug

---

cloud/org_new.go
cmd/earthly/org_cmds.go
go.mod
go.sum

Requiring a name doesn't necessarily add much and can slow down the invite flow.

Remove user name from invite command

---

builder/builder.go
builder/docker.go
scripts/tests/export.sh

This fixes a bug where loadDockerManifest was comparing a materialized
platform with an unmaterialized platform.
Additionally, a warning is now displayed when no platform matching the
default platform is found.

fix loadDockerManifest platform detection bug

---

conslogging/conslogging.go

Making the complete output slightly more compact. Less scrolling.
This fixes #2087.

feat(logging): less verbose headers

---

buildkitd/buildkitd.go
util/containerutil/frontend.go
util/containerutil/frontend_test.go
util/containerutil/shell_shared.go
util/containerutil/stub.go

In an environment where Docker was not set up and the user forgot that there would be some local outputs from a satellite build they were getting this error:
```
output | WARN: (exporting outputs) failed to copy to tar: rpc error: code = Unknown desc = io: read/write on closed pipe
2022/08/17 16:41:39 http2: server connection error from localhost: connection error: PROTOCOL_ERROR
```
The issue was that the local outputs could not be loaded into Docker because the frontend was not initialized (Docker isn't available). This PR helps with a better error in such cases.

Return errors in stub frontend

---

examples/go-monorepo/services/two/Earthfile

The `go-monorepo` example doesn't build because of this small typo.

Fix typo in go-monorepo example

---

cloud/client.go
cmd/earthly/satellite_cmds.go

Apparently `errors.Is` works much better than `errors.Cause`. I suspect in these cases, the `context.Canceled` error was not necessarily the "cause" but was somewhere in the chain.
Before + after:

Fix Ctrl-C in Satellite Launch/Rm

---

.github/workflows/satellites.yml

+examples2 was failing because QEMU was not installed. The satellites tests just run local buildkit instead of actually on satellites when they are triggered by a fork.
Example of passing test from a fork https://github.com/earthly/earthly/actions/runs/2920999640

Fix +examples2 on Satellites from Forks

---

cmd/earthly/main.go
cmd/earthly/org_cmds.go

This makes the "read" permission the default choice if they enter nothing. It also removes the "message" parameter from the flow by default (it can still be passed in via a flag).

Invite tweaks: require the least amount of decisions of the user

---

Earthfile
examples/cache-command/npm/package-lock.json
examples/tutorial/js/part3/package-lock.json
examples/tutorial/js/part4/package-lock.json
examples/tutorial/js/part5/services/service-one/package-lock.json
examples/tutorial/js/part6/api/package-lock.json
examples/tutorial/js/part6/app/package-lock.json
tests/remote-cache/test2/package-lock.json

This adds a target which performs an npm update on all examples and
tests. This is to keep packages up to date with security patches.

npm-update-all target

---

go.mod
go.sum

Fixes #2151 
This resolves errors stemming from https://github.com/golang/go/issues/51689; it just so happens it was fixed a few hours ago.  I didn't think a dependency change of this nature would warrant any new tests, but correct me if I'm wrong.  But this does eliminate the errors after applying this change.

Update crypto to address "parse error in message type 27" errors

---

earthfile2llb/converter.go

This fixes a bug where SAVE IMAGE --push commands always pushed an
image, even when earthly was run without the --push flag.

fix: SAVE IMAGE --push in WAIT/END always happened

---

builder/builder.go
builder/solver.go
earthfile2llb/wait_block.go
tests/wait-block/save-multi-platform-image/Earthfile
tests/wait-block/save-multi-platform-image/test.sh
util/dockerutil/docker.go
util/gatewaycrafter/pullpingmap.go

This fixes a bug where the default platform was never exported to the
local docker instance.

fix wait-end multiplatform exports

---

docs/docker-images/all-in-one.md
docs/docker-images/buildkit-standalone.md

The prerelease tag does not exist.

remove prerelease from docs

---

builder/builder.go
earthfile2llb/converter.go
earthfile2llb/wait_block.go
util/gatewaycrafter/exportcoordinator.go
util/saveartifactlocally/saveartifactlocally.go

SAVE IMAGE (and SAVE ARTIFACT) details should be displayed at the end of
the earthly run in the summary details.

Display SAVE IMAGE (within wait-end) details

---

.earthly_version_flag_overrides
CHANGELOG.md
earthfile2llb/converter.go
tests/push-images/test.sh

It is still experimental; however, the code is now much more complete,
and has a higher degree of test-coverage.
The push-images test was modified due to the --wait-block feature no
longer prevents saving an image after a push, e.g.
RUN --push ...
SAVE IMAGE ...
is now valid when run with the `--wait-end` feature, since it roughly
translates into
ARG EARTHLY_PUSH
IF [ $EARTHLY_PUSH = "true" ]
RUN --push ...
END
SAVE IMAGE ...

Remove WAIT/END is experimental warning

---

cloud/client.go
cloud/org_new.go
cmd/earthly/org_cmds.go
go.mod
go.sum

New subcommand that helps users determine the status of previously sent invites.
```
earthly preview orgs --org earthly-technologies invite ls
User Email                     Permission  Created     Accepted
mike@earthly.dev               admin       2022-07-29  No
mikejholly@gmail.com           read        2022-08-22  2022-08-22
mikejholly+test001@gmail.com   read        2022-08-22  2022-08-22
mikejholly+test0002@gmail.com  read        2022-08-24  No
mikejholly+test0003@gmail.com  admin       2022-08-24  No
mikejholly+test0004@gmail.com  read        2022-08-25  2022-08-25
```

New subcommand to list invite status

---

cmd/earthly/build_cmd.go
cmd/earthly/buildkit.go
cmd/earthly/root_cmds.go

There are valid use cases for installing Earthly without a functional Buildkit. For example, using it via podman (needs to be configured), or using it only for org/account/secret management.
Before this PR, the brew installation would fail on a Mac if Docker is not available. One case is that Docker simply is not installed. But another (very common) case is that the Docker App is simply not started. We don't want to prevent the user from installing Earthly in these cases. We can always show them a more meaningful error on their first build.
In addition, this PR improves the error shown when attempting to perform a local build and Docker is not running.

Brew install should not fail if buildkit startup fails

---

docs/basics/part-4-args.md

Simply change the spelling from `latests` -> `latest`.

correct spelling error latests -> latest

---

CHANGELOG.md
cmd/earthly/autocomplete.go

A user reported having `/usr/share/zsh/site-functions` as their zsh location rather than `/usr/local/share/zsh/site-functions`; This change checks both locations rather than just the later.

bootstrap: attempt multiple zsh install locations

---

cloud/auth_test.go
cloud/client.go
cloud/grpc.go
cloud/http.go
cloud/satellite.go
cmd/earthly/account_cmds.go
cmd/earthly/build_cmd.go
cmd/earthly/debug_cmds.go
cmd/earthly/flags.go
cmd/earthly/main.go
cmd/earthly/org_cmds.go
cmd/earthly/project_cmds.go
cmd/earthly/root_cmds.go
cmd/earthly/satellite_cmds.go
cmd/earthly/secret_cmds.go
go.mod

I was running into some issues with the JSON-to-protobuf unmarshaller we've been using. In particular with enums, where existing enums can not be added to on the server without breaking old clients versions - i.e. the JSON unmarshaller throws an error if it encounters an enum value it doesn't recognize. Traditional gRPC does not have this limitation.
Unsurprisingly, the code is also much simpler now in gRPC than it was before using REST calls.
Note: this switches the Pipelines endpoints only, as other endpoints don't support gRPC yet. In due time, we can convert the other endpoints too (after we've converted them on the server first).

Use gRPC Client Instead of JSON

---

CHANGELOG.md
util/containerutil/docker.go
util/containerutil/podman.go
util/containerutil/shell_shared.go
util/containerutil/stub.go

fixes https://github.com/earthly/earthly/issues/1895
Running Earthly from an M1 mac to a remote docker host running x86 was broken as described in the issue.
We need to ensure an appropriate image is pulled that is. compatible with the architecture the docker host itself.
The solution is to use the frontend information we collect via the `Information` call to determine if the current client's platform also works on the server. 
If it is supported, this acts as a sort of preference to the client's platform.
If not, it will default to the server platform to allow the buildkitd container to run.
@alexcb @vladaionescu

Fix remote docker host running x86 platform. Fixes https://github.com/earthly/earthly/issues/1895

---

cmd/earthly/org_cmds.go
cmd/earthly/root_cmds.go

This PR:
* Removes the older `invite` command 
* Moves the new `invite` and `members` subcommands out of `preview`

Move new org invite and members commands out of preview

---

features/features.go
tests/autocompletion/Earthfile
tests/autocompletion/bad-version-flag.earth
util/flagutil/parse.go

Dont display errors (and help text) if the autocompletion code fails due to an unknown VERSION flag.

dont display errors during autocompletion

---

.github/workflows/ci.yml
CHANGELOG.md
buildkitd/buildkitd.go
buildkitd/settings.go
cmd/earthly/buildkit.go
go.mod
go.sum

* Use flock to prevent buildkit startup race conditions. Fixes https://github.com/earthly/earthly/issues/2194
* This PR also speeds up buildkit start time, after adjusting some timeouts in the startup code

Use flock to prevent buildkit startup race conditions

---

cmd/earthly/main.go

Indicate that `--allow-privileged` should be provided on the command-line, not in `WITH DOCKER`.

Slightly clearer error message on missing `-P`

---

buildkitd/buildkitd.go
cloud/client.go
cloud/satellite.go
cmd/earthly/buildkit.go
go.mod
go.sum

The new [satellite reserve endpoint](https://github.com/earthly/cloud/pull/344) wakes up a satellite if it's asleep, and calls buildkit Reserve().  It's a streaming RPC call, which returns periodic updates until the instance is awake.

Use New Satellite Reserve Endpoint

---

variables/collection.go

Setting org/project on the current stack frame was leading to UDC secrets not having access to the org/project. This change sets the org/project values directly on the var collection.

Don't use stack frames for org/project

---

cmd/earthly/project_cmds.go
cmd/earthly/secret_cmds.go

It seems like `app.console.Printf` writes to stderr. This was causing some issues with grepping, etc.

Don't output secret list result to stderr

---

release/README.md

ci-integration.md was deleted in d6c4467ae401c14c0fd7b10e8df29437389fc556

remove dead link from release readme

---

.github/workflows/ci-docker-ubuntu.yml
.github/workflows/ci-scheduled-codeql-analysis.yml
.github/workflows/ci-scheduled-pkg-tests.yml
.github/workflows/ci-scheduled-podman-mac.yml
.github/workflows/ci-staging-deploy.yml
.github/workflows/reusable-bootstrap-integrations.yml
.github/workflows/reusable-example.yml
.github/workflows/reusable-export-test.yml
.github/workflows/reusable-misc-tests.yml
.github/workflows/reusable-push-integrations.yml
.github/workflows/reusable-repo-auth-tests.yml
.github/workflows/reusable-secrets-integrations.yml
.github/workflows/reusable-test-local.yml
.github/workflows/reusable-test.yml

The GITUHB_TOKEN is auto-generated and scoped to the repository running the workflow.
This should fix the problem forked repositories were having.

[ci]: use GITHUB_TOKEN rather than GRISWALD

---

buildcontext/detectbuildfile.go
cmd/earthly/root_cmds.go

This is a proof of concept, that aims to improve error presented to end user, when we encounter syntax error when executing `earthly ls`.
I would love to get some feedback, or suggestions what else could be fixed under this PR, as the change now is minimal, and probably not worth merging yet.
Closes #2223

chore: removed custom error

---

CHANGELOG.md
buildkitd/buildkitd.go
util/containerutil/docker.go
util/containerutil/podman.go
util/containerutil/types.go

Cache size was being returned as Bytes, but was treated as if it were KiB.

Fix cache size unit

---

features/features.go

Version feature flags are instrumented; however the version value was never instrumented.

Instrument version number

---

.earthly_version_flag_overrides
CHANGELOG.md
Earthfile
cmd/earthly/build_cmd.go
cmd/earthly/buildkit.go
features/features.go

Closes https://github.com/earthly/earthly/issues/1268
Note that the feature flag `--use-registry-with-docker` is backward compatible, hence we can enable it retroactively for all versions, now that we have confidence in the way it functions.
For earthly-in-earthly used in our integration tests, `WITH DOCKER` doesn't work correctly with the embedded registry, due to the use of `NETWORK_MODE=host`. In such cases, we force the old behavior via the override feature flags functionality.

GA `--use-registry-with-docker` and make the Satellite warnings less prominent

---

docs/guides/podman.md

Link wasn't properly formatted. It may be nicer to change it to something like:
```markdown
[podman machine][podman_machine]
[podman_machine]: https://docs.podman.io/en/latest/markdown/podman-machine.1.html
```
And reuse the link across the document, I just wasn't sure about the style/practices for these docs.

Fix link in podman guide

---

CHANGELOG.md
cloud/account.go
cloud/auth.go
cloud/client.go
cmd/earthly/account_cmds.go

Extend client-side support for all ssh key types.

Support for all ssh key types (e.g. ssh-ed25519)

---

ast/tests/git-clone.ast.json
buildcontext/git.go
earthfile2llb/converter.go
tests/git-clone.earth
util/llbutil/copyop.go

CopyOp was ignoring the current working directory when merging.

fix copyop merging without cwd

---

release/README.md
release/release.sh

We should check for `jq` + update the release.sh run command to also pass $USER.

[contrib]: check for jq + update release cmd in docs

---

CONTRIBUTING.md

buildkit PRs should only be squashed for new features, not when merging upstream changes.

clarify squashing of buildkit commits

---

analytics/analytics.go
cloud/client.go
cloud/satellite.go
cmd/earthly/build_cmd.go
cmd/earthly/buildkit.go
go.mod
go.sum

This passes the git authro all the way up to the call to ReserveSatellite, which must be adjusted on the back end.

Pass git author to ReserveSatellite

---

cmd/earthly/main.go

Display a final warning on the last line in yellow, if earthly exits due to a ctrl-c

display warning as final line on ctrl-c

---

CHANGELOG.md
util/fsutilprogress/progress.go

This displays a summary of total bytes, number of files, and data transfer rate every 15 seconds.

Display summary of context file transfers

---

cloud/client.go
cloud/satellite.go
cmd/earthly/buildkit.go
cmd/earthly/satellite_cmds.go
go.mod
go.sum

The satellite wake command will start a satellite that is asleep. This can be useful for using the `inspect` command, since it will not show much info when the satellite is asleep. 
The wake command will also use more "force" in trying to start a satellite than a normal Reserve call will do, so it can be usef to debug or attempt to recover a satellite that has failed or ended up in a bad state for some reason.
Examples below 👇 
Satellite wake command, when satellite is asleep:
Satellite wake when already awake:
`inspect` prompts user to run `wake` if the satellite is asleep:

Satellite Wake-up Command

---

buildkitd/buildkitd.go
outmon/solvermon.go
util/buildkitutil/utilization.go

This is to avoid load being misinterpreted as "loading data".

rename Load to current utilization

---

util/containerutil/frontend_test.go

The frontend tests had a few issues:
- the returned error was being ignored.
- The container was started with an invalid command meaning they weren't up for long.
- We didn't wait for the containers to actually be running before trying to test them.
- We only checked stderr had logs, but now we check both for expected messages.
- We weren't using `t.Cleanup`, so we weren't necessarily waiting for containers to be cleaned up.

Patch frontend tests

---

.github/workflows/ci-docker-satellites.yml

The example targets should run on the satellite `core-examples`
This helps balance the load when there's lots of PR builds. Also a proof-of-concept for splitting load on multiple satellites

Run builds on two Satellites

---

CHANGELOG.md
buildkitd/buildkitd.cache.template
buildkitd/entrypoint.sh

This increases the cache limit for local and git sources from 10% to 50% to support copying large files (e.g. binary assets). This additionally fixes the `gckeepstorage` value which expects MB and not bytes.

increased buildkit source cache limit

---

util/platutil/resolver.go

This was being overridden because in the past we didn't have distinct platforms for user vs target vs native. This no longer makes sense now, however.

Use correct user platform on Darwin and on Windows

---

earthly

Before:
```sh
% ./earthly +for-darwin-m1
.earthly_version_flag_overrides has changed since last run, checking for prerele
ase binaries If you see an "unable to set <flag-name>: invalid flag" error, you 
may have to wait for the prerelease binary to be built by GHA on the main branch
, before re-attempting a ./earthly upgrade
./earthly: line 49: none: command not found
```
After:
```sh
% ./earthly +for-darwin-m1
.earthly_version_flag_overrides has changed since last run, checking for prerele
ase binaries. If you see an "unable to set <flag-name>: invalid flag" error, you
may have to wait for the prerelease binary to be built by GHA on the main branc
h, before re-attempting a ./earthly upgrade
```

Add period to .earthly_version_flag_overrides warning

---

CONTRIBUTING.md

I don't know that the average Mac user knows what `<platform>` would be. But, more importantly, the average new Mac user will not have an `amd64` Mac, so the rest of the command doesn't work.
Alternatively, the text could be `<platform>/<arch>` -- in which case something should really explain both `<platform>` and `<arch>`.

Switch platform/arch to work on Apple m1

---

cloud/client.go
cloud/satellite.go
cmd/earthly/satellite_cmds.go
go.mod
go.sum

Added a new command that manually puts a satellite to sleep. When the satellite is already asleep, this is a no-op. 
This command is very useful for us internally for testing, but also could be of use to users who want more fine-grain control over their satellite's up-time. 
Note this will put a satellite to sleep, even if the user has manually disabled the auto-sleep feature. Hence a user could opt out of the auto-sleep feature and completely manage the satellite's state themselves, if they are so inclined.

Satellite sleep command

---

earthly

This fixes an edge case where ~/.earthly/earthly-prerelease is deleted by the user, but the script assumes it still exists.

Always Check for earthly prerelease

---

.github/workflows/ci-docker-satellites.yml

This is temporary, while the original `core-test` satellite is in a weird state that we want to continue debugging.

Use 'core-test-2' satellite

---

docs/ci-integration/guides/woodpecker-integration.md
docs/ci-integration/overview.md

There was no documentation yet about how to use earthly with woodpecker-ci. It took me some time to get it working (the combination of trusted project, adding the image to the list of privileged images and the volume mount in a ci file).
It might be helpful for others too.

Add documentation for woodpecker-ci

---

.github/workflows/reusable-misc-tests.yml
buildkitd/entrypoint.sh

Uses a `trap` to relay the SIGTERM to buildkit in the entrypoint script.

Buildkit graceful shutdown on SIGTERM

---

CHANGELOG.md

CHANGELOG entry for v0.6.29

---

docs/earthly-config/earthly-config.md

Add documentation for specifying the frontend (Docker / Podman) to the `global` configuration options.

[docs]: Specify how to set podman shell

---

docs/guides/target-ref.md

All other three examples can be used directly on the cli, or via a `BUILD`, the `earthly+for-linux` can only be used in an Earthfile, which is confusing for new users.

remove `earthly+for-linux` from the target example

---

util/containerutil/docker.go
util/containerutil/podman.go
util/containerutil/shell_shared.go

No longer necessary, and they add too much output when autodetecting frontend.

Remove frontend commands retries

---

.github/workflows/reusable-misc-tests.yml
scripts/tests/interactive-debugger/docker-compose/Dockerfile
scripts/tests/interactive-debugger/docker-compose/Earthfile
scripts/tests/interactive-debugger/docker-compose/docker-compose.yml
scripts/tests/interactive-debugger/docker-compose/test-docker-compose.py

Closes #2263.
1. Replace `aa8y/postgres-dataset` with the rot13 echo server.
2. Reduce the interactive debugger test timeout to 180 seconds.

Simplify the docker-compose interactive debugger test

---

CHANGELOG.md
earthfile2llb/converter.go
earthfile2llb/interpreter.go
tests/Earthfile
tests/multi-stack-failure.earth
tests/stack-failure.earth
variables/builtin.go
variables/collection.go

This fixes an issue where all .env values are displayed during failures, which could potentially print a secret value (since secrets can also read from .env).

Only display declared ARGs in failures

---

Earthfile
earthly

If the frontend detection fails, it returns `none`, then the `./earthly` script will attempt to run commands such as `none pull docker.io/earthly/earthlybinaries:prerelease`, which results in a `none command not found` which is difficult to debug.

exit with error if frontend not detected

---

logbus/bus.go
logbus/command.go
logbus/formattedwriter.go
logbus/generic.go
logbus/logstreamer/logstreamer.go
logbus/run.go
logbus/setup/setup.go
logbus/target.go

Also, fix panic due to sending on a closed channel in `Logstreamer`.

Fix `time.Now().UnixNano()` stripping away the nanos

---

contrib/earthfile-syntax-highlighting-intellij/README.md
contrib/earthfile-syntax-highlighting/Earthfile
contrib/earthfile-syntax-highlighting/LICENSE
contrib/earthfile-syntax-highlighting/README.md
contrib/earthfile-syntax-highlighting/syntaxes/earthfile.tmLanguage.json

- Fixes https://github.com/earthly/earthly/issues/2399
- Fixes https://github.com/earthly/earthly/issues/2417
- Adds IntelliJ reference, for completeness
- Adds `publish-to-ovsx` step on release target

Changes in vscode-syntax-highlighting-v0.0.12

---

CHANGELOG.md
tests/shell-out/new.earth
util/shell/lex.go

lexer was incorrectly removing first character when parsing single quotes within a shellout. fixes https://github.com/earthly/earthly/issues/2340

fix singlequote parsing for --shell-out-anywhere

---

logbus/formatter/formatter.go
logbus/logstreamer/logstreamer.go
logbus/solvermon/solvermon.go
util/xcontext/xcontext.go

This addresses some issues related to attempting to send deltas after close, plus it fixes an occasional hang on ctrl-c.

Fix logstream closing sequence

---

cloud/satellite.go
cmd/earthly/main.go
cmd/earthly/satellite_cmds.go
go.mod
go.sum

Added a couple of fields to  `ls` and `inspect`. 
Buidlkit version and state are now shown in `ls`. Buildkit version only works on new satellites, as it requires a new server change to be applied as they are launched. Notice the output is also sorted now by server too.
Feature flags are shown on `inspect`, along with the new version field.

More fields on satellite ls and inspect

---

cmd/earthly/main.go
conslogging/conslogging.go
conslogging/prefixwriter.go
logbus/formatter/formatter.go
logbus/generic.go
logbus/logstreamer/logstreamer.go
logbus/run.go
logbus/setup/setup.go

Known issue: There are some extra new lines in the output. Will be fixed in a future PR.

Add all the non-buildkit output to logstream too

---

CHANGELOG.md
buildcontext/gitlookup.go

This adds support for a custom `.netrc` file path using the (apparently) standard `NETRC` env. https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html

Support NETRC environmental var

---

release/Earthfile

The homebrew earthly formula creates it's own ldflags string, replacing it via the release.sh will lead to conflicting changes.

homebrew-release: don't change ldflags

---

cmd/earthly/build_cmd.go

For local testing of logstream until we replace this properly.

default to my-project for org until we replace it

---

earthly

This prevents bash autocompletion from attempting to execute a non-existant binary (which then displays errors to the screen, which clobbers a user's terminal).

prevent autocompletion from executing non-existant binary

---

Earthfile

The earthly pre-release should default to an `earthly` default installation name rather than `earthly-dev`; only locally-compiled versions of earthly should use `earthly-dev` -- this change makes the local workflow faster as `./earthly +for-<platform>` and `./build/platform.../earthly` would have unique installation names, which will prevent the need to restart buildkit when switching between the two.

earthly script should default to ~/.earthly

---

builder/builder.go
earthfile2llb/converter.go
earthfile2llb/earthfile2llb.go
earthfile2llb/save_artifact_wait_item.go
earthfile2llb/save_image_wait_item.go
earthfile2llb/state_wait_item.go
earthfile2llb/wait_block.go
states/states.go
tests/wait-block/save-artifact-multi-ref/Earthfile
tests/wait-block/save-artifact-multi-ref/test.sh
tests/wait-block/save-multi-platform-image-with-from/Earthfile
tests/wait-block/save-multi-platform-image-with-from/test.sh
tests/wait-block/with-docker-run-load/Earthfile
tests/wait-block/with-docker-run-load/test.sh
util/waitutil/wait_block.go
util/waitutil/wait_item.go

This fixes a race condition where the same target is referenced from
both a FROM or COPY, then a BUILD.
When the converter is run via a FROM or COPY, it produces wait-items
which do not have a doSave (aka localExport) flag set; when it's
re-referenced from a BUILD it must scan through all wait items and set
the flag to true.

fix wait-end SAVE IMAGE/ARTIFACT race

---

CHANGELOG.md
earthfile2llb/interpreter.go
tests/Earthfile
tests/env-home.earth
util/shell/lex.go
util/shell/lex_test.go
variables/collection.go

The HOME env is set by the shell and not in the docker image; if a user references $HOME we will automatically shellout to determine the value.

automatic shell-out for $HOME expansion

---

tests/local/Earthfile

GHA's underlying VM changed and no longer returns `5:cpuset:/` on `/proc/1/cgroup`. Instead we can use `systemd-detect-virt --container` to detect if the command is running within a container or not.

update test-local to use systemd-detect-virt

---

examples/readme/go1/Earthfile

This updates the example to use 1.19 and golangci-lint

update go1 example

---

docs/basics/part-3-adding-dependencies-with-caching.md

The links for "More examples" in "Learn the basics Part 3" were referencing Part 4 instead.
The code taken from the Earthfiles and shown in the docs seems correct.

docs: fix incorrect links in "Learn the basics Part 3: More Examples"

---

CONTRIBUTING.md

This bit me hard; it took me quite a while to figure out why the test suite was failing so horribly for me.  I'm not sure if it's because there are tests that don't respect `DOCKERHUB_MIRROR` or because I was using the binary to verify it solved my problem (#2516), but one or both resulted in me hitting hub's rate limit due to my config file not being used.
I'm happy to rephrase/reformat however you want; I just thought it was important to get documented.

Note location of new post- v0.6.30 config file

---

buildcontext/git.go
buildcontext/resolver.go
builder/builder.go
cmd/earthly/build_cmd.go
config/config.go
docs/earthly-config/earthly-config.md

This adds support to set the `gitImage` via an entry in the config file:
```yaml
global:
git_image: my/gitimage:v1.2.3
```

feat: allow to set gitImage via config file #2027

---

docs/basics/part-5-importing.md
docs/earthfile/earthfile.md

basics:
- clarify that relative paths require './' or ../'
- clarify how earthly recognizes a repository path in FROM
earthfile:
- add notes about '../' and '/' in FROM

docs: clarify references to other builds in FROM

---

docs/basics/part-1-a-simple-earthfile.md

I was a little tripped up by the fact that 'SAVE ARTIFACT output/example' just loses the 'output/' directory.  This just clarifies that we're relying on a default value in a second argument to 'SAVE ARTIFACT' in the tutorial.

docs/basics: clarify the destination path in SAVE ARTIFACT

---

.github/workflows/reusable-test.yml
ast/tests/privileged.ast.json
tests/allow-privileged-import.earth
tests/allow-privileged.earth
tests/privileged.earth
tests/true-false-flag.earth
util/containerutil/docker.go
util/containerutil/frontend.go
util/containerutil/podman.go
util/containerutil/shell_shared.go
util/containerutil/stub.go

The `--platform` flag is only ever passed to docker/podman when both the
user and server platform values are equal. When they mismatch, the
`--platform` flag is ommitted, and the server's native platform is used.
Since the `--platform` value is only ever passed when the user and
server platforms are equal, it shouldn't matter; however in practice
there is a podman bug, which causes a pull to occur whenver the
`--platform` flag is specified: https://github.com/containers/podman/issues/15711
This bug will cause podman to always pull the earthly/buildkitd image from
docker hub, which will either 1) overwrite the local image if the image exists in docker hub,
and ultimately will cause our tests to run against an incorrect image
version, or 2) result in the following 404-error if the tag does …

Don't pass --platform to docker/podman

---

Earthfile

This is to help with sanity checking docker login is passed variables correctly.
For example, I had some tests that were failing on:
WARN Earthfile line 369:12: The command 'RUN docker login $DOCKERHUB_MIRROR --username="$USERNAME" --***' failed: unauthorized
which were due to upstream server issues, but I wanted to eliminate the possibility that secrets were not correctly passed.

explicitly check docker login vars are set

---

Earthfile
ast/env_var.go
ast/listener.go
util/shell/env_var_name.go

The `ast` submodule was a little broken because it was importing `github.com/earthly/earthly/util/shell` but did not have `github.com/earthly/earthly/util/shell` in its `go.mod`.  Running `go mod tidy` fixed that; but the whole point of having the `ast` package as a separate submodule was to allow other packages to import `ast` without downloading the whole `earthly` project.
The quick and dirty solution is to reverse the imports so that the `util/shell` package is importing `ast`, not the other way around.
This PR also fixes our `+unit-test` target to run tests against our current go submodules, since `./...` ignores submodules.

Decouple the `ast` submodule from the `util` package

---

util/llbutil/secretprovider/cloud.go

This fixes a bug where using `VERSION --use-project-secrets 0.6` causes secrets to be lookedup in the cloud with an empty org or project, which returns an unauthorized error rather than the expected `unable to lookup secret SECRET3: not found` error message (which causes the `+secrets-test` test to fail).

dont attempt secrets lookup when org or project not set

---

Earthfile
docs/ci-integration/pull-through-cache.md
docs/guides/registries/self-signed.md
tests/registry-certs/Earthfile
tests/remote-cache/Earthfile

If both http=true and insecure=true are set, buildkit will create two registry entries, one on port 80, and the other on port 443 and will attempt to connect to either server.

buildkit http and insecure options are mutually exclusive

---

cmd/earthly/build_cmd.go
cmd/earthly/flags.go

The --use-inline-cache and --save-inline-cache flags have been causing issues in some cases and we don't yet know the root cause. For now, we're removing the implicit enabling of these flags in --ci.

cmd/earthly: --ci no longer implies --use-inline-cache or --save-inline-cache

---

Earthfile
examples/cloud-secrets/Earthfile
examples/secrets/Earthfile

Move the cloud-secrets example to a seperate Earthfile, and update it to make use of the `PROJECT` command.

Update cloud-secrets example

---

.github/workflows/reusable-test.yml
tests/Earthfile

The tests/web test requires access to the earthly-technologies cloud-secrets account, which causes community contributors from running the high-level +test target.
This moves them to a separate target, which is triggered directly from GHA.

move tests that need earthly-technologies access

---

docs/SUMMARY.md

Follow up for previous Pull request: [2361](https://github.com/earthly/earthly/pull/2361) that added a little documentation on how to use earthly with woodpecker-ci. 
It was not showing up in the documentation yet and it seems that the missing occurrence in the summary might be the cause.

Documentation: add link to woodpecker-ci in SUMMARY.md

---

.github/workflows/ci-staging-deploy.yml
Earthfile
buildkitd/Earthfile
release/Earthfile
release/release.sh

push staging builds to a separate earthly/earthly-staging and earthly/buildkitd-staging docker images, to make it easier for users to differentiate between version tags when viewing docker hub.

move staging builds to separate docker image

---

buildkitd/Earthfile

The default wasn't working as intended, which resulted in every `BUILDKIT_PROJECT` value being treated as a local target (even when clearly a remote).
Example: 
```
$ earthly ./buildkitd+buildkitd --BUILDKIT_PROJECT=github.com/earthly/buildkit:earthly-main
<snip>
./buildkitd+buildkitd | BUILDKIT_PROJECT=github.com/earthly/buildkit:earthly-main
./buildkitd+buildkitd | *cached* --> IF [ "$BUILDKIT_PROJECT" != "" ]
./buildkitd+buildkitd | BUILDKIT_PROJECT=github.com/earthly/buildkit:earthly-main
./buildkitd+buildkitd | *cached* --> IF case "$BUILDKIT_PROJECT" in "../*") true;; "*") false;; esac
Error: build target: build main: failed to solve: buildkitd/Earthfile line 20:4 apply FROM ../github.com/earthly/buildkit:earthly-main+build: apply build …
```

Fix logic for custom BUILDKIT_PROJECT

---

ast/lexer.go
tests/invalid/Earthfile
tests/invalid/leading-whitespace.earth

In certain edge cases, erroneous indentation was causing us to call popRecipeMode too many times. Simply adding a 'recover' changes our panic into a syntax error.
Resolves #2603

ast: recover from popping too many modes

---

features/features.go

This is something I had noticed a long time ago, but minor enough that it wasn't worth a dedicated PR, and then forgot by the time I had a real PR where I could shoehorn it in.
When @vladaionescu pointed me to https://github.com/earthly/earthly/blob/next/docs/earthfile/features.md and I saw the bad description, I immediately recognized it and became 99% sure that doc was auto-generated from code.  So this is more about fixing the docs, and assuming this is first step.  And since this is truly "code", I assume it should be merged to 'main' (and you'll do something after to get it and/or the generated content to 'next').

Fix description for `--use-chmod` feature

---

cmd/earthly/build_cmd.go
debugger/common/common.go

In receiveFileVersion2, a deferred error check was checking the wrong error variable. This meant that we never entered the if block.

cmd/earthly: fix deferred error check

---

docs/remote-caching.md

The text of this info box makes it seem like the only thing required to have the cache available for future builds are the --ci and --push flags. When, in fact, you must provide those flags to a target or something connected to it via BUILD commands.

Mention explicitly that you must push images to use them as cache

---

CHANGELOG.md
cloud/secret_new.go
cmd/earthly/main.go
cmd/earthly/registry_cmds.go
cmd/earthly/root_cmds.go
cmd/earthly/secret_cmds.go
tests/Earthfile
tests/autocompletion/Earthfile
tests/registry-command/Earthfile
tests/registry-command/lock.sh
tests/registry-command/test-project.sh
tests/registry-command/test-user.sh
tests/registry-command/unlock.sh
tests/web/Earthfile

Adds `earthly registry login/list/logout` commands which are used to manage cloud-stored registry credentials.

commands for cloud-stored registry auth

---

features/features.go
tests/version/Earthfile
tests/version/invalid-feature-flag-override.earth

Boolean overrides for feature flags should not be possible; this change
will now raise an error instead of silently ignoring them.
While it is technically possible to implement disabling feature flags,
we chose to raise an error instead to encourage users to fully adopt
a new VERSION.
This is because feature flags are for experimental features, once they
are promoted they become part of the forward-direction of earthly;
allowing users to adopt the latest version while individually flipping a
feature off may lead to buggy experiences.
If a user really wants to disable a feature, then they will have to
remain at a previous VERSION, and instead select the (experimental) features
they wish to enable (with caution).

fix: raise error when setting feature flag values

---

earthfile2llb/converter.go
tests/remote-cache/Earthfile
tests/remote-cache/test.earth

If a user is using VERSION 0.7 without any explicit WAIT block, we will use the build function to perform the export due to a bug that exists in the earthly-specific Export buildkit grpc call, which skips the inline cache.

work-around for implicit WAIT/END inline cache bug

---

builder/builder.go

WAIT/END makes it possible to perform a push or local output during the build phase, since these operations may have occurred prior to the push and local output phases, these phases will be renamed to be a summary to make it more clear they don't imply the order.

rename output phases to summary

---

release/README.md
release/release.sh

The prerelease value was not correctly passed to the +release-github target, which caused the RC to show up as latest.
This additionally re-orders the earthly version detection logic to handle the case where the earthly command override is missing.

fix release.sh not passing prerelease arg

---

CHANGELOG.md
earthfile2llb/interpreter.go
features/features.go
tests/Earthfile
tests/copy-keep-own.earth

In order to copy a file from one target to another with the same ownership information requires the `--keep-own` flag be applied to both `SAVE ARTIFACT` and `COPY`.
The final `COPY`'s `--keep-own` flag should be sufficient for determining if the original file's permissions are to be copied over or not.
This fixes #2640

always apply SAVE ARTIFACT --keep-own flag

---

CHANGELOG.md

Clarify that the new `--push` behavioud only applies to `VERSION 0.7`, and does not affect `VERSION 0.6` Earthfiles.

CHANGELOG: --push change only applies to v0.7

---

CHANGELOG.md
cloud/satellite.go
cmd/earthly/satellite_cmds.go

Newly launched satellites will now be in the medium size instead of large (which is the server default).

Medium is Default Size for Satellites

---

docs/remote-caching.md

https://docs.earthly.dev/docs/earthfile#what-is-being-output-and-pushed is a dead link (maybe it used to work, but something changed with gitbook?)
Let's point to the heading of `#build` (alternatively we could point to the description section of build, but gitbook references that as `#description-6` which is fragile)

fix remote-caching deadlink

---

CHANGELOG.md
ast/alias_test.go
ast/antlrhandler/error_listener.go
ast/antlrhandler/error_strategy.go
ast/antlrhandler/hint_error.go
ast/ast.go
ast/ast_test.go
ast/parse_errors_test.go
ast/parser/export.go

Our parser/lexer syntax errors are extremely hard to comprehend and have been causing confusion. This updates our ErrorListener and ErrorStrategy with a few niceties, attempting to add extra context about the incorrect syntax.
These cases are pretty minimal, but they're a start.
---
For issue #2656 in particular, here's the updated error message:
```
Error: build target: build main: failed to solve: resolve build context for target +foo: Earthfile line 5:45 '
': invalid syntax
Hints:
- I got lost looking for '=' - did you define a key/value pair without a value?
```

ast/antlrhandler: add hints to syntax errors

---

analytics/analytics_test.go
analytics/imports_test.go
autocomplete/complete_test.go
autocomplete/imports_test.go
buildcontext/gitlookup_test.go
buildcontext/imports_test.go
domain/domain_test.go
domain/domain_windows_test.go
domain/imports_test.go
features/features_test.go
features/imports_test.go
util/gitutil/detectgit_test.go
util/gitutil/imports_test.go
util/stringutil/imports_test.go
util/stringutil/scrub_test.go
variables/builtin_test.go
variables/imports_test.go
variables/parsenew_test.go
variables/reserved/imports_test.go
variables/reserved/names_test.go
variables/util_test.go

Rather than do a dot import, i.e.
. "github.com/stretchr/testify/assert"
testify assertion functions will be defined in a corresponding `imports_test.go` file, to make it more obvious where these functions are coming from. This makes it easier when grepping.
Furthermore, an upcoming linter change started complaining about these imports.

import testify functions explicitly

---

variables/collection.go

Some docker images (e.g. opensuse/tumbleweed) don't define the `PATH` environment (but rather defines it inside the image container layers).
This fixes https://github.com/earthly/earthly/issues/290#issuecomment-1410735538

If PATH is missing, shell out to determine it

---

analytics/analytics.go
cloud/account.go
cloud/analytics.go
cloud/auth.go
cloud/auth_test.go
cloud/client.go
cloud/grpc.go
cloud/http.go
cloud/log.go
cloud/logstream.go
cloud/org.go
cloud/org_new.go
cloud/project.go
cloud/satellite.go
cloud/secret.go
cloud/secret_new.go
cmd/earthly/account_cmds.go
cmd/earthly/buildkit.go
cmd/earthly/common.go
cmd/earthly/project_cmds.go
cmd/earthly/satellite_cmds.go
logbus/logstreamer/logstreamer.go
logbus/setup/setup.go
util/llbutil/authprovider/cloudauth/authprovider.go
util/llbutil/secretprovider/cloud.go

As per https://github.com/golang/go/wiki/CodeReviewComments#interfaces an interface should be defined wherever it is used, and not in the cloud package.
If an interface is needed by a specific caller of the client, then it's best to create a much smaller interface tied to the use of the client, which will make it more clear which methods must bet implemented for that specific portion of the code.

cloud.Client should just be a struct

---

logbus/logstreamer/helheim_mocks_test.go
logbus/logstreamer/import_test.go
logbus/logstreamer/logstreamer.go
logbus/logstreamer/logstreamer_chaos_test.go
logbus/logstreamer/logstreamer_test.go

I also added a test for `Close()` draining when it's being flooded with messages, because I think it would have issues with that without the mutex lock (and since it's a channel, I wouldn't be surprised if the mutex lock is removed some day). However, due to the mutex lock, it's actually not a current problem. But having a test there for if/when the mutex lock is removed is nice.

logbus/logstreamer: fix drain blocking on read from nil channel

---

release/release.sh

Fixes the staging release script, which was incorrectly changing the working directory before resolving the absolute path of the overridden, relatively-referenced `earthly` binary.

fix staging release script

---

CHANGELOG.md
ast/ast_test.go
ast/lexer.go

This solves an issue where unindented comments in recipe bodies would trigger a DEDENT token, causing parser errors when the comments really should just be ignored.
This also incidentally allows documentation to be on a line immediately following a comment if that comment is in an indented block (e.g. if the previous target ended with a comment).
Resolves #2697

ast: handle unindented comments in recipe bodies

---

.github/workflows/reusable-misc-tests.yml
scripts/tests/earthly-image.sh

The satellite test needs a valid docker hub credential, or it will be rate-limited.
Perhaps one day we will be able to configure a mirror; however, that option doesn't exist currently for satellites.

satellite test needs docker hub access

---

earthfile2llb/converter.go

running `RUN --push --ssh ...` didn't correctly display the --ssh flag in the output logs:
Before:
--> RUN --push stat $SSH_AUTH_SOCK
After:
--> RUN --push --ssh stat $SSH_AUTH_SOCK

display --ssh in RUN command

---

CHANGELOG.md

Somehow we lost an entry from RC1 in RC2 and subsequent releases of 0.7. This restores that entry to later versinos in the changelog.

CHANGELOG: add back lost 'changed' entry from 0.7.0-RC1

---

examples/scala/Earthfile

The scala example did not work on my MacBook Pro M2 Max running colima. The process was stalled indefinitely (or at least over 1 hour).  Memory was not the issue, but the base image.
Just running a compilation with `docker run -it --rm -v $PWD:/work -w /work hseeberger/scala-sbt:11.0.7_1.3.13_2.11.12 sbt package` also did not compleet. 
Using the `scala-sbt` as base image did work.

Update base image for scala example

---

cmd/earthly/buildkit.go
cmd/earthly/flags.go
cmd/earthly/main.go

This also adds aliases to other existing TLS-related flags to more closely match existing conventions around 'translating' between a CLI flag, environment variable, and config entry.

Allow toggling TLS and setting CA from CLI/environment

---

tests/Earthfile
tests/true.earth

the "failed to send analytics" message should only ever appear under verbose logging.

add test for silent analytics failure

---

CHANGELOG.md
cmd/earthly/main.go
scripts/tests/interactive-debugger/interactive-run/test-interactive-run.py

This detects and silences failures of the form
Error: build target: build main: failed to solve: unlazy force execution: process "/bin/sh -c GLIBC_VER=2.31-r0 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /usr/bin/earth_debugger /bin/sh -c '... did not complete successfully: exit code: 1
As they are displayed in a clearer format higher up in the output.

make RUN ... errors easier to read

---

earthfile2llb/earthfile2llb.go
earthfile2llb/save_image_wait_item.go
states/states.go
tests/wait-block/common/test.sh
tests/wait-block/save-image-push-implicit-wait-block/Earthfile
tests/wait-block/save-image-push-implicit-wait-block/test.sh

Fixes a race bug where the --push option was not correctly propagated to
targets that were first indirectly referenced by a `FROM` or `COPY`, but
then later referenced by an explicit `BUILD`.
This was missed in eee3db502797bfb74e91886db59e685434e15ccc
and fixes https://github.com/earthly/earthly/issues/2762.

propagate push to wait block items

---

cmd/earthly/buildkit.go

These are enabled by default now in 0.7 anyways

Remove warning logs about feature flags used on satellites

---

docs/basics/part-1-a-simple-earthfile.md
docs/basics/part-2-outputs.md
docs/basics/part-3-adding-dependencies-with-caching.md
docs/basics/part-4-args.md
docs/basics/part-5-importing.md
docs/basics/part-6-using-docker-with-earthly.md
docs/best-practices/best-practices.md
docs/earthfile/earthfile.md
docs/earthly-command/earthly-command.md
docs/earthly-config/earthly-config.md
docs/guides/advanced-local-caching.md
docs/guides/build-args.md
docs/guides/debugging.md
docs/guides/integration.md
docs/guides/udc.md

My original intent was only to update the `.env`/`.arg`/`.secret` changes, as that was very noticeable.  Then I started noticing other things on the way.
There are still a number of `0.6.x` references that I left untouched for various reasons.  The subset I changed were mostly around the 'language' (e.g., `VERSION 0.7`), which are very user-facing and 'static'.  The rest were largely around advanced deployment, esp. download links and docker tags, which are probably less visible and are moving targets.

Misc. doc updates (0.7 specific)

---

CHANGELOG.md
util/llbutil/authprovider/cloudauth/authprovider.go

If an auth provider fails to login using the credentials stored in earthly's cloud-based registry config, a warning will be displayed.
Additional debug messages are now displayed in `--verbose` mode.

improve authprovider warnings

---

buildcontext/gitlookup.go
util/stringutil/scrub.go
util/stringutil/scrub_test.go

Adds additional verbose logging messages for when git substitution is used.

verbose logging for git matchers

---

Earthfile

This stopped working (reason currently unknown), but probably something with the previous http/insecure changes, or the buildkit update.  This writes out an explicit stanza for the mirror registry.
Previously:
```
[registry."docker.io"]
mirrors = ["mymirror"]
http = true
```
After this change:
```
[registry."docker.io"]
mirrors = ["mymirror"]
http = true
[registry."mymirror"]
http = true
```
The buildkit docs (https://github.com/moby/buildkit/blob/master/docs/buildkitd.toml.md?plain=1#L97-L101) show the current way being syntantically correct.  We probably assumed that `http = true` would apply to the list of mirrors, but doesn't.  At least anymore.  It probably applies to the registry itself.
Regardless of why/when it stopped working, this makes it work properly again.  The 'fixed' …

Fix usage of Hub mirrors for testing

---

cmd/earthly/build_cmd.go
earthfile2llb/converter.go
earthfile2llb/interpreter.go
tests/try-catch/try-finally-fail/.gitignore
tests/try-catch/try-finally-fail/Earthfile
tests/try-catch/try-finally-fail/test.sh

Fixes #2800 
This allows all three failures scenarios to work, namely:
1. Saving to the current directory (`AS LOCAL ./`)
2. Saving to a child directory (`AS LOCAL docs/`)
3. Saving to a named file in a child directory (`AS LOCAL docs/data.txt`)
I know this is experimental functionality, which is both a reason you may accept (not as worried about compatibility, etc.) or reject (wanting to address this in a different way in a future rewrite) the change.  Since I had already done the investigation, which was the hard part, I figured I'd take my chances.

Allow saves to more destinations on `TRY` failures

---

ast/ast_test.go
ast/listener.go

This allows engineers to add documentation with indentation, e.g. for sample output.
Resolves #2747

ast: trim a consistent level of spacing from docs

---

cmd/earthly/build_cmd.go
conslogging/conslogging.go

A few things I wasn't sure about and would like to get your opinion on:
- Should printing these messages be more opinionated (i.e create some special function to print log in a specific color, not expose `ColorPrintf`)?
- Moving the location of `Streaming logs to` outside of the go routine, means that it might be printed before we start uploading the log, is that ok?
- Is the color ok (see attached screenshots)?
- Not directly related to this PR, but I noticed we have a private function `makeColor`, is it needed given `color.New` is available (the difference is the no color check in the latter)?
terminal - 
ci -

Modify color and location for log mesage+url

---

ast/ast_test.go
ast/lexer.go

When we're outside of RECIPE mode, there's no reason to consider adjusting the indentation level, because INDENT and DEDENT tokens aren't valid anyway.
Resolves #2826

ast: fix lexer error in base target IF statements

---

cmd/earthly/common.go
cmd/earthly/main.go
cmd/earthly/root_cmds.go
docs/earthly-command/earthly-command.md

This adds two command line options for pruning the cache.
* `--keep-duration`, which will drop all cache older than this duration. It expects a string parseable by `time.ParseDuration`.
* `--target-size`, which will drop the oldest items from the cache until the size is reached. It expects a string parseable by `humanize.ParseBytes` (which we already have in our `go.mod`).
I presume docs need to be added, I'll append those to this PR if these options look ok.

Add command line options for time/size based partial cache pruning

---

release/ami/cleanup.sh
release/ami/image.pkr.hcl
release/ami/install.sh

Amazon Linux is proving to be more stable in many instances; future releases (and some past) need to be updated.

Change Earthly AMI releases to use Amazon Linux 2

---

.gitignore
ast/tests/if-exists.ast.json
tests/Earthfile
tests/if-exists.earth
util/llbutil/copyop.go

Fixes #2541 
Given source `+target/data`, the current code translates that to wildcard `[/]data`, which never matches.  This translates it to `[d]ata` (analogous to how it works for classical copies).
I'm not sure what I'm supposed to "carefully look for" in regards to the AST changes (or if I was even right to generate them); the activity on #1557 (a very similar issue/solution) was my guide.

Allow `COPY --if-exists` to work with target sources

---

cloud/client.go
cloud/http.go
cmd/earthly/common.go
cmd/earthly/flags.go
cmd/earthly/main.go
tests/Earthfile

fix https://github.com/earthly/earthly/issues/2761
This change sets a timeout to establish a http connection to the API server.
Note that the issue this fixes did not seem to relate to analytics, even with analytics disabled, Earthly was stuck on trying to ping the API server.
Also note that this sets a timeout on connection errors such as Deadline exceeded, for which we do not retry.
Other types of connection errors do get retried and as a result the overall time might be bigger than the set timeout.

Add http connection timeout

---

builder/image_solver.go

Fixes the `Warning: Could not detect digest for image %s. Please update your buildkit installation.` error which prevented the digest from being loaded for image names of the form `docker.io/<user>/<img>` (where as previously images were prefixed with `docker.io/library/<user>/<img>`).

fix missing digest error for some docker.io images

---

release/ami/image.pkr.hcl

This encrypts the AMI by default on release, helps with compliance.

Encrypt AMI release by default

---

earthfile2llb/converter.go

Fixes regression introduced in 4b139f43db7de4bb801e5070d304a469ed4b758a which incorrectly set TargetPlatforms in the dockerui Config rather than keeping it in ConvertOpt. This resulted in implicitTargetPlatform being set to true, which caused the host platform (e.g. darwin) to be propigated to the target platform.

bugfix: set TargetPlatform in ConvertOpt

---

scripts/tests/interactive-debugger/docker-compose/Earthfile
scripts/tests/interactive-debugger/docker-compose/docker-compose.yml
scripts/tests/interactive-debugger/docker-compose/rot13/Dockerfile
scripts/tests/interactive-debugger/docker-compose/rot13/README
scripts/tests/interactive-debugger/docker-compose/test-docker-compose.py

Use a pre-built image to speed up the tests.

use pre-build rot13 image in interactive-test

---

.github/workflows/reusable-bootstrap-integrations.yml
.github/workflows/reusable-example.yml
.github/workflows/reusable-export-test.yml
.github/workflows/reusable-git-metadata-test.yml
.github/workflows/reusable-misc-tests.yml
.github/workflows/reusable-push-integrations.yml
.github/workflows/reusable-repo-auth-tests.yml
.github/workflows/reusable-secrets-integrations.yml
.github/workflows/reusable-test-local.yml
.github/workflows/reusable-test.yml
release/Earthfile
release/release.sh

Since most users will not have 'docker.io' added to podman's search registries by default, we need to fully qualify the earthly-buildkitd image by default.
Resolves #2834

fully qualified earthly-buildkitd

---

docs/earthly-config/earthly-config.md

If no value is specificed in buildkit.toml, buildkit will set it adaptively: https://github.com/moby/buildkit/blob/54b8ff2fc8648c86b1b8c35e5cd07517b56ac2d5/cmd/buildkitd/config/gcpolicy_unix.go#L16

clarify default cache size

---

autocomplete/complete.go
tests/autocompletion/Earthfile

Given
```Earthfile
VERSION 0.7
FROM alpine
test:
ARG --required input
RUN echo "$input" > file
SAVE ARTIFACT file
```
the command `earthly +test -<TAB>` will autocomplete (`--input`), but `earthly -a +test/file -<TAB>` will not.  This change makes them behave identically.
If the item in target position does not parse as a target, it will try parsing it as an artifact.  If it does parse, the artifact's target will then be used to offer build arg completion.

Allow build args to auto-complete in artifact mode

---

earthly-entrypoint.sh

I overlooked the lint error from the previous PR, this should fix it.

Add quotes to fix lint error in earthly-entrypoint script

---

.github/workflows/ci-docker-ubuntu.yml

Due to flaky tests, our pre-release workflow is not running; this means we are no longer dogfooding our code in main via the ./earthly script.
If the code is merged into main; then we need to be dogfooding it -- even if it causes tests to fail -- otherwise we won't ever taste bad dogfood.

loosen the tests required for a pre-release

---

builder/builder.go
cmd/earthly/build_cmd.go
cmd/earthly/flags.go
cmd/earthly/main.go
earthfile2llb/earthfile2llb.go
logbus/logstreamer/logstreamer_orchestrator.go
logbus/setup/setup.go

This PR will help ensure that logs are (almost) always sent to the log streaming service when streaming is enabled. It does so by looking for `EARTHLY_ORG` and `EARTHLY_PROJECT` and initializing the stream using those values when present. The remote end will verify that the currently logged-in user has permission to write logs for the given org/project combination.

Initialize log streaming upfront if org/project envs set

---

CONTRIBUTING.md
Earthfile

Since delve needs optimizations disabled in order to properly track things like variable and function names, line numbers, and so on, it needs binaries to be compiled with some flags in order to properly debug them. This allows those flags to be set and documents their use.

Earthfile: support -GO_GCFLAGS overrides for delve debugging

---

.github/workflows/ci-podman-ubuntu.yml
.github/workflows/reusable-example.yml

This is a follow-up to #2895, finally getting our podman tests green again. The two final problems:
1. We need to pass along the environment when using `sudo`, using `sudo -E`.
2. Due to changes in podman setup, we need to re-bootstrap after rebuilding earthly.
After those changes, we should :crossed_fingers: have green podman tests again.

fix podman tests

---

.github/workflows/reusable-example.yml
.github/workflows/reusable-export-test.yml

We no longer use a default registry in our podman tests (because most
podman installs don't come with a default registry), so now we always
need to specify the registry when logging in. This adds the docker.io
registry to any login commands that were missing it in GHA.

.github: always specify registry when logging in

---

buildcontext/parsefeatures.go
features/features.go
tests/Earthfile
variables/collection.go
variables/collection_test.go
variables/imports_test.go

This also includes a very rudimentary first pass at unit tests for `variables.Collection`.
Resolves #2879

variables: support builtins in --arg-scope-and-set

---

CHANGELOG.md
cmd/earthly/build_cmd.go

Fixes https://github.com/earthly/earthly/issues/2883

secret key IDs should follow ARG naming scheme.

---

earthfile2llb/converter.go
tests/Earthfile
tests/command-nested-global.earth
variables/collection.go
variables/scope.go

When calling `DO +SOME_CMD`, we were dropping the existing overrides. This meant that globals were (sometimes?) losing their overrides if any UDC called `DO +SOME_OTHER_CMD`.
This updates DO scopes to include existing overrides, while still letting the `DO` call's args take precedence.
Resolves #2920

earthfile2llb: when entering a DO scope, ensure existing overrides are passed through

---

cloud/satellite.go
cmd/earthly/satellite_cmds.go
go.mod
go.sum

The following command can now be used to alter the size of the satellite:
```
earthly satellite update --size <new-size> <existing-satellite>
```
This is important for CI runners, which currently have no other way to specify a size other than medium.
Changing size will also drop the existing cache. I will explain that in a separate docs PR.

Support changing size of satellites and CI runners

---

cmd/earthly/build_cmd.go

If a user really wants to disable limitting of conversion_parallelism, then the use can just set this to 99999999.
fixes #2898

prevent panic when conversion_parallelism <= 0

---

CHANGELOG.md
earthfile2llb/converter.go
earthfile2llb/save_image_wait_item.go
earthfile2llb/wait_block.go
tests/wait-block/save-image/test.sh

An image should only be pushed when the `SAVE IMAGE --push ...` command is used in combination with earthly being run with the --push flag on the cli; this fixes a regression where simply running `earthly --push` would cause all `SAVE IMAGE ...` commands to be pushed regardless of if the command had a `--push` or not.
Fixes #2923

fix: SAVE IMAGE --push flag was ignored

---

scripts/tests/earthly-image.sh

Typically github actions exposes the dockerhub credentials and earthly token; however, this makes it more difficult to run locally -- when they are missing, we will pull them in from earthly secrets.

earthly-image test: lookup secrets when missing

---

buildkitd/Earthfile
buildkitd/runc-ps

A small script which displays all runc instances and displays what program they are running. This is useful for debugging buildkit instances which are under heavy load.

runc-ps script for earthly-buildkitd container

---

buildkitd/buildkitd.go

Fix a context timeout value that, during constant retrying of an operation, is 'overflowing' and eventually reaching 0s. The 0s timeout caused unexpected behavior like not registering the true error.
Fixes #2942
I logged the value of attemptTimeout variable during an earthly invocation to a remote buildkitd which did not respond. Note the value eventually settling to 0s:
buildkitd | Connecting to tcp://some_server:8372
...
attempt timeout 596523h14m8s
attempt timeout 1193046h28m16s
attempt timeout 2386092h56m32s
attempt timeout -351909h41m29.709551616s
attempt timeout -703819h22m59.419103232s
attempt timeout -1407638h45m58.838206464s
attempt timeout 2308818h2m36.033138688s
attempt timeout -506459h29m21.64327424s
attempt timeout -1012918h58m43.28654848s
attempt timeout …

fix: context with timeout of 0s

---

buildkitd/docker-auto-install.sh
buildkitd/dockerd-wrapper.sh

The legacy docker-compose stand-alone program is no longer avaiable under 3.18.

alpine 3.18 uses the docker compose plugin

---

tests/registry-command/lock.sh

This is to prevent a lock from being forced open too early; which then propigates to an unlock error such as
unlock failed: unexpected lock contents (expected 6b40e388-71d9-41dd-b843-d486e7518f55; got 8ce0c485-4edc-4d27-9cda-5dad37164086)

increase lock timeout

---

.github/workflows/ci-docker-ubuntu.yml
.github/workflows/reusable-misc-tests.yml
.github/workflows/reusable-wait-block-override.yml

The wait-block override test runs all of +test with a specific override flag; it can take 20+ minutes and should be a separate test (to make retrying failures easier).

move wait-block override test to separate target

---

docs/earthfile/earthfile.md
docs/earthfile/features.md

This cherry-picks #2964 onto the `0.7` docs branch.

docs: add information about --arg-scope-and-set

---

cmd/earthly/buildkit.go
cmd/earthly/satellite_cmds.go

Some context was missing in a recent auth error reported by satellite users. 
The error reported by the user was:
```
Error: could not construct new buildkit client: unable to authenticate
```
The additional context added here should help both us and the user debug similar auth issues.

Improve error reporting in satellite auth

---

Earthfile
cloud/client_offline_test.go
cloud/imports_test.go

This creates a new +offline-test target, which is used to validate the cloud client can be created without performing any network I/O (which is important for autocompletion and cases where a user has set DO_NOT_TRACK).

test cloud client can be created without network

---

earthly

The ./earthly prerelease script requires md5sum to detect changes in the .earthly_version_flag_overrides file.

./earthly should check that md5sum is installed

---

buildkitd/buildkitd.go

This log often looks concerning to users, however, long GC runs in buildkit are not as unusual as we thought when we initially added this warning.

Remove Buildkit GC warning log

---

CHANGELOG.md
buildcontext/excludes.go
buildcontext/excludes_test.go
buildcontext/local.go
docs/earthfile/earthfile.md
docs/earthfile/features.md
earthfile2llb/converter.go
features/features.go
features/features_test.go
tests/Earthfile
tests/from-dockerfile-dockerignore.earth

This PR adds support for using a `.dockerignore` file in target using `FROM DOCKERFILE` with <build context> from the host system.
The feature is enabled using `--use-docker-ignore` feature flag.
The `.dockerignore` file will not be used if the <build context> contains an `.earthlyignore` or `.earthignore` file.

Use .dockerignore in FROM DOCKERFILE targets

---

CHANGELOG.md
cmd/earthly/satellite_cmds.go

This fixes a bug that was causing manual updates to revert the size to medium if the user previously had a different size set.

Remove default size in satellite update

---

cloud/client.go
cloud/org.go
cloud/satellite.go
cmd/earthly/buildkit.go
cmd/earthly/satellite_cmds.go
scripts/tests/earthly-image.sh

additionally fixes a bug where an incorrect satellite would be displayed as selected when a member is part of two orgs which contain the same satellite name.

introduces a call to list satellites by org name

---

buildkitd/Earthfile
buildkitd/entrypoint.sh
go.mod
go.sum

This will automatically cancel builds that have run for longer than the configured timeout. Set to 24 hours by default (I think this reasonable, but up for debate).

Configure Buildkit Session Timeout

---

tests/registry-command/Earthfile
tests/registry-command/test-multi.sh
util/llbutil/authprovider/authprovider.go

Once an authprovider responds for a specific host, only subsequent requests should be sent to that authprovider; similarlly if an authserver has responded with ErrAuthProviderNoResponse (indicating it doesnt have credentials) it shouldn't be requeried for credentials.

keep track of which authprovider responded

---

cmd/earthly/satellite_cmds.go

This will now be determined by the backend when size is empty. The defaults are small for free tier, medium for paid tiers.
It is especially important to remove this for free tier users, as it will cause errors with it set to medium by default since their plan doesn't allow that size.

Remove default size in satellite launch

---

.github/workflows/ci-docker-satellites.yml
.github/workflows/ci-docker-ubuntu.yml
.github/workflows/ci-podman-ubuntu.yml
.github/workflows/reusable-race-test.yml
.github/workflows/reusable-test.yml
Earthfile
tests/Earthfile

This splits up some of our longest-running (and most likely to flake) GHA jobs into smaller chunks. This helps specifically in the case where a test flakes, requiring us to re-run the job - taking around 10 minutes each retry instead of 45.
Hopefully, this will also give us a clearer picture of which tests are flaking most often, so we know which ones need to be fixed.

.github: spread out multiple test targets across multiple workflows

---

builder/builder.go
cmd/earthly/build_cmd.go
earthfile2llb/converter.go
earthfile2llb/earthfile2llb.go
util/llbutil/authprovider/authprovider.go
util/llbutil/authprovider/doc.go
util/llbutil/authprovider/helheim_mocks_test.go
util/llbutil/authprovider/imports_test.go
util/llbutil/authprovider/multiauthprovider_test.go
util/llbutil/authprovider/podman.go
util/llbutil/authprovider/podman_test.go

Part of the improvements in PR #3026 was a form of caching authproviders that don't have any credentials configured for a given host. This did not account for the project being set *after* the first attempt at loading credentials.
This commit updates the aggregated authprovider to invalidate its cache of per-host child auth providers when AddProject is called.

authprovider: invalidate cache when AddProject is called

---

cloud/account.go
cmd/earthly/account_cmds.go
go.mod
go.sum

```
$ ./build/linux/amd64/earthly account create-token --expiry never delete-me-4
created token "UEBvw7Yau1WvDBu9BJQhQNJGX7JE8pmrmjeAwXMfYxKTMvXGC8SwS1PbWWnRLe29" which will never expire; save this token somewhere, it can't be viewed again (only reset)
$ ./build/linux/amd64/earthly account create-token delete-me-5 
created token "ELdaUHXyXMbEJ86PLQgI6hsxzwqjg6DcWXiYyAqIZ7XjmqUvtKNrcVjBAwZTux1y" which will never expire; save this token somewhere, it can't be viewed again (only reset)
$ ./build/linux/amd64/earthly account list-tokens             
Token Name   Read/Write  Expiry
local        r           2023-06-14T23:38 UTC *expired*
delete-me    r           2024-07-12T22:12 UTC
local-2      rw          2023-09-13T21:43 UTC
delete-me-2  r           Never
local-3      rw …
```

Improve output for indefinite auth tokens

---

buildkitd/Earthfile
go.mod
go.sum
tests/local/Earthfile

Verifies https://github.com/earthly/buildkit/pull/19, which in turn fixes https://github.com/earthly/earthly/issues/3094.
This ensures that an existing file is truncated prior to writing; otherwise, if the source (`X`) is smaller than the destination (`Y`), the destination contains all of `X` bytes at the beginning, and `Y-X` bytes of the original destination at the end.

Tests to verify correct (local) overwrite behavior

---

scripts/tests/interactive-debugger/docker-compose/test-docker-compose.py

This test used to do a "select * from countries limit 1" which would return "Afghanistan"; however, the test was simplified to use a rot13 echo server instead of starting up a database -- but this error message was never updated.

fix docker-compose interactive debugger error string

---

scripts/acbtest/acbgrep
scripts/acbtest/acbtest
scripts/acbtest/update.sh
scripts/tests/cloud-docker-credentials-integration.sh
scripts/tests/docker-build/integration.sh
scripts/tests/earthly-image.sh
scripts/tests/export.sh
scripts/tests/satellites-integration.sh
scripts/tests/secrets-integration.sh
tests/local/with-docker-compose-local-reg/Earthfile
tests/local/with-docker-compose-local/Earthfile

`acbgrep` from https://github.com/alexcb/acbtest; is a wrapper around grep which will display a failure message if grep fails (rather than silently exiting with an error code).
When data is pipped in, it will also display the contents of the data that is being grepped -- this makes it easier to see the full output of earthly if grep fails to find an expected string.

use acbgrep to make test failures more clear

---

cmd/earthly/account_cmds.go

This PR fixes the following issue with v0.7.12.
```
$ earthly account create-token --write --expiry 2023-12-01 some-token2c
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1015d1fb0]
goroutine 1 [running]:
main.(*earthlyApp).actionAccountCreateToken(0x14000514800, 0x1400034a680)
github.com/earthly/earthly/cmd/earthly/account_cmds.go:481 +0x2c0
github.com/urfave/cli/v2.(*Command).Run(0x14000568240, 0x1400034a240)
github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4f8
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0x14000003ba0, 0x1400055f600)
github.com/urfave/cli/v2@v2.3.0/app.go:434 +0x948
github.com/urfave/cli/v2.(*Command).startApp(0x1400056d560, 0x1400055f600) …
```

Fix code error with token expiry parsing

---

docs/cloud/managing-permissions.md

The documentation wasn't clear that building (or other normal operations during the course of building) were permitted with `read` permissions.

Clarify satellite docs

---

scripts/tests/interactive-debugger/interactive-run/test-interactive-run.py
scripts/tests/interactive-debugger/test-interactive.py

Display a summary of the total number of tests that passed, and display which ones failed at the end of the test runner.
Without this, a user might have a previous test fail, but the final test passes and displays:
/test # cat /data.txt | base64 -d
e88cc2b8-c179-4ed7-8eae-207a0ef7546c/test # [6n
test-docker-compose passed
Error: Process completed with exit code 1.
which is confusing, as they might not know to scroll up looking for a previous test failure.
Now we will display:
== Summary ==
2/3 tests passed
test-interactive-run failed with exit code=1

print summary of interactive debugger tests

---

Earthfile
cloud/account.go
cloud/auth.go
cloud/auth_test.go
cloud/client.go
cloud/grpc.go
cloud/http.go
cloud/org.go
cmd/earthly/account_cmds.go
scripts/tests/cloud-docker-credentials-integration.sh
scripts/tests/export.sh
scripts/tests/satellites-integration.sh
scripts/tests/secrets-integration.sh
tests/Earthfile
tests/account/Earthfile
tests/account/test-login.sh

if there's a valid auth.jwt, earthly should not re-login (potentially with different credentials).

don't change the currently logged in user

---

cmd/earthly/init_cmds.go
tests/Earthfile
util/proj/golang.go
util/proj/golang_golden_test.go
util/proj/golang_test.go
util/proj/imports_test.go
util/proj/proj.go
util/proj/testdata/golang_base.out

This allows 'earthly init' to initialize a single-type project without the type-specific prefix. So no more '+go-build' in go-only projects, it's just '+build'.

util/proj: allow for an empty prefix

---

CHANGELOG.md
buildkitd/Earthfile
go.mod
go.sum

This tests, and implements https://github.com/earthly/buildkit/pull/20 as a partial performance resolution to #3085. Some of the higher resource utilization at the end exists (per user reports testing this fix), but the pauses appear to be gone.

Partial fix for Buildkit performance issues

---

Earthfile
ast/tests/with-docker.ast.json
buildkitd/docker-auto-install.sh
buildkitd/dockerd-wrapper.sh
examples/grpc/Earthfile
examples/integration-test/Earthfile
examples/react/Earthfile
examples/tutorial/go/part6/Earthfile
examples/tutorial/java/part6/Earthfile
examples/tutorial/js/part6/Earthfile
examples/tutorial/python/part6/Earthfile
release/Earthfile
scripts/tests/interactive-debugger/docker-compose/Earthfile
scripts/tests/interactive-debugger/docker-compose/docker-compose.yml
scripts/tests/interactive-debugger/docker-compose/test-docker-compose.py
tests/ssh.earth
tests/wait-block/save-image/Earthfile
tests/wait-block/with-docker-run-load/Earthfile
tests/with-docker-expose/Earthfile
tests/with-docker-registry/Earthfile
tests/with-docker-via-command/Earthfile
tests/with-docker/Earthfile

New dind image tags are:
earthly/dind:alpine-3.18 (which is also earthly/dind:alpine)
earthly/dind:ubuntu-20.04
earthly/dind:ubuntu-23.04 (which is also earthly/dind:ubuntu)

include dind base os version in tag

---

cloud/satellite.go
cmd/earthly/satellite_cmds.go
go.mod
go.sum

Allows users to specify a new platform in the satellite update command. Note that this is currently the only way to change a runner in Earthly CI to ARM.

Support changing platform in satellite update command

---

Earthfile
buildkitd/docker-auto-install.sh
docs/docker-images/dind.md

earthly/dind images will now include the docker version in the tag.
For example:
alpine-3.18-docker-23.0.6-r4
ubuntu-23.04-docker-24.0.5-1
Additionally we will tag images to include when they were produced.
For example:
alpine-3.18-docker-23.0.6-r4-20230808225455
ubuntu-23.04-docker-24.0.5-1-20230808225455

include docker version in dind tag

---

buildkitd/Earthfile
go.mod
go.sum

Updated buildkit will include additional
return leaving incoming open help me: %s
logs.

update buildkit to include extra scheduler logs

---

states/image/image.go

From the Go docs:
> "If the map is nil, the number of iterations is 0." https://go.dev/ref/spec#For_range
Therefore, an additional nil check for before the loop is unnecessary. Example: https://go.dev/play/p/Cw_wnqYzemu

states/image: remove redundant nil check

---

.github/workflows/reusable-secrets-integrations.yml
cmd/earthly/subcmd/account_cmds.go
cmd/earthly/subcmd/secret_cmds.go
scripts/tests/secrets-integration.sh
util/termutil/is_tty.go

When running `earthly secret set <path>`, rather than exiting with an error, we will prompt the user for a single-line secret value.
This allows a user to type in a single line followed by hitting the <enter> key.
Additionally, if `-stdin` is used from an interactive tty, earthly will now display a message saying it is waiting for an EOF (ctrl-d).
This additionally fixes a bug with isTTY, which was only checking stdout but could not detect if a command was being piped to stdin or not.

prompt for secret value when missing

---

util/containerutil/alias_test.go
util/containerutil/frontend_test.go

Switch to using require instead of assert to avoid continuing past an error and then panicing on a nil pointer dereference.

prevent frontend_test from panicing

---

earthfile2llb/converter.go
earthfile2llb/with_docker_run_base.go
earthfile2llb/with_docker_run_tar.go
logbus/formatter/formatter.go
logbus/solvermon/solvermon.go
util/vertexmeta/vertexmeta.go

It seems that buildkit now creates a lot of duplicate vertices when parts of a build are re-used. This PR deduplicates these by tracking via a CommandID that is set in the converter, instead of relying on buildkit's vertex digest.
Additionally, this PR removes all `context` output (unless verbose is enabled) as it is extremely noisy.

Fix redundant output

---

.github/workflows/update-docker-hub-readmes.yml

Limit the paths to only reference the docker hub markdowns, the `docs/**` did not discover the docker-image markdowns.

limit docker hub readme paths

---

scripts/tests/interactive-debugger/test-interactive.py

Display the name of the individual interactive debugger test in a box, to make it easier to differentiate the output of each test.

add interactive-debugger test headers

---

ast/commandflag/flags.go
earthfile2llb/converter.go
earthfile2llb/interpreter.go
earthfile2llb/with_docker_run_base.go
earthfile2llb/with_docker_run_local_reg.go
earthfile2llb/with_docker_run_local_tar.go
earthfile2llb/with_docker_run_reg.go
earthfile2llb/with_docker_run_tar.go
features/features.go
tests/Earthfile
tests/command-nested-global.earth
tests/pass-args-root.earth
tests/pass-args-sub-dir.earth

Introduces a new `--pass-args` flag to BUILD, FROM, COPY, WITH DOCKER, and DO commands, which allows users to propigate args between targets that exist outside of the scope of a single Earthfile.
This implements https://github.com/earthly/earthly/issues/1891

--pass-args flag

---

Earthfile
ast/tests/Earthfile

Now that earthly-v0.7.17 has been released with --pass-args, we can use it during bootstrapping our tests/builds.

use --pass-args in root Earthfile

---

buildkitd/Earthfile
go.mod
go.sum

Reverts earthly/earthly#3204
@vladaionescu was able to fix the root cause which was the slow consumption of messages from BK.

Revert "Update buildkit to c7693ebc3b039d047ed3def2d1bcda90de27876e"

---

cmd/earthly/app/run.go

Some errors weren't being reported correctly, leading to "No SetFatalError" warnings...
In addition, some cancellations had some hidden errors in them. These are now viewable in --verbose mode.

Logstream: Output errors in more cases

---

cmd/earthly/base/buildkit.go

Earthly will now warn:
TLS has been disabled; this should never be done when connecting to Earthly's production API
When attempting to connect to a satellite without TLS.

Display warning when TLS is disabled

---

tests/Earthfile

In paticular, `./tests+save-artifact-dont-overwrite` is failing under buildkite (but not locally), and it's not clear why.

use acbgrep to get a more clear error message

---

.buildkite/tests.sh
.github/actions/stage2-setup/action.yml

If the `earthly secret get ...` command substitution fails, propigate the failure to the calling script (since a `set -e` or `-o pipefail` doesn't catch this case)

exit if earthly secret get fails

---

scripts/tests/secrets-integration.sh
util/llbutil/secretprovider/secrets.go

When project-based secrets were introduced, the ErrNotFound type was changed, which prevented the secret lookup method from returning the correct error message which would contain **which** secret was not found.
Rather than displaying
RUN ./some-command failed: not found
We will now show:
RUN ./some-command failed: unable to lookup secret my_secret: not found

display name of secret that is not found

---

Earthfile
tests/Earthfile

The dockerhub mirror was not correctly setup when running earthly-in-earthly tests, due to the refactor in d875bf0883cb61b717f90e0fd613dbf84b7ef3c7

fix mirror setup in tests

---

.github/workflows/reusable-bootstrap-integrations.yml
.github/workflows/reusable-docker-build-integrations.yml
.github/workflows/reusable-earthly-image-tests.yml
.github/workflows/reusable-example.yml
.github/workflows/reusable-git-metadata-test.yml
.github/workflows/reusable-test-local.yml
.github/workflows/reusable-wait-block-override.yml

The satellite tests don't have a local instance of buildkit -- it's not possible to show logs.

dont display buildkit logs on sat tests

---

.github/actions/stage2-setup/action.yml
.github/workflows/ci-docker-satellites.yml
.github/workflows/reusable-bootstrap-integrations.yml
.github/workflows/reusable-docker-build-integrations.yml
.github/workflows/reusable-earthly-image-tests.yml
.github/workflows/reusable-example.yml
.github/workflows/reusable-export-test.yml
.github/workflows/reusable-git-metadata-test.yml
.github/workflows/reusable-misc-tests-1.yml
.github/workflows/reusable-misc-tests-2.yml
.github/workflows/reusable-push-integrations.yml
.github/workflows/reusable-race-test.yml
.github/workflows/reusable-repo-auth-tests.yml
.github/workflows/reusable-secrets-integrations.yml
.github/workflows/reusable-test-local.yml
.github/workflows/reusable-test.yml
.github/workflows/reusable-wait-block-override.yml

The earthly core-test satellite can get quite overloaded; randomly select 1 of 4 core-test-* instance to distribute load.
Also fixes some tests that were not correctly propagating through the `USE_SATELLITE` bool.

Distribute core-test load across shards

---

cmd/earthly/subcmd/account_cmds.go

The help string says the tokens will expire in one year by default, however, the earthly code (and corresponding cloud code) ssem to be deliberately using no expiry as the default. 
FWIW I think no-expiry as a default makes sense, as these tokens will often be used in CI for satellites. It may result in an unpleasant surprise a year later if the token expires and the user's CI fails.

Fix account create-token help string

---

.github/actions/stage2-setup/action.yml

Running `$(expr $RANDOM % 4)` returns an exit code of 1 when
0 is returned.
This was causing the random satellite shard selection to fail 25% of the
time.

tests: fix random satellite selection

---

buildkitd/dockerd-wrapper.sh

WSL does not support iptables-nft; for WITH DOCKER to work with kind; iptables must be switched to legacy.

WITH DOCKER should switch to iptable-legacy in WSL

---

Earthfile

This additionally explicitly sets `--platform=linux/amd64` for the amd64 targets, which is needed for m1 users to build the amd64 versions of earthly.

+for-linux-arm64 target for building arm64-linux

---

.github/workflows/reusable-earthly-image-tests.yml
scripts/tests/earthly-image-sat.sh
scripts/tests/earthly-image.sh

Move the satellite related tests from earthly-image.sh into a separate earthly-image-sat.sh test, to make it make it more clear which tests depend on satellites or not.

split up sat tests from earthly-image tests

---

.github/workflows/reusable-bootstrap-integrations.yml
.github/workflows/reusable-docker-build-integrations.yml
.github/workflows/reusable-earthly-image-tests.yml
.github/workflows/reusable-example.yml
.github/workflows/reusable-export-test.yml
.github/workflows/reusable-git-metadata-test.yml
.github/workflows/reusable-misc-tests-1.yml
.github/workflows/reusable-misc-tests-2.yml
.github/workflows/reusable-push-integrations.yml
.github/workflows/reusable-race-test.yml
.github/workflows/reusable-repo-auth-tests.yml
.github/workflows/reusable-secrets-integrations.yml
.github/workflows/reusable-test-local.yml
.github/workflows/reusable-test.yml
.github/workflows/reusable-wait-block-override.yml

Don't raise an error if docker logs earthly-buildkitd fails, as it can confuse users who are not familar with our tests and don't know to look at previous failures.

GHA: dont error during failure step

---

earthfile2llb/runmount.go
tests/Earthfile
tests/cache-mount-mode.earth

fixes #3278 
```
$ build/linux/amd64/earthly  +build
Init 🚀
buildkitd | Found buildkit daemon as docker container (earthly-dev-buildkitd)
Streaming logs to https://cloud.earthly.dev/builds/28574cd4-d086-4ca2-8132-31e0e7974b97
Build 🔧
ubuntu:22.10 | --> Load metadata ubuntu:22.10 linux/amd64
+build | --> FROM ubuntu:22.10
+build | [----------] 100% FROM ubuntu:22.10
+build | --> RUN stat -c '%A %n' /cache-folder
+build | d------rwx /cache-folder
output | --> exporting outputs
```

add mode support to mount cache

---

CHANGELOG.md
cmd/earthly/app/run.go

partially addresses #3200 
With this change we will ensure a non satellite build that fails due to missing qemu, will be display a message to tell the user what to do.
In case it's in a satellite, debug message will remind the user `--disable-emulation` flag is set in the satellite.

Print proper hint if qemu is missing

---

ast/commandflag/flags.go
docs/earthfile/earthfile.md
earthfile2llb/converter.go
earthfile2llb/interpreter.go
earthfile2llb/runmount.go
tests/Earthfile
tests/cache-mode.earth
tests/cache-mount-mode.earth

Right now, we cannot set the permissions for a `CACHE` directory. This PR fixes that.
_(Also, realized that we were using `0` as the default value for cache mount mode, so changing that to the `0644` standard in this same PR)_
I've noticed that we are using "mode" and "chmod" across different commands. I can take this opportunity to do some clean-up and unify into a single term. Personally I think "chmod" is more expressive. Thoughts?

Add CACHE mode support

---

CHANGELOG.md
Earthfile
release/changelogparser.py

New releases will require the CHANGELOG to mention if a the release contains any buildkit changes, by enforcing the existance of a new section:
- This release includes changes to buildkit
or
- This release has no changes to buildkit
depending on if the release includes changes to buildkit or not.

CHANGELOG linter: enforce buildkit change info

---

logbus/setup/setup.go

An empty `multierror.Error` value ought not to be added to the list.

Fixes issue with incorrect error count report

---

CHANGELOG.md
cmd/earthly/app/run.go
conslogging/conslogging.go
scripts/tests/earthly-image.sh

This pr partially addresses issue #3200 .
It suppresses some error messages from being displayed at the end of the execution
and allows to show them in verbose mode.

Move some error messages at end of execution to verbose mode

---

.github/workflows/ci-docker-satellites.yml
.github/workflows/ci-docker-ubuntu.yml
.github/workflows/ci-lint-docs.yml
.github/workflows/ci-podman-ubuntu.yml
.github/workflows/ci-scheduled-codeql-analysis.yml

A common case is when a new commit is pushed to the branch - 
With this added configuration any running jobs for the previous commit will be stopped and the jobs will start again for the newest commit (same as they do today).
Note, the configuration is added only in workflow files that are triggered by a pull request.
[docs reference](https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-concurrency-to-cancel-any-in-progress-job-or-run)

with this change, GH actions will only be able to run once for each branch/pr

---

CHANGELOG.md
cmd/debugger/main.go
debugger/terminal/terminal_other.go

Partially addresses #3200  (example 5)
- Avoid printing log errors that occur due to debugger exiting
- Make other log messages clearer that they are coming from the debugger, use console instead of Logger
Credit to @alexcb for solution.

interactive debugger ignore errors if command exits correctly

---

.github/workflows/ci-docker-ubuntu.yml
.github/workflows/ci-podman-ubuntu.yml
.github/workflows/reusable-find-pr-changes.yaml

Adding a new reusable job that will detect whether "essential" files were changed.
Then other jobs will run conditionally only is essentials files (e.g. *.go files) are changed as part of a PR.
Note that according to documentation, skipped jobs that are used as required checks in Github do not block PRs
(see note [here](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution#overview)).
Since all the tests are dependent on `build-earthly` job, it was sufficient to conditionally execute the latter.
If it is skipped, all dependent jobs will be skipped as well. 
I tested these changes on my fork of earthly

Conditionally run GH actions jobs only if relevant files changed

---

docs/earthfile/earthfile.md
docs/earthfile/features.md
earthfile2llb/converter.go
earthfile2llb/runmount.go
features/features.go
tests/shared-cache/Earthfile
tests/shared-cache/lib1/Earthfile

Adds `--global-cache` feature flag for https://github.com/earthly/earthly/pull/3296
Also changes names from "shared" to "global", since this first one is too overloaded in our documentation

Adds --global-cache feature flag

---

CHANGELOG.md
buildkitd/docker-auto-install.sh

This is to prevent cases where gpg may attempt to use a tty, which will result in an error during the docker auto-install script.

docker-auto-install use the gpg --no-tty option

---

cmd/earthly/subcmd/build_cmd.go
logbus/ship/ship.go

It appears that `Write` is being called after `Close` in very rare cases. I noticed this once last night but lost the CI URL. IN any case, it seems reasonable to discard log messages after `Close` is called.

Logstream: Fix panic when logs are written after Close called

---

Earthfile
release/Earthfile

The changelog-parser was changed in
7e7bd7c92be740354b1bb4b266f8c44d477351e4 to make use of the packaging library; however it was only ever installed in the base linter, and not the ./release+release-notes target, which caused that target to break.
This refactors the targets to use the same common base (which includes the packaging library).

changelog-parser: use a common base

---

Earthfile
buildkitd/Earthfile
cmd/earthly/subcmd/build_cmd.go
go.mod
go.sum
regproxy/proxy.go

Removes the HTTP-level code in favor of a lower-level TCP proxy approach. 
The tricky part here was that Docker (and most HTTP clients) leaves the TCP connection open. Hence, there's no way for the code to detect when to stop reading the initial request aside from a timeout. Apparently, the recommended approach is to set [`SetReadDeadline`](https://cs.opensource.google/go/go/+/refs/tags/go1.21.1:src/net/net.go;l=156) ahead of each read and appropriately handle any timeout errors. 
Overall, I think this is preferable to the original code as the HTTP code & header parsing is a bit brittle.
Works with: https://github.com/earthly/buildkit/pull/26

Registry proxy: Use lower-level TCP streaming

---

.github/workflows/README.md
.github/workflows/build-earthly.yml
.github/workflows/ci-docker-satellites.yml
.github/workflows/ci-docker-ubuntu.yml
.github/workflows/ci-podman-ubuntu.yml
.github/workflows/ci-staging-deploy.yml
.github/workflows/reusable-bootstrap-integrations.yml
.github/workflows/reusable-docker-build-integrations.yml
.github/workflows/reusable-earthly-image-tests.yml
.github/workflows/reusable-example.yml
.github/workflows/reusable-export-test.yml
.github/workflows/reusable-git-metadata-test.yml
.github/workflows/reusable-misc-tests-1.yml
.github/workflows/reusable-misc-tests-2.yml
.github/workflows/reusable-push-integrations.yml
.github/workflows/reusable-race-test.yml
.github/workflows/reusable-repo-auth-tests.yml
.github/workflows/reusable-secrets-integrations.yml
.github/workflows/reusable-test-local.yml
.github/workflows/reusable-test.yml
.github/workflows/reusable-wait-block-override.yml
examples/tutorial/python/part3/requirements.txt
examples/tutorial/python/part4/requirements.txt
examples/tutorial/python/part5/services/service-one/requirements.txt
examples/tutorial/python/part6/requirements.txt

The current configuration might causes jobs that are marked as required checks to get stuck in pending.
This PR aims to fix it.
See the readme added in this PR for more information.
Also fixing:
* workflows not running properly on push to main
* python tutorial tests

Change how PRs are skipped so that required checks won't get stuck in pending

---

builder/builder.go
buildkitd/Earthfile
cmd/earthly/subcmd/build_cmd.go
go.mod
go.sum

This PR moves the registry proxy start-up code into `Builder` and gates the feature using the new cap added here: https://github.com/earthly/buildkit/pull/27

Implement registry capabilities check

---

.github/workflows/ci-staging-deploy.yml

The CHANGELOG linter was changed to enforce each release contains a new "Additional Info" section in 7e7bd7c92be740354b1bb4b266f8c44d477351e4; however, the ci-staging-deploy script was never changed to emit the newly required text.
In this case we will always append a "This release includes changes to buildkit" message, even if there isn't actually a change.

staging-release: add Additional Info to CHANGELOG

---

.github/renovate.json5
.github/workflows/docs-checks-links.yml
Earthfile
docs/earthfile/earthlyignore.md
release/README.md

- Clarify/Update release/README.md
- Update Renovate to update referenced earthly version in release/README.md
- Add GH workflow to find broken links
- Enable Renovate for Github actions (Renovate will start updating dependencies of referenced gh actions, e.g. 
`uses: actions/checkout@v3` => `uses: actions/checkout@v4`

Address v0.7.20 release process retro

---

docs-internals/README.md
docs-internals/build-steps.md

This is a rough starting-point for developers who want to learn more about the internals of the earthly codebase.

developer-docs of the earthly codebase

---

.github/workflows/ci-docker-satellites.yml
.github/workflows/ci-docker-ubuntu.yml
.github/workflows/ci-podman-ubuntu.yml
Earthfile

Existing `examples2` target seems to be using all available GHA runner disk.

Split examples target for disk use issue

---

CHANGELOG.md
cmd/earthly/subcmd/bootstrap_cmds.go
earthly-entrypoint.sh

The earthly/earthly image entrypoint script performs a bootstrap in order to generate self-signed TLS certificates (which is good), but continues to attempt to start a buildkit instance (which is bad), since the script continues to run buildkitd directly in the same container.
This leads to confusing warning messages such as
buildkitd | Starting buildkit daemon as a docker container (earthly-buildkitd)...
bootstrap | Warning: Bootstrapping buildkit failed: maybe start buildkitd: start: could not start buildkit: 1 error occurred:
bootstrap | 	* command failed: docker run --privileged --env BUILDKIT_DEBUG=false --env BUILDKIT_TCP_TRANSPORT_ENABLED=true --env BUILDKIT_TLS_ENABLED=true --env BUILDKIT_MAX_PARALLELISM=20 --label dev.earthly.settingshash=53bb7043424f0e87 --mount …

bootstrap: --force-certification-generation

---

CHANGELOG.md
buildkitd/Earthfile
go.mod
go.sum

cherry-picked 100d3cb6b6903be50f7a3e5dba193515aa9530fa from https://github.com/moby/buildkit/pull/4285
fixes https://github.com/earthly/earthly/issues/2957

update buildkit with double-merged-edge fix

---

.github/workflows/reusable-wait-block-target.yml

the wait-block-target test used to run all of +test, but was split up in 02a2749b8b1d35ce893c54c34dbffc2e79fb6110 however the test name was never updated.

fix wait/end test name to include TARGET_NAME

---

examples/go-monorepo/services/one/main_test.go
examples/go-monorepo/services/two/main_test.go

io/ioutil has been deprecated in favor of 'io' and 'os' which are drop-in replacements for io/ioutil.
In this case, we are replacing ioutil's ReadAll with io's ReadAll.
Happy Hacktoberfest :) Thank you for considering my PR!

Patch: Eliminates deprecated ioutil

---

docs-internals/README.md
docs-internals/buildkit-fork.md

A rough list of our features in our buildkit fork, which are not appropriate for upstream submissions.

internal-docs: list buildkit-fork features

---

.github/workflows/reusable-earthly-image-tests.yml
.github/workflows/update-docker-hub-readmes.yml

The earthly automation dockerhub user has changed and now requires us to
use a seperate token rather than password for accessing the API.

dockerhub readme: use token instead of password

---

.github/workflows/release-merge-docs.yml
Earthfile
docs/ci-integration/pull-through-cache.md
release/README.md

* Get workflow to merge main to docs-0.7 out of dry run mode
* Update release/README to use badges of relevant workflows - the above mentioned worklow & find broken links
* Fix broken link in docs (the docker registry configuration page has moved)

Update to release process & docs

---

docs/earthfile/earthfile.md

Warn users that as of v0.7.21; buildkit no longer stores the credentials in the git/config file.

docs: warn git credentials are no longer stored

---

cloud/auth.go

Fixes a call to SignWithFlags which requested sha512 be used for all callenge signing requests; however this flag is only used by ssh-rsa keys.
Some ssh agents, like OpenSSH, will simply ignore this flag when a different key type is used; however other agents, like 1password's ssh agent, will raise an error if this flag is set.
Fixes #3366

fix: non-rsa public-key auth challeng signing

---

Earthfile
builder/builder.go
buildkitd/Earthfile
cmd/earthly/subcmd/build_cmd.go
config/config.go
go.mod
go.sum
regproxy/controller.go
regproxy/proxy.go
util/containerutil/frontend.go
util/containerutil/shell_shared.go
util/containerutil/stub.go
util/containerutil/types.go

Enables image registry proxy support for Mac via a side-car `socat` container. On Mac, `docker pull` (and friends) will make requests to `localhost`. These requests will be answered by the `socat` container and proxied through to the registry proxy server spawned by the CLI. That server then sends the request to BK (remote or local) via the gRPC tunnel. 
Depends on: https://github.com/earthly/buildkit/pull/30
https://github.com/earthly/earthly/issues/3412

Registry proxy: support container for Mac

---

docs/docker-images/dind.md

Fix the docs to mention that the legacy unversioned tags only broke earthly v0.7.14, and were fixed again in v0.7.15.

dind docs: older versions work again

---

tests/config/Earthfile

The final stage of the config-test is to check for an error case (via grep), this causes the last line to be output as:
./tests/config+test | --> RUN cat output.txt | grep 'Error: read config: failed to read from /home/testuser/.earthly/config.yml: open /home/testuser/.earthly/config.yml: permission denied'
./tests/config+test | Error: read config: failed to read from /home/testuser/.earthly/config.yml: open /home/testuser/.earthly/config.yml: permission denied
which is not obvious at a quick glance.
Now we will print a final "config test passed" line.

make it obvious when the confit test passes

---

docs/SUMMARY.md
docs/alt-installation/alt-installation.md
docs/install/install.md

A new user reported that it wasn't clear how to install Earthly after going through the docs. They ended up Googling for a Docker image and used that instead, which was less than ideal.
Our docs TOC did not have a link to install Earthly. Added that now.

Make it clearer to the docs readers how to install Earthly

---

ast/commandflag/flags.go
earthfile2llb/interpreter.go
inputgraph/loader.go
tests/autoskip/Earthfile
tests/autoskip/for.earth

This PR adds support for `FOR...IN` variable expansion (example below). Shell-out is not yet supported.  
```
test-vars:
ARG vals = \
foo \
bar \
baz \
bim
FOR idx IN $vals
RUN echo "hello $idx"
END
```

Support FOR..IN variable expansion

---

CHANGELOG.md
logbus/formatter/formatter.go
logbus/solvermon/vertexmon.go

Closed #3356 
Also fixing cases where `Error:` prefix is added to the message even though the message already starts with `ERROR` or `WARN`.
Earthfile:
```Earthfile
local:
LOCALLY
RUN false
```
Before:
```
/U/i/Documents+local | darwin/arm64
/U/i/Documents+local | --> RUN false
/U/i/Documents+local | WARN /Users/idodavid/Documents/Earthfile line 9:4: The command 'RUN false' failed: error calling LocalhostExec: exit code: 1
View logs at https://cloud.earthly.dev/builds/5ba6eca1-111e-4597-9c90-b7aeaba78488
Error: /Users/idodavid/Documents/Earthfile line 9:4 apply RUN: unlazy force execution: error calling LocalhostExec: exit code: 1
in              /Users/idodavid/Documents+local
```
After:
```
/U/i/Documents+local *failed* | Repeating the failure error...
/U/i/Documents+local *failed* | …
```

make error message for  `RUN` under  `LOCALLY` the same as `RUN` without `LOCALLY`

---

earthfile2llb/converter.go
earthfile2llb/runmount.go

We've been getting a ton of feedback lately that cache mounts are difficult to work with. A source of confusion is that the cache key by default is a digest of target + args. Everyone expects this to be just target.
This PR fixes the issue.

Cache key is not intuitive

---

CHANGELOG.md
cmd/earthly/app/run.go
cmd/earthly/base/cli.go
cmd/earthly/subcmd/build_cmd.go
cmd/earthly/subcmd/cli.go
conslogging/color.go
conslogging/conslogging.go

Also printing help messages after build errors in color, adding `Help: ` as a prefix to these messages.

Move logstream link to be printed after build errors

---

cmd/earthly/subcmd/build_cmd.go
inputgraph/hash.go
inputgraph/loader.go
tests/autoskip/Earthfile
tests/autoskip/simple.earth
tests/autoskip/subdir/test.earth

Includes the following auto-skip changes:
* Fail with messages when `--no-cache` and `--push` are passed to the CLI with `--auto-skip`
* ~Abort when `--no-cache` is used in a visited `RUN` command~
* Don't add log-sharing link when build is skipped
* Added back prefix for some auto-skip messages (only when build continues)

Auto-skip: handle --no-cache & --push on command line

---

CHANGELOG.md
cmd/earthly/app/run.go
cmd/earthly/base/buildkit.go
cmd/earthly/subcmd/build_cmd.go
cmd/earthly/subcmd/cli.go
cmd/earthly/subcmd/common.go
cmd/earthly/subcmd/registry_cmds.go

When using the selected org instead of explicitly setting the org in the command (or via an env var),
the org was not properly sent to analytics server.
This PR adds a new function that reads the org name from the command flag and falls back to the selected org if the former is not set.
In addition this also changes the `earthly registry` command to fall back to the selected org which it did not do before.

make sure selected org is used in all applicable commands when org is not explicitly set

---

inputgraph/loader.go
tests/autoskip/Earthfile
tests/autoskip/shell-out.earth

Allows targets that use shell-out features to be auto-skipped unless the target name is to be dynamically resolved using the result of a shell-out command.

Auto-skip: further support for shell-out

---

CHANGELOG.md
buildkitd/Earthfile
buildkitd/runc-ps
cmd/earthly/app/before.go
cmd/earthly/flag/global.go
earthfile2llb/converter.go
earthfile2llb/earthfile2llb.go
go.mod
go.sum
logbus/command.go
logbus/formatter/formatter.go
logbus/setup/setup.go
logbus/solvermon/solvermon.go
logbus/solvermon/vertexmon.go
scripts/tests/interactive-debugger/test-interactive.py
tests/Earthfile
tests/stats.earth
util/statsstreamparser/parser.go

Introduces a new `--exec--stats` flag that displays cpu and memory usage per
target.

Display per-target CPU and memory stats

---

inputgraph/loader.go
tests/autoskip/Earthfile
tests/autoskip/simple.earth

This PR adds auto-skip support for `COPY --if-exists` & fixes a bug with `FOR...IN` incorrectly including the index var & `IN`.

Auto-skip: support for COPY --if-exists & FOR IN fix

---

ast/commandflag/flags.go

A friendly reminder, stemming from the discussion in https://github.com/earthly/earthly/pull/3510#issuecomment-1819561503

code-comment reminder for feature flags

---

examples/rust/Earthfile

Rust example uses our UDC instead of cargo chef

Examples: Using CARGO UDC in rust example

---

inputgraph/loader.go
inputgraph/loader_hashing.go
tests/autoskip/Earthfile
tests/autoskip/remote-target.earth

Adds `BUILD`, `COPY`, `FROM` support for remote targets that use explicit SHAs or tags.

Auto-skip: support for some remote targets

---

inputgraph/hash_test.go

These tests are failing in `main`. I merged a PR that was partially failing due to the ECR auth issue.

Auto-skip: fix & remove hard-coded test hash

---

inputgraph/hash_test.go
inputgraph/loader.go
inputgraph/testdata/with-docker/Earthfile
tests/autoskip/Dockerfile
tests/autoskip/Earthfile
tests/autoskip/from-dockerfile.earth

Auto-skip support for targets that contain:
```
FROM DOCKERFILE -f /dist/Dockerfile /dist
````
```
FROM DOCKERFILE github.com/earthly/test-remote/from-dockerfile:40080b4fc1fd4881f5123f03ba030055efbbbafe+create-dockerfile/
```
```
FROM DOCKERFILE +create-dockerfile/
```
```
WITH DOCKER --load foo=github.com/earthly/earthly:6610b73131f94cbe594dba3b90665748f21a9b8d+license
```

Auto-skip: support FROM DOCKERFILE & remotes for WITH DOCKER --load

---

cmd/earthly/subcmd/build_cmd.go
tests/autoskip/Earthfile

This PR tweaks the behavior of auto-skip failures such that hashing problems will force the CLI to exit. 
Before:
```
$ ./build/linux/amd64/earthly --auto-skip +code      
Init 🚀
auto-skip | unable to calculate hash for +code: circular dependency detected; +code already called
buildkitd | Found buildkit daemon as docker container (earthly-dev-buildkitd)
Streaming logs to https://cloud.earthly.dev/builds/a3d9a6de-08fc-4967-a103-db3e13440bf4
Build 🔧
golang:1.21-alpine3.17 | --> Load metadata golang:1.21-alpine3.17 linux/amd64
...
```
After:
```
$ ./build/linux/amd64/earthly --auto-skip +code
Init 🚀 …
```

Auto-skip: exit on hashing failure

---

cmd/earthly/subcmd/build_cmd.go
outmon/solvermon.go

prevent --exec-stats data from getting dumped to stdout when legacy non-logbus code is used.

--exec-stats requires logbus

---

cmd/earthly/subcmd/build_cmd.go
inputgraph/hash.go
inputgraph/loader.go
tests/autoskip/Earthfile
tests/do-not-track/Earthfile
util/shell/lex.go
util/shell/lex_test.go

Fixes 2 issues that were blocking auto-skip on `+test` & `+for-linux`. 
* Problems parsing args with complex quoting/parens
* Arg expansion for ${$VAL#foo}. Example: https://github.com/earthly/earthly/blob/main/Earthfile#L366
The above targets now work!

Auto-skip: fixes arg parsing issues

---

CHANGELOG.md
ast/antlrhandler/error_listener.go
ast/ast.go
ast/hint/error.go
buildkitd/buildkitd.go
buildkitd/certificates.go
cmd/earthly/app/run.go
cmd/earthly/common/shared.go
cmd/earthly/subcmd/doc_cmds.go
cmd/earthly/subcmd/init_cmds.go
earthfile2llb/interpreter.go
logbus/solvermon/vertexmon.go
scripts/tests/secrets-integration.sh
tests/Earthfile
util/hint/hinterror.go
util/hint/hinterror_test.go
util/llbutil/secretprovider/secrets.go
util/proj/golang.go
variables/collection.go

In a recent previous PR the existing hint.Error was refactored in order to allow for hints to be displayed at the end of a failed execution in a more consistent way compared to other help messages.
In this PR that change was slightly reverted so that it would be easier to remove the deprecated hint.Error
(`WrapWithDisplay` is reverted back to `Wrap`)
So instead, this PR introduced a new hint.Error, which if used, will show the hint at the end of an execution like other help messages. In addition the mechanism was improved such that even hints going through gRPC will be properly identified.
Finally, this new hint error is used in cases where a cloud secret could not be found.

Introduce a new hint error to display at the end of a failed execution

---

cmd/earthly/subcmd/build_flags.go

I noticed that in some cases using `Value` field instead of `Destination` can cause a bug in how `urfave/cli` parses the flags and arguments.
According to [documentation](https://cli.urfave.org/v2/examples/flags/#placeholder-values) `Destination` is the correct field to use.

Use the correct field to assign the value of a slice flag

---

.github/workflows/docs-checks-links.yml
Earthfile
docs/caching/caching-in-earthfiles.md
docs/caching/caching-via-registry.md
docs/caching/caching.md

This PR fix some broken links and adds a new job
that will be triggered on a PR to docs-0.7.
This job will find the temporary link generated by Gitbook, and look for broken links.
This way we can find broken links before merging the PR

add new gh job to check for broken links on PRs to docs-0.7

---

CHANGELOG.md
conslogging/color.go

Example of new color:
https://cloud.earthly.dev/builds/d98fbdeb-6747-41e1-8c5f-cb7ecaabb766

Change color used to print metadata values (such as ARG values)

---

.github/renovate.json5
.github/workflows/docs-checks-links.yml
.github/workflows/release-merge-docs.yml
release/README.md

Also:
1. Point Renovate PR which updates the earthly version in our docs to target `docs-0.7` branch
2. Add the Github workflow that was previously added to the docs-0.7 (to avoid future potential merge conflicts)

Clarify release readme that refers to badges

---

features/features.go

Move the `no-use-registry-for-with-docker` and `earthly-ci-runner-arg` features to a seperate section for features that will never be enabled by default; where as the other unreleased features are likely to be promoted to enabled for `VERSION 0.8`.

seperate potential VERSION 0.8 features

---

analytics/analytics.go

Add detection for:
* Zuul
* Semaphore
* Azure DevOps Pipelines
* Bitbucket Pipelines
Also, add another catch-all heuristic for git detached head state (typically used in CI).

Better CI detection

---

scripts/tests/interactive-debugger/test-interactive.py

Raise an error if the specified `--test` value doesn't match any tests.

interactive-debugger test: validate test name

---

ast/validator.go
tests/version/Earthfile

Fixes an error which stated `VERSION 0.0` is valid (when in fact it's only ever used in tests)

don't display 0.0 as supported VERSION

---

CHANGELOG.md
cmd/earthly/app/run.go

If a build fails as a result of RUN failing with an exit code != 0, earthly will print a help message to use the interactive flag.
Example:
Note: this will only be printed if the interactive flag is not already in use.

Show a hint to use interactive flag on relevant build failures

---

CHANGELOG.md
builder/builder.go
earthfile2llb/earthfile2llb.go
earthfile2llb/interpreter.go

The previous version was too noisy.
This changes it to show 3 times max and only once per file.

Limit the number of warnings shown when using COMMAND keyword

---

cloud/askv.go

`PipelineName` is not in use and will be removed as an option for auto-skip pruning.

Askv: remove pipeline

---

.github/workflows/update-docker-hub-readmes.yml

We get a new renovate PR for each commit to the project, so moving to use an official release to make Renovate less noisy (and rely on official releases instead)

updatedockerhub readme job - use semver instead of sha for dependency

---

buildkitd/Earthfile
go.mod
go.sum

buildkit will now display a list of previously used edges in the actives map when an inconsistent graph state error occurs.

track data for inconsistent graph state errors

---

tests/autoskip/remote-target.earth

`+license` was heavier than expected.

Auto-skip: use lightweight target for tests

---

cmd/earthly/subcmd/build_cmd.go
tests/autoskip/Earthfile

This PR removes the check against using `--push` with auto-skip.

Auto-skip: reinstate --push support

---

cmd/earthly/app/run.go
go.mod
go.sum
inputgraph/error.go
inputgraph/loader.go
tests/Earthfile

Prepends file location & line numbers to auto-skip error messages.
```
Error: tests/Earthfile line 1647:4: auto-skip is unable to calculate hash for ./tests+bad-remote: only remote targets referenced by a complete Git SHA or an explicit tag referenced as 'tags/...' are supported
```

Auto-skip: include source file & line for all error message

---

tests/private-https/Earthfile
tests/private-https/git-clone-private-https-nestedrepo.earth

This test shows a bug that exists when trying to perform a GIT CLONE of a repo that doesn't follow the two directory user/repo git URL.

tests for https-based non-standard repo URL

---

cmd/earthly/app/run.go
cmd/earthly/main.go
logbus/ship/ship.go
util/syncutil/signal.go

Control-C was leading to a hung process. The log streaming context was being canceled which led to a deadlock with writing new messages.

Fix hanging when process killed by user

---

Earthfile
release/Earthfile

Addresses https://github.com/earthly/earthly/issues/2142
There's a new `BIN_VERSION` arg which can be manually set to differentiate between the binary version & the container image tag. It will fall back to the container image tag if it's not provided. 
Example:
```
$ earthly ./release+release-dockerhub --PUSH_LATEST_TAG=true --RELEASE_TAG="v8.8.8"
...
...
Push Summary ⏫ (disabled)
To enable pushing use earthly --push
Did not push image docker.io/earthly/buildkitd:v8.8.8
Did not push image docker.io/earthly/buildkitd:v8.8.8
Did not push image docker.io/earthly/buildkitd:v8.8.8
Did not push image docker.io/earthly/buildkitd:v8.8.8
Did not push image docker.io/earthly/buildkitd:latest
Did not push image …
```

Ensure "latest" DockerHub image is identical to version-tagged image

---

util/llbutil/authprovider/imports_test.go
util/llbutil/authprovider/podman_test.go

The test was checking for the chan to be closed before waiting on the goroutine in `BeforeEach` to close the chan.
Before:
```bash
go test -count 2000 -run TestPodmanProvider 
--- FAIL: TestPodmanProvider (0.00s)
--- FAIL: TestPodmanProvider/it_falls_back_to_XDG_RUNTIME_DIR/containers/auth.json (0.00s)
podman_test.go:63: channel open
podman_test.go:63
--- FAIL: TestPodmanProvider (0.00s)
--- FAIL: TestPodmanProvider/it_prefers_REGISTRY_AUTH_FILE (0.00s)
podman_test.go:63: channel open
podman_test.go:63
--- FAIL: TestPodmanProvider (0.00s)
--- FAIL: TestPodmanProvider/it_prefers_REGISTRY_AUTH_FILE (0.00s)
podman_test.go:63: channel open
podman_test.go:63
--- FAIL: TestPodmanProvider (0.00s)
--- FAIL: TestPodmanProvider/it_falls_back_to_XDG_RUNTIME_DIR/containers/auth.json (0.00s) …
```

Fix flaky Podman test

---

tests/with-docker-kind/Earthfile

Declaring an ARG that's meant to depend on a global doesn't seem to be supported. Perhaps this should be supported by Earthly, but for now, here's a fix for the CircleCI test.

Remove second var declaration in +smoke-test

---

inputgraph/loader.go
tests/autoskip/Earthfile
tests/autoskip/expand-args.earth
variables/collection.go

This fixes an issue with stripping quotes when expanding arguments.
The new code retains quotes and ensures the argument values are maintained after expansion.
Previous:
```
Original: COPY (+my-target --my-arg="hello world" --other="$FOO")
Expanded: COPY (+my-target --my-arg=hello world --other=value)
```
Note that the above `--my-arg` value will lead to an invalid argument error.
New:
```
Original: COPY (+my-target --my-arg="hello world" --other="$FOO")
Expanded: COPY (+my-target --my-arg="hello world" --other="value")
```

Auto-skip: retain quotes when expanding args

---

go.mod
go.sum
util/llbutil/authprovider/cloudauth/authprovider.go

I see the below error from time to time but I assumed that we had retries in place for these requests. That's not the case, so I've added a drop-in retryable client that should cover these requests. I've extended the base retry policy to support `io.EOF`. 
```
failed to login to registry-1.docker.io with username griswoldthecat (using credentials from /earthly-technologies/cloud/std/registry/registry-1.docker.io/): Post "https://auth.docker.io/token": EOF
```
https://github.com/earthly/cloud/actions/runs/7303264176/job/19903432258

Retry auth provider token fetch requests

---

util/llbutil/authprovider/cloudauth/authprovider.go
util/llbutil/authprovider/cloudauth/authprovider_test.go

Adds a few more tests for the retry behavior introduced in https://github.com/earthly/earthly/pull/3649

More tests for retryable HTTP client used in auth provider

---

.github/renovate.json5

This would update the alpine/git version in the git-clone.ast.json file so that tests will pass, unlike in this PR which was opened by Renovate - https://github.com/earthly/earthly/pull/3654

Renovate config - Fix regex for alpine/git updates

---

tests/local/with-docker-compose-local-reg/docker-compose.yml
tests/local/with-docker-compose-local/docker-compose.yml

This adds an extra readiness check at the Compose level for a flaky test. Interestingly, the `curl` retry options (below) don't appear to support `CURLE_COULDNT_CONNECT` (i.e., "Couldn't connect to server") so an extra, external check is likely required here. 
```
curl --connect-timeout 1 \
--max-time 1 \
--retry 5 \
--retry-delay 0 \
--retry-max-time 10 \
"http://${WEBHOST}:${WEBPORT}"
```

Add extra Compose healthcheck for WITH DOCKER test

---

ast/tests/copy.ast.json
earthfile2llb/interpreter.go
tests/Earthfile
tests/copy.earth
util/llbutil/copyop.go

Addresses https://github.com/earthly/earthly/issues/3147
This PR adds a check against empty COPY source arguments. This fixes the above `--if-exists` panic and validates all other sources that expand to empty strings. Another option would be to fail during arg expansion if the arg doesn't exist.

Guard against empty COPY sources

---

cloud/client.go
cmd/earthly/subcmd/account_cmds.go
tests/account/test-login.sh

Addresses #3284
This change allows for the Cloud client's auth token to be set when using the below command to log in. Previously, the command was performing SSH-based auth despite the `--token` parameter.
```
earthly account login --token <token>
```
Setting the `--token` parameter will also ignore any cached JWT. This seems more intuitive as the token is explicitly provided.

Prefer auth token to SSH login when provided

---

cmd/earthly/subcmd/common.go
cmd/earthly/subcmd/common_test.go
cmd/earthly/subcmd/registry_cmds.go
cmd/earthly/subcmd/secret_cmds.go

Addresses https://github.com/earthly/earthly/issues/3158
This change ensures the following user secret listing styles all behave as expected:
```bash
$ EARTHLY_ORG="" EARTHLY_PROJECT="" earthly secrets ls /user
$ EARTHLY_ORG="my-org" EARTHLY_PROJECT="my-project" earthly secrets ls /user
$ EARTHLY_ORG="my-org" EARTHLY_PROJECT="" earthly secrets ls /user
$ EARTHLY_ORG="my-personal-org" EARTHLY_PROJECT="" earthly secrets ls
```
However, because of how user secret names are stripped of the `/user/` prefix on display, users may be confused by the following scenario:
```bash
$ EARTHLY_ORG="my-org" EARTHLY_PROJECT="my-project" earthly secrets ls /user
/my/secret
$ EARTHLY_ORG="my-org" EARTHLY_PROJECT="my-project" earthly secrets set /my/secret foo
```
We can either leave this as is or disallow …

Improve user secret ls ergonomics

---

scripts/tests/earthly-image-sat.sh

The `earthly-image-sat.sh` test has been failing periodically due to hitting unexpected states. This change will handle all states appropriately & wait for the satellite to become available.

Ensure satellite is ready before running test

---

tests/remote-cache/Earthfile

check the exit code of earthly in the remote-cache test.
additionally use acbtest (which will print out values if it fails)

remote-cache test: check exit code

---

tests/Earthfile

Add some missing --pass-args to builds to propagate the registry mirror
settings to +earthly-integration-test-base

tests: use --pass-args to configure mirror

---

Earthfile
ast/spec/earthfile.go
buildcontext/detectbuildfile.go
buildcontext/git.go
buildcontext/resolver.go
earthfile2llb/converter.go
earthfile2llb/interpreter.go
features/features.go
tests/Earthfile
tests/wildcard-build.earth
tests/wildcard-build/bar/Earthfile
tests/wildcard-build/baz/Earthfile
tests/wildcard-build/foo/Earthfile
tests/wildcard-build/no-target/Earthfile
util/fileutil/fileutil.go
util/fileutil/fileutil_test.go
wildcard-build/bar/Earthfile
wildcard-build/baz/Earthfile
wildcard-build/foo/Earthfile

This PR is my first pass on wildcard BUILD expansion. That is, builds in the form of `BUILD ./*+target`. This code will attempt to expand the BUILD into multiple commands if both the Earthfile & the target exist. The code will only explore directories 1 level beneath the referenced directory and globstar (`**`) is not yet supported.
Example: 
```
$ tree tests/wildcard-build 
tests/wildcard-build
├── bar
│   └── Earthfile
├── baz
│   └── Earthfile
├── foo
│   └── Earthfile
├── no-earthfile
└── no-target
└── Earthfile
```
```
VERSION 0.7
test:
FROM alpine
BUILD ./wildcard-build/*+test
```
https://cloud.earthly.dev/builds/ec88fff1-d353-4045-a345-e3ce10cadff0

Wildcard BUILDs

---

cloud/logstream.go
cloud/logstream_test.go

This change fixes a stream resumption issue where a delta may be dropped if the resume attempt immediately fails.  On L150, the code attempts to send the resume delta and any delta that previously failed to send. The `last` variable was not updated in the earlier code, so the `last` delta would not be properly passed to the subsequent retry. The new code ensures `last` is always set appropriately.

Logstream: ensure no deltas are dropped on failed resume

---

earthfile2llb/converter.go
earthfile2llb/earthfile2llb.go
go.mod
go.sum
logbus/target.go
util/deltautil/apply.go
util/deltautil/go.mod
util/deltautil/go.sum

This is rather simple but it seems to work. Perhaps I'm missing something. 
Example debug output:
```
Parent target 523272c3-de17-45db-af41-372af13e1b0b +for-linux
Parent target dd0122f0-fcb3-4901-b512-f9fe4a470ccf ./ast/parser+parser
Parent target 523272c3-de17-45db-af41-372af13e1b0b +for-linux
Parent target 901cf3be-0061-49f3-99e6-1c98d9ed72af ./buildkitd+buildkitd
```

Add Logbus/Logstream target link to allow for association

---

inputgraph/loader.go
tests/autoskip/Earthfile
tests/autoskip/expand-args.earth

Addresses: https://github.com/earthly/earthly/issues/3694
It looks like support for the case below may have been dropped during a refactor. Fixed and added some tests. 
```
copy-target-dynamic:
ARG name="+copy-target"
COPY ($name/x --foo=goodbye) .
RUN cat x
```

Auto-skip: expand dynamic COPY target names

---

cloud/logstream_test.go

Probably best to use a recoverable error for the resumption tests! This was failing a few times per 100 runs.

Logstream: use recoverable error in test

---

cmd/earthly/subcmd/satellite_cmds.go

The inspect command was not resolving the address or setting up TLS for self-hosted satellites.

Fix inspect command for self-hosted satellites

---

.github/workflows/ci-docker-ubuntu.yml
.github/workflows/ci-podman-ubuntu.yml
tests/Earthfile

split up the the
`tests-that-require-earthly-technologies-account-access` target into the 4 seperate targets it builds.

split up tests-that-require-earthly-technologies-account-access

---

cmd/earthly/subcmd/build_cmd.go
inputgraph/hash.go
inputgraph/hash_test.go
inputgraph/loader.go
inputgraph/testdata/target-cache/Earthfile

Addresses: https://github.com/earthly/earthly/issues/3691
This PR adds code to cache already hashed targets for auto-skip hash calculation. A cache key is created using the canonical target value & all supplied arguments. The computed hash value is stored as the map value. If another target then refers to a cached target, the pre-computed hash value will be used instead of wastefully revisiting the same target. This approach makes some auto-skip checks upwards of 10 times faster as some project graphs balloon in complexity (execution-wise) when many targets import several complex sub-targets. 
I looked into using `synccache.SyncCache` for this, but it didn't seem to expose whether the cache was used or not (see stats values below). Plus this code is not yet used concurrently so using a …

Auto-skip: cache target hash results for reuse

---

tests/Earthfile
tests/functions-do-not-propagate-args/Earthfile
tests/functions-do-not-propagate-args/propagate.earth

Unlike targets, calling a function does not cause args to be automatically propagated.

test that functions do not propagate args

---

ast/tests/if-exists.ast.json
earthfile2llb/converter.go
tests/Earthfile
tests/if-exists.earth
util/llbutil/copyop.go

Addresses: https://github.com/earthly/earthly/issues/1679
A previously added special case for `SAVE ARTIFACT --if-exists` was interfering with wildcard expansion. When the path includes a wildcard, there's no need to use the globbing pattern (e.g., `[g]o.mod` to optionally match `go.mod`) to make the match optional.

Fix SAVE ARTIFACT --if-exists wildcard bug

---

tests/do-not-track/Earthfile
tests/do-not-track/api-earthly-stub-server-shutdown.py
tests/do-not-track/api-earthly-stub-server.py
tests/do-not-track/test-earthly-script.sh

If the do-not-track test fails, display the api.earthly.dev stub server logs.

do-not-track test: display stub server logs

---

docs/SUMMARY.md

The new doc page wasn't being listed in the side-bar, presumably because this entry was missing in the summary.md.

Docs: Add satellites best practices to summary

---

buildkitd/buildkitd.go

It looks like the computed cache values are already exposed by the `ListWorkers` endpoint via the `GCPolicy` attribute. 
The [`CACHE_ALL_KEEP_BYTES`](https://github.com/earthly/earthly/blob/main/buildkitd/entrypoint.sh#L186) variable is set to the byte value of `CACHE_SIZE_MB`, so it should be ok to rely on this value.
It should be possible to add the `gckeepstorage` value to the endpoint response, but that will require a few code changes in BuildKit.

Display warning message when configured cache size is too small

---

builder/builder.go
cmd/earthly/flag/global.go
cmd/earthly/subcmd/build_cmd.go

Adds `--disable-remote-registry-proxy` as a workaround for users who may have problems with the remote registry proxy.

Add flag to disable remote registry proxy

---

cmd/earthly/subcmd/common.go
cmd/earthly/subcmd/project_cmds.go
cmd/earthly/subcmd/satellite_cmds.go

Satellites must be asleep to start a manual update. We would previously produce an error if the satellite was not asleep, but this has been confusing to users.
This PR introduces ~~a prompt which will ask the user permission~~ flag which will need to provided before automatically sleeping the satellite and starting the update.

Put satellites to sleep before starting updates

---

go.mod
regproxy/controller.go
regproxy/controller_test.go

Fixes: https://github.com/earthly/earthly/issues/3740
The Darwin proxy healthcheck was timing out immediately. This wasn't obvious on faster machines where the proxy came up immediately. 
I also renamed a context value to disambiguate it from the one in the `defer`. 
Thanks to @brandonSc for the testing and confirmation help!

Fix issue with Darwin proxy container wait time

---

CHANGELOG.md
buildkitd/buildkitd.go
buildkitd/entrypoint.sh
buildkitd/settings.go
docs/caching/managing-cache.md

automatically set cache size to min(55%, max(10%, 20GB)), rather than using buildkit's 10% default.

override buildkit's automatic cache size

---

util/containerutil/shell_shared.go
util/containerutil/shell_shared_test.go

An empty result was leading to the below panic:
```
panic: runtime error: index out of range [4] with length 1
goroutine 126 [running]:
github.com/earthly/earthly/util/containerutil.(*shellFrontend).ContainerList(0x0?, {0x105d40148?, 0x1400049a1e0?})
github.com/earthly/earthly/util/containerutil/shell_shared.go:76 +0x334
github.com/earthly/earthly/regproxy.(*Controller).stopOldDarwinProxies(0x1400013a000, {0x105d40148, 0x1400049a1e0})
github.com/earthly/earthly/regproxy/controller.go:181 +0x38
github.com/earthly/earthly/regproxy.(*Controller).startDarwinProxy.func1()
github.com/earthly/earthly/regproxy/controller.go:123 +0x38
created by github.com/earthly/earthly/regproxy.(*Controller).startDarwinProxy in goroutine 112
github.com/earthly/earthly/regproxy/controller.go:122 +0xd4
```

Fix panic on empty docker ps result

---

cmd/earthly/app/run.go
cmd/earthly/app/run_test.go
util/stringutil/filter.go
util/stringutil/filter_test.go

fixes #3746
when running `earthly --secret foo=bar --ci +test`, earthly will now display
earthly -i --secret foo=XXXXX +test
previously it wouldn't display a suggested command when secrets were present, when no secrets were specified, it would incorrectly suggest to run:
earthly -i --ci +test
which would return an error.

don't suggest using both --interactive and --ci

---

CHANGELOG.md
buildcontext/git.go
tests/git-metadata/Earthfile
util/gitutil/detectgit.go

EARTHLY_GIT_REFS should only return refernces that point at the commit rather than contains the commit.

EARTHLY_GIT_REFS: use git-each-ref --points-at

---

cmd/earthly/subcmd/account_cmds.go
tests/account/test-login.sh

Fixes: https://github.com/earthly/earthly/issues/3761
Using `--token` was working correctly, but did not ultimately create the `auth.credentials` file as the code assumed the user was already logged in. This led to some issues with Satellite commands. This change ensures that using `--token` will always create `auth.credentials`.

Ensure auth.credentials file is created with --token

---

cloud/satellite.go
cmd/earthly/subcmd/satellite_cmds.go
go.mod
go.sum

If a satellite is not in a sleep or "offline" state, then the command will ask the user to re-run using a `--force` flag instead. This prevents a user from mistakenly killing builds that may be running.

Satellite `rm` requires a `--force` if it's running

---

docs/docker-images/all-in-one.md

This satisfies the following Alex writing rule:
> Using 'simple' may come across as condescending.
Reference:
https://github.com/errata-ai/alex/blob/master/alex/Condescending.yml
I also dropped _just_ which is flagged in the linked article:
https://css-tricks.com/words-avoid-educational-writing/#aa-6-just
Thanks for all the work on Earthly, I am enjoying trying it out ✨

docs: update Docker document to remove Simple prefix in demo headings

---

Earthfile
ast/commandflag/flags.go
builder/builder.go
cmd/earthly/bk/buildkitskipper_create.go
cmd/earthly/flag/global.go
cmd/earthly/subcmd/build_cmd.go
earthfile2llb/converter.go
earthfile2llb/earthfile2llb.go
earthfile2llb/interpreter.go
features/features.go
inputgraph/hash.go
inputgraph/loader.go
tests/autoskip/Earthfile
tests/autoskip/build-flag.earth
util/buildkitskipper/cloud.go
util/buildkitskipper/local.go
util/flagutil/parse.go

Implements: https://github.com/earthly/earthly/issues/3581
Adds support for `BUILD --auto-skip <target-name>` where individual targets may be auto-skipped. 
Example: 
```
VERSION 0.8
FROM alpine
PROJECT earthly-technologies/core
a:
RUN echo "hello from a"
b:
RUN echo "hello from b"
basic:
BUILD --auto-skip +a --foo=1
BUILD --auto-skip +b
```
Output for second run (after auto-skip results captured): 
```
Init 🚀
buildkitd | Found buildkit daemon as docker container (earthly-dev-buildkitd)
Streaming logs to https://cloud.earthly.dev/builds/75a1763e-9995-4494-b115-ba6bbf361621
Build 🔧
alpine | --> Load metadata alpine linux/amd64 …
```

Allow for --auto-skip on BUILD commands

---

docs/docker-images/dind.md

we should include older tags for users who rely on outdated versions of docker

add older tags to dind docs

---

CHANGELOG.md
ast/tests/with-docker.ast.json
buildkitd/dockerd-wrapper.sh
tests/with-docker/Earthfile
tests/with-docker/pre-script.sh

This is to allow for runtime configuration before executing a `WITH DOCKER` statement, such as selecting which version of iptables to use.

dockerd-wrapper: execute pre-script

---

Earthfile

earthly attempts to create a symbolic link to /sbin/iptables-legacy whenever wsl is detected.

dind:alpine-3.19 install iptables-legacy

---

buildkitd/Earthfile
go.mod
go.sum

I accidentally merged this [Core PR](https://github.com/earthly/earthly/pull/3794) before the [BK one](https://github.com/earthly/buildkit/pull/42). This PR updates the correct `earthly-main` commit SHA.

Update BK to fbd249f8

---

buildcontext/git.go

We've had reports of internal errors resolving git projects, which could be related to using an image for the wrong architecture.  Appending the intended platform to the error could shed some light on the issue.
Example error: 
```
exec /bin/sh: exec format error
ERROR
The internal command
GET GIT META github.com/org/repo:refs/main
did not complete successfully. Exit code 1 
```

Append platform to git project errors

---

docs/caching/caching-via-registry.md

https://aws.amazon.com/blogs/containers/announcing-remote-cache-support-in-amazon-ecr-for-buildkit-clients/

Mark AWS ECR explicit registry caching as supported

---

earthfile2llb/interpreter.go
tests/Earthfile
tests/cache-cmd.earth

Users reported that that ARGs were not expanded in the `--id` of `CACHE` commands. For example, the following would not expand the arg, and result in a cache id of the literal string `$something`:
```
ARG something
CACHE --id $something
```

Expand args in CACHE --id

---

docs/cloud/satellites/self-hosted.md

The earthly-cache volume conflicts with local buildkit.

Different volume in self-hosted instructions

---

earthfile2llb/converter.go
earthfile2llb/earthfile2llb.go
earthfile2llb/with_docker_run_base.go
earthfile2llb/with_docker_run_local_reg.go
earthfile2llb/with_docker_run_local_tar.go
earthfile2llb/with_docker_run_reg.go
earthfile2llb/with_docker_run_tar.go
go.mod
go.sum
logbus/command.go
logbus/run.go
logbus/solvermon/solvermon.go
logbus/target.go
tests/Earthfile
tests/logbus/Earthfile
tests/logbus/manifest.earth
util/deltautil/apply.go
util/deltautil/go.mod
util/deltautil/go.sum

Addresses: https://github.com/earthly/earthly/issues/3807
This PR adds new Logbus commands for pseudo-commands like `BUILD` & `FROM` that don't necessarily lead to a command being run in BuildKit. It also links commands to any referenced targets. For example: `COPY +foo/file .` will ensure the Logstream data reflects the fact that the `COPY` command refers to the `+foo` target. This will allow for some more interesting UI features.
The main changes are:
* Some Logbus commands are created ahead of time rather than while listening for solve updates
* Some commands are created and updated in place for pseudo-commands
* If set, the command ID will be used in Earthfile2LLB to link a command to a target
Please have a look at the implementation. I'll take a look at adding tests where possible if …

Logstream: link nested targets to parent commands & BUILD command

---

cmd/earthly/subcmd/build_cmd.go

We need to support `EARTHLY_ORG` & `--org` to get org ID data to Logstream in all cases. It looks like we inadvertently lost support for these settings with this change: https://github.com/earthly/earthly/commit/cbcad005b087f2177fabbbb8dee908de371eb69d#diff-1ca730ef8be44ea6574fb0c5e06a96627cea73b86f46ba51ba09c5807418527aL158
I'll look into adding a test or two if this looks good.

Bring back support for org env/flag for log streaming

---

Earthfile

1. Use `DEEP_CLONE` `FUNCTION`
2. Change order of args/commands to optimize caching
3. Improve idempotency for `+open-pr-for-fork` so that we can update the test pr in case it's already open.
4. Temporarily open a PR before merging main to docs-0.8 to address branch protection rules

Fix & Improve `+merge-main-to-docs` & `+open-pr-for-fork`

---

earthfile2llb/interpreter.go
tests/wildcard-build.earth

`BUILD --auto-skip ...` is only valid when `VERSION --build-auto-skip ...` is enabled. When it isn't, an error should be returned

BUILD --auto-skip was silently ignored when not feature flagged

---

ast/tests/copy.ast.json
tests/Earthfile
tests/copy.earth
util/llbutil/copyop.go

Fixes: https://github.com/earthly/earthly/issues/3875
This PR fixes the issue, but I'm curious why the `!strings.Contains(src, "*")` was added in the first place. It seems like all of the relevant tests pass without this extra condition.

Fix COPY --if-exists with wildcard

---

.github/renovate.json5
Earthfile

This will open separate PRs when a new alpine docker image or docker apk package becomes available.
This will be followed by another PR to add a github action to release a new image upon merging the Renovate PR.
Once the above is done similar PRs will be opened to address the ubuntu images.

Add Renovate rules to update alpine-dind image dependencies

---

Earthfile

Before this change, the target `+merge-main-to-docs`  would open a new temp PR and wait for all its GH checks to complete (or for first failure). Unfortunately, One of those checks that it was waiting for is the job that invoked the target, so the target would get stuck waiting on itself until timing out.
This change limits the target to only watch for the "check broken links" job to complete before trying to merge the PR/branch.

Fix worklow that merges main to docs-0.8

---

ast/Earthfile
inputgraph/loader.go
tests/autoskip/Earthfile
tests/autoskip/arg-change.earth
util/deltautil/Earthfile

The auto-skip code did not account for the "base" target. Hence, the change to root-level `ARG`s were not breaking the cache. 
https://github.com/earthly/earthly/issues/3895

Auto-skip: ensure we account for +base

---

go.mod
go.sum
logbus/bus.go
logbus/formattedwriter.go
logbus/formatter/formatter.go

Used to filter log entries by command ID in the UI.

Logstream: add command ID to formatted logs

---

buildkitd/buildkitd.go
util/containerutil/shell_shared.go
util/containerutil/types.go

Examples of the new warning:
When starting a new container:
```
buildkitd | Starting buildkit daemon as a docker container (earthly-dev-buildkitd)...
buildkitd | Warning: earthly-dev-buildkitd was started using architecture amd64, but host architecture is arm64; is DOCKER_DEFAULT_PLATFORM accidentally set?
```
When checking an existing container:
```
buildkitd | Found buildkit daemon as docker container (earthly-dev-buildkitd)
buildkitd | Warning: currently running earthly-dev-buildkitd under architecture amd64, but host architecture is arm64; is DOCKER_DEFAULT_PLATFORM accidentally set?
```
fixes #3937

warn if arch mismatch between host and local buildkit

---

earthfile2llb/converter.go
earthfile2llb/earthfile2llb.go
earthfile2llb/interpreter.go

A missing func call was leading to some target statuses not being updated.

Logstream: ensure all failed targets are marked as such

---

cmd/earthly/app/before.go
cmd/earthly/app/run.go
cmd/earthly/flag/global.go
cmd/earthly/subcmd/build_cmd.go
logbus/formatter/formatter.go
logbus/setup/setup.go
util/execstatssummary/tracker.go

Outputs a list of targets which include the max memory and cpu time that was consumed from a single RUN command.

exec-stats-summary: output summary of stats at end

---

cloud/client.go

Fixes a problem with log deltas being disrupted before being fully sent.

Logstream: prevent context cancels from disrupting conn

---

cmd/earthly/subcmd/build_cmd.go
logbus/setup/setup.go
logbus/ship/ship.go
logbus/ship/ship_test.go

The previous PR https://github.com/earthly/earthly/pull/3953 surfaced that not all messages were being written after a user-initiated cancelation. This PR adds a short sleep to allow the messages to be written to the send channel. I tried another approach using channels but gave up after several hours because target & command writers are not reliably closed on cancellation. I don't like adding `time.Sleep` but the alternative will require a lot of effort.

Logstream: improve message draining

---

.buildkite/tests.sh
.github/workflows/ci-docker-satellites.yml
.github/workflows/ci-docker-ubuntu.yml
.github/workflows/ci-podman-ubuntu.yml
Earthfile
tests/Earthfile

The mac instances that run the buildkite tests only have 8GB (7GB under the docker VM). This breaks up the tests into more granular groups to isolate memory-intensive tests.

break up tests for mac+buildkite tests

---

go.mod
go.sum

`main` appears to be breaking due to the differing versions of `deltautil` & Earthly.

Bump google.golang.org/protobuf to v1.33.0

---

.github/workflows/ci-docker-satellites.yml
.github/workflows/ci-docker-ubuntu.yml

c502950b56e9247c659a593567e2a3ff30f08054 renamed test-quick to test-misc; however tests-quick was missed. This renames it to singular test-quick (to make searching easier in the future).

rename tests-quick to test-misc

---

go.sum
logbus/run.go
logbus/run_test.go

SSH URLs were breaking links in the new UI.

Handle source location containing SSH URL

---

.buildkite/tests.sh
Earthfile
ast/tests/Earthfile

additionally add a retry attempt in the buildkite test, to avoid having to re-run all groups if a single group fails.

break up ast tests to prevent OOM errors

---

Earthfile

Rather than just display the PR number, display a full URL, so users can click on it.

display URL of existing PR

---

.github/renovate.json5

1. `matchFileNames` takes exact file name or a globbing expression but not regex (this rule excludes updates of earthly/dind  in docs-0.8 when found in the root Earthfile
2. remove new line

renovate- fix rules

---

Earthfile

b3309ddbb5d23050de7d7951fac9ced55d0e01d5 renamed test-quick to test-misc; however missed the target under test-no-qemu.

test-quick was renamed to test-misc

---

ast/tests/host.ast.json
tests/host.earth

`acbgrep` isn't available here. Plus, the other tests in this file just use `grep`.

Fix host test use of grep

---

Earthfile
tests/integration-base/Earthfile

The BuildKit specified when running `+for-linux` and friends is not also being used by `RUN_EARTHLY` tests which use the `earthly-integration-test-base` image. This PR adds a similar argument for tests based on the latter image. 
```
earthly -P +test-no-qemu-group8 --BUILDKIT_PROJECT="../buildkit"
```

Allow for local --BUILDKIT_PROJECT when running RUN_EARTHLY tests

---

Earthfile
not-a-unit-test.sh
scripts/unit-test-parser/main.go

example output:
```
+unit-test | --- Test Duration Summary ---
+unit-test | Package                                               Test                                                                                        Action  Elapsed (seconds)
+unit-test | github.com/earthly/earthly/debugger/server            TestServer                                                                                  pass    0.01
+unit-test | github.com/earthly/earthly/inputgraph                 TestHashTargetCache                                                                         pass    0.01
+unit-test | github.com/earthly/earthly/inputgraph                 TestHashTargetNoCache                                                                       pass    0.01
+unit-test | …
```

display unit-test test durations

---

cloud/github.go
cmd/earthly/subcmd/account_cmds.go
cmd/earthly/subcmd/github_cmds.go
cmd/earthly/subcmd/root_cmds.go
tests/autocompletion/Earthfile
tests/shared-cache/lib2/Earthfile

Adds a new hidden command `earthly github add` that lets the user create a new [GHA-Satellites integration](https://docs.google.com/document/d/1Hl42AT8OjRTw2f9Yv0J757_GewLrOk8RVZsBsoxYjbY/edit#heading=h.5imekt3ni58h) (experimental)

feat: add GHA token setting

---

CHANGELOG.md
buildcontext/git.go
cmd/earthly/subcmd/build_cmd.go
docs/earthfile/builtin-args.md
features/features.go
tests/git-metadata/Earthfile
tests/git-metadata/test.earth
util/gitutil/detectgit.go
variables/builtin.go
variables/reserved/names.go

1. Add EARTHLY_GIT_AUTHOR_EMAIL and `EARTHLY_GIT_AUTHOR_NAME` built-in args.
2. Address #3822

fix builtin arg for author; add two new args

---

.buildkite/tests.sh

fixes container name typo in 577d8e1e21ab495eb552135bbb74c67cad58174f

buildkite: display buildkit logs on failure

---

.buildkite/tests.sh

- handle interrupts (in order to print a clearer error message indicating buildkite cancelled the test).
- expand the container cleanup phase of the buildkite test to remove all earthly-* containers.
- display buildkite build, job, and agent IDs (to make it possible to match up test failures with agent logs)

buildkite: handle interrupts and remove all earthly-* containers

---

.buildkite/tests.sh
.github/workflows/ci-docker-ubuntu.yml
.github/workflows/ci-podman-ubuntu.yml
tests/Earthfile
tests/autoskip/Earthfile

the autoskip+test-all target requires more than 16GB of memory, which is causing the M1 test instance to run out of memory and fail.

split up autoskip tests

---

Earthfile

test groups 9 and 10 were created in bf607d263c05ac9118c517bc87eb24178a01a222; however, they were not added to the root Earthfile, which is what the buildkite test calls.

buildkite: add missing test groups 9 and 10

---

.buildkite/tests.sh
.github/workflows/ci-docker-ubuntu.yml
.github/workflows/ci-podman-ubuntu.yml
Earthfile
tests/Earthfile
tests/autoskip/Earthfile

The autoskip tests are still periodically OOMing; this splits them up further.

buildkite: split up autoskip tests

---

cmd/earthly/base/buildkit.go

The GH SH runner needs to call the satellite through `earthly.local` hostname.
This PR makes possible overwriting the satellite address also for SH satellites.

add SatelliteAddress overwrite support for SH satellites too

---

ast/ast.go
cmd/earthly/app/run.go
earthfile2llb/converter.go
earthfile2llb/interpreter.go
earthfile2llb/interpretererror.go
inputgraph/error.go
logbus/solvermon/vertexmon.go
outmon/vertexmon.go
tests/Earthfile

Old Error:
```
Error: tests/raw-output2/Earthfile Line:7:4 the first command has to be FROM, FROM DOCKERFILE, LOCALLY, ARG, BUILD or IMPORT
```
New Error:
```
Error: tests/raw-output2/Earthfile:7:4 apply FOR ... IN: requires a FROM, FROM DOCKERFILE, or LOCALLY
Hint: This command needs to run in a shell. You should be able to solve this by adding 'FROM someImage' on the line before this one.
in              github.com/earthly/earthly/tests/raw-output2:agbell/error_message+for
```
The `path:line:col` is source link format that is clickable in VS Code, intellij and other IDEs. Changing errors to use it instead of `Error: file Line:line:col`

Requires FROM error message improvement

---

buildkitd/dockerd-wrapper.sh

The `with DOCKER --cache-id` feature requires locking to prevents two buildkit from running two instances of docker on the same shared data-root.

fix: add locking to WITH DOCKER --cache-id

---

cmd/earthly/flag/global.go
cmd/earthly/subcmd/build_cmd.go

Adds a new hidden --ticktock flag, which can be used to enable to new experimental fork of buildkit which features a different scheduler.

feat: --ticktock flag

---

.github/workflows/ci-docker-ubuntu.yml
scripts/tests/backwards-compatability.sh

Introduces a new test for validating earthly v0.8.0 can work with the current version of earthly-buildkitd.
Fixes https://github.com/earthly/earthly/issues/4128

Backwards compatability test for WITH DOCKER

---

util/fsutilprogress/progress.go

I noticed this apparent typo while debugging source op caching in BuildKit. 
Before: 
After:

Fix errant paren in file info message

---

cmd/earthly/base/init_frontend.go
cmd/earthly/subcmd/build_cmd.go

This fixes the issue where the bootstrap command was ignoring the --ticktock option.

fix: the --ticktock flag should also be used for bootstrap

---

.github/actions/stage2-setup/action.yml
.github/workflows/build-earthly.yml
.github/workflows/ci-earthly-next-docker-ubuntu.yml
.github/workflows/reusable-test.yml

Adds a new workflow to run the +docker-tests-no-qemu-group* tests using the buildkit version from the earthly-next branch.

test: use earthly-next branch for some tests

---

tests/remote-cache/Earthfile

Progress bars sometimes print out in `earthly-next` for cached operations. The caching behavior is working, though. 
This PR updates a remote caching test to be more precise & ignore progress output. It now passes for both BuildKit branches. 
This commit with `earthly-next` tests: https://github.com/earthly/earthly/pull/4146
Failure example: https://github.com/earthly/earthly/actions/runs/9196103317/job/25295783368?pr=4139

Have remote cache test ignore progress

---

.github/workflows/ci-docker-satellites.yml
.github/workflows/reusable-satellite-smoke-test.yml

Introduces a new reusable-smoke-test to our Github actions which runs a simple/arbitary build on a satellite. We use this to mainly test connectivity with self-hosted and BYOC satellites.

BYOC and Self-Hosted Dogfood

---

earthfile2llb/converter.go
earthfile2llb/with_docker_run_local_reg.go
earthfile2llb/with_docker_run_reg.go
logbus/solvermon/vertexmon.go
logbus/solvermon/vertexmon_test.go

If a run fails in WITH DOCKER you get an error message like this:
```
================================== ❌ FAILURE ===================================
./t/with-docker+fail-test1 *failed* | Repeating the failure error...
./t/with-docker+fail-test1 *failed* | --> WITH DOCKER RUN --privileged echo "dummy" && false
./t/with-docker+fail-test1 *failed* | Starting dockerd with data root /var/earthly/dind/7b5da64c458d405fff1f21d3a985f6812f9eaad6af9c6eb0d2b8c1ca7422a2e2/tmp.lbamkM
./t/with-docker+fail-test1 *failed* | dummy
./t/with-docker+fail-test1 *failed* | ERROR tests/with-docker/Earthfile:186:8
./t/with-docker+fail-test1 *failed* |       The command
./t/with-docker+fail-test1 *failed* |           WITH DOCKER RUN --privileged echo "dummy" && false
./t/with-docker+fail-test1 *failed* | …
```

Better error message for WITH DOCKER (unlazy force execution)

---

buildkitd/entrypoint.sh

This fix is relevant for tun devices, which are common in VPN implementations. For example, while a "normal" default route may look like:
default via 192.168.1.1 dev enp1s0 proto dhcp src 192.168.1.123 metric 100
A tun device for a VPN may instead look like:
default dev tun0 scope link
In the current entrypoint, the device name would be incorrectly parsed as "link" instead of "tun0". By using sed to find the word after "dev", the result is more likely to be correct. Sed is used elsewhere in the entrypoint, so it is already an expected utility.
When the device name is incorrectly parsed, the earthly-buildkitd container fails with the error:
cat: can't open '/sys/class/net/link/mtu': No such file or directory

Fix device name parsing for MTU discovery when using link scoped devices

---

logbus/solvermon/vertexmon.go
logbus/solvermon/vertexmon_test.go

See #4221 for details and how to repro.
Added tests to validate that the regex matches as expected.
Didn't have time to add tests for formatErrorMessage(), but I confirmed that it correctly formats the error now:
Also verified that it doesn't panic when the regex fails to match:

fix: Match internalfailed errors in formatErrorMessage() (fixes #4221)

---

earthfile2llb/interpreter.go
earthfile2llb/with_docker_run_base.go
earthfile2llb/with_docker_run_local_reg.go
earthfile2llb/with_docker_run_local_tar.go
earthfile2llb/with_docker_run_reg.go
earthfile2llb/with_docker_run_tar.go
tests/Earthfile
tests/aws-flag.earth
tests/oidc/aws.earth
tests/oidc/test-aws.sh

This PR fixes AWS and OIDC related options not being handled when running `WITH DOCKER ...` command.
Added related tests which are mostly based off the non `WITH DOCKER ...` variant.
Fixes https://github.com/earthly/earthly/issues/4241

Propagate aws and oidc related options for WITH DOCKER command

---

cloud/cloud_installation.go
cmd/earthly/subcmd/cloud_installation_cmds.go
go.mod
go.sum

This tweaks the BYOC cloud installation methods to enable manual installation; and installation via terraform. Example commands:
To install automatically via CloudFormation: `earthly cloud install --via cloudformation --name <stack-name>`
To install automatically via Terraform: `earthly cloud install --via terraform`
To install manually:
```
earthly cloud install \
--name <name> \
--aws-account-id <aws-account-id> \
--aws-region <aws-region> \
--aws-security-group-id <aws-security-group-id> \
--aws-ssh-key-id <aws-ssh-key-id> \
--aws-subnet-id <aws-subnet-id> \
--aws-instance-profile-arn <aws-instance-profile-arn> \
--aws-earthly-access-role-arn <aws-earthly-access-role-arn>
```
Docs forthcoming on the new installation options.

Add terraform and manual installation support

---

docs/cloud/satellites/byoc/aws/manual.md
docs/cloud/satellites/byoc/aws/terraform.md

The policy suggested in the docs (the one that allows Earthly's backend access to the 3rd party cloud) now includes tags that limit Earthly's access to resources that contain a certain tag.

Docs: Update suggested IAM policy for BYOC manual install

---

buildkitd/dockerd-wrapper.sh

When using a self-hosted satellite with the `--docker-cache` experimental feature enabled, it was found that leftover bad state in the cached data-root could cause builds to start failing. In particular, a leftover, stopped container making use of one of the images that the `dockerd-wrapper.sh` attempts to `rmi` would result in a `unable to remove repository reference` error. Some additional debugging revealed that other types of docker objects are potentially left behind in the data-root. This change modifies the `docker-wrapper.sh` to do some housekeeping of these undesirable objects, and also makes changes to avoid having builds fail due to unanticipated leftover state.

Dockerd wrapper housekeeping

---

docs/earthly-command/earthly-command.md

The syntax for this command was mentioned the use of parenthesis in a way that is not valid bash. I believe this was probably due to some confusion with the way artifact copying works in Earthfile.

Docs: Fix `earthly --artifact` syntax
