- build.earth
- buildkitd/buildkitd.toml.template
- cmd/earth/main.go
- docs/earth-command/earth-command.md
- earthfile2llb/converter.go
- earthfile2llb/dedup/targetinput.go
- earthfile2llb/runmount.go
- examples/tests/build.earth
- examples/tests/cache2.earth
* Mount params not args-expanded
* Cache key dependent on tag (which changes with every branch switch, causing frequent cache bust)
* Cache size for cache mounts too small, causing frequent GC of it
Note that this will break build temporarily as new build definition uses arg in cache mount.
> Fix cache mount issues

- README.md
Github now has the ability to download the latest release directly. See [here](https://stackoverflow.com/questions/24987542/is-there-a-link-to-github-for-downloading-a-file-in-the-latest-release-of-a-repo/54836319#54836319) and [here](https://help.github.com/en/github/administering-a-repository/linking-to-releases).
> Greatly simplify Mac/Linux install instructions

- contrib/earthfile-syntax-highlighting/README.md
- contrib/earthfile-syntax-highlighting/build.earth
- contrib/earthfile-syntax-highlighting/package.json
- contrib/earthfile-syntax-highlighting/syntaxes/earthfile.tmLanguage.json
- docs/earthfile/earthfile.md
- earthfile2llb/converter.go
- earthfile2llb/image/image.go
- earthfile2llb/listener.go
- examples/cpp/.gitignore
- examples/tests/config.earth
- go.sum
- llbutil/constants.go
* Smoke tested via augmenting existing config test
* Manually tested via docker inspect on produced image
* Manually tested via [this example](https://medium.com/better-programming/docker-healthchecks-eb744bfe3f3b)
This will require a release of the syntax highlighting package for vscode.
~I still need to add docs for this hence draft.~ Done
Fixes #80
> Add support for HEALTHCHECK

- build.earth
- buildcontext/git.go
- buildkitd/build.earth
- buildkitd/buildkitd.go
- buildkitd/entrypoint.sh
- buildkitd/envcredhelper.sh
- buildkitd/settings.go
- cmd/earth/main.go
- config/config.go
- go.mod
- go.sum
The global config file (default location ~/earthly/config.yaml) can be
used to store https credentials for various sites. For example:
```yaml
git:
default:
auth: https
username: foo
password: bar
github.com:
username: f00
password: bart
```
If the --git-username or --git-password command line values are given,
then those values will override all values stored in the config file.
> Create global config file for storing credentials

- conslogging/conslogging.go
This fixes the handling of control characters which are used to display
progress bars which use the \r control character.
> Fix prefixing for control character progress bars

- buildkitd/buildkitd.go
This fixes a bug which was introduced by #101
> bugfix: GIT_URL_INSTEAD_OF needs to be passed to buildkitd

- buildkitd/buildkitd.go
- buildkitd/entrypoint.sh
earth sets a variable named GIT_CONFIG which conflicts with what "git config" is looking for, renaming it to EARTH_GIT_CONFIG avoids the conflict.
> GIT_CONFIG env conflicts with using git

- buildcontext/detectearthfile.go
- buildcontext/excludes.go
- buildcontext/git.go
- buildcontext/local.go
- buildcontext/resolver.go
- cmd/earth/main.go
- contrib/earthfile-syntax-highlighting/README.md
- contrib/earthfile-syntax-highlighting/package.json
- examples/tests/build.earth
* For backwards compatibility, `build.earth` is used if an `Earthfile` is not present
* Docs update coming in separate PR
> Rename build.earth to Earthfile

- .github/workflows/ci.yml
- build.earth
- buildkitd/build.earth
- buildkitd/buildkitd.go
- buildkitd/entrypoint.sh
Use a sparse file for the loop device.
Incidentally - we already had the `dd` command needed to create a sparse file, as a fallback. So this PR makes that `dd` command the only one to be used.
There is also an option to auto-detect whether the underlying fs is already ext4 to skip wrapping with a loop device. However, this option is not used by default (`FORCE_LOOP_DEVICE` is true).
Fixes #36
> Use a sparse file for the loop device

- docs/earth-command/earth-command.md
when a user runs `earth --help` it shows a links to https://docs.earthly.dev/earth-command however on that page it doesn't define how the target-reference can be formatted.
> docs: target reference

- buildkitd/buildkitd.go
- buildkitd/settings.go
- cmd/earth/main.go
- config/config.go
Rather than assume users want to cache data under tmp,
allow the user to override it.
The default value will be changed to /var/cache/earthly
so the cache persists between reboots.
> Allow user to change earthly cache path

- conslogging/color.go
- conslogging/conslogging.go
Also removes red colors from prefixes to prevent confusion regular
output with errors/warnings.
> Add warnf func to print warning messages in red

- examples/dotnet/Earthfile
An issue in buildkit caused a "tar/archive: sockets not supported" error
while building the dot net example; this issue has been fixed upstream
in buildkit ( see https://github.com/moby/buildkit/pull/1581 ), and we
can now remove this work-around.
> Remove socket file rm hack

- cmd/earth/main.go
rather than just die, display a warning if the symlink can't be
followed.
> display a warning on symlink eval error

- builder/solver.go
- builder/solver_monitor.go
- conslogging/conslogging.go
only output percentage every 5 seconds or when it finishes, this avoids
the issue of lots of stdout being written.
Additionally display failed commands in red, and avoid showing too much
of context canceled errors which are a side effect of the main failure
(and can confuse users).
> limit amount of status percentage that is output

- .circleci/config.yml
- .github/workflows/ci.yml
- Earthfile
- buildcontext/git.go
- buildcontext/local.go
- builder/builder.go
- builder/solver_monitor.go
- conslogging/conslogging.go
- earthfile2llb/converter.go
- earthfile2llb/states.go
* Use different colors if the build args are different
* Use different colors for different build contexts
* Improved, slightly cleaner printout of Earthfile commands
* An unrelated change: Add some handy build targets (eg `earth +for-linux`) for faster development
* `+earth` for mac and linux have different colors
* The different contexts have different colors so as to be able to tell them apart
* Other improvements (eg eliminating the `[ ]` around the `RUN` command arguments)
> Improve vertex names... and colors

- Earthfile
- buildkitd/buildkitd.go
- cmd/debugger/main.go
- cmd/earth/main.go
- config/config.go
- debugger/server/debugger_server.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
In the event that a RUN command fails, when earth is run with the
interactive flag (-I); rather than clean up the failed build process, it
will present the user with an interactive shell.
This allows a user to manually inspect the system at the point of
failure, and additionally lets arbitrary commands be run interactively
without the need to modify the Earthfile.
This is currently limited by:
- no up/down arrow support for history
- output text race condition where two lines sometimes appear on the same line
- hardcoded ip/port for the reverse debugger shell
> Add experimental interactive debugging mode

- cmd/debugger/main.go
- cmd/earth/main.go
- debugger/server/debugger_server.go
- earthfile2llb/converter.go
Rather than use a hardcoded port, let the OS provide a free port. The
address to connect to is now passed as a secret to prevent the port from
affecting the cache.
> let the OS provide an open port for the debugger

- Earthfile
- buildkitd/Earthfile
- buildkitd/buildkitd.go
- buildkitd/buildkitd.toml.template
- buildkitd/entrypoint.sh
- buildkitd/settings.go
- cmd/earth/main.go
verbose flag enables debugging mode of the buildkitd container (which
enables logs to be viewed via docker logs earthly-buildkitd)
> Add verbose command line flag

- Earthfile
Our build has a circular dependency where the debugger image is required
before our CI can pass; however CI is responsible for creating the image
after the tests pass. We will pin the version to get around this problem
and come up with a better solution down the road.
> Pin debugger image to a specific version

- .circleci/config.yml
This will allow circle to run safely for external contributors.
> Docker login not necessary in circle

- buildkitd/buildkitd.go
If the earthly-buildkitd container is in a stopped or exited state,
remove it before attempting to start a new instance of it.
This fix is to allow for the removal of the --rm flag from the
docker run command, so that logs persist in the cause of a failure.
This fixes https://github.com/earthly/earthly/issues/152
> Remove earthly-buildkitd container if exited

- Earthfile
- buildkitd/buildkitd.go
- buildkitd/settings.go
- cmd/debugger/main.go
- cmd/earth/main.go
- config/config.go
- debugger/common/settings.go
- debugger/server/debugger_server.go
- earthfile2llb/converter.go
- examples/cpp/Earthfile
Rather than using tcp to run the interactive debugger, use a
socket-based connection. This is more secure as it doesn't expose any
ports on the network (and also prevents firewalls from disallowing
connections).
> Bind interactive debugger to socket

- buildcontext/detectbuildfile.go
- buildcontext/git.go
- buildcontext/local.go
- buildcontext/resolver.go
- domain/target.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
One limitation: The dockerfile **has** to be named `Dockerfile`. The option `-f` is not yet supported.
This pretty much reuses the build context resolver that we use for Earthfiles - it was just extended to also work on Dockerfiles.
> Support for dockerfile builds in remote targets too

- buildkitd/Earthfile
- buildkitd/buildkitd.go
- buildkitd/settings.go
- cmd/earth/main.go
- config/config.go
- examples/tests/Earthfile
* Also, use tmpfs for cache in integration tests to avoid bloating Earthly cache.
This change makes Earthly 2.76X (!!!) faster on Mac, bringing its performance up-to-par with Linux.
> Use a docker volume rather than a bind-mount for cache

- .circleci/config.yml
- .github/workflows/ci.yml
- Earthfile
- buildkitd/Earthfile
Also, fix run mounts not working in Dockerfiles.
> Use buildkit Earthfile

- cmd/earth/main.go
- earthfile2llb/converter.go
* expose the -i, --interactive flags under help
* always run the command via the earthly_debugger to prevent a different
cache path from being used between interactive and non interactive
debugging
> interactive mode flag and cache fix

- .github/workflows/ci.yml
- docs/examples/gh-actions-integration.md
GitHub Actions checkout@v2 no longer leaves the branch in a detached head state,
so there is no longer a need to run `git checkout` as a step.
> Remove extraneous checkout step in Actions example

- Earthfile
- release/Earthfile
- release/earthly.rb
Example generated earthly.rb:
```
./release+release-homebrew | class Earthly < Formula
./release+release-homebrew |   desc "Build automation tool for the post-container era"
./release+release-homebrew |   homepage "https://earthly.dev/"
./release+release-homebrew |   url "https://github.com/earthly/earthly/archive/v0.0.0.tar.gz"
./release+release-homebrew |   sha256 "d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed"
./release+release-homebrew |   license "MPL-2.0"
./release+release-homebrew |   head "https://github.com/earthly/earthly.git"
./release+release-homebrew |   bottle do
./release+release-homebrew |     cellar :any_skip_relocation
./release+release-homebrew |     sha256 "5929dc77833f8c3df5401ac67fb3cd6f519b9f24152d6c8e52d8675919826934" => :catalina …
```
> Use the same go build flags in homebrew build

- examples/tests/Earthfile
- examples/tests/config.earth
- examples/tests/dind.earth
- examples/tests/docker-load.earth
- examples/tests/docker-pull.earth
- examples/tests/fail.earth
- examples/tests/push.earth
- examples/tests/transitive-args.earth
* validate that RUN commands that return an error code are correctly
caught by earth, which causes earth to fail.
This test is to prevent #204 from reoccurring.
> test for capturing run errors

- contrib/earthfile-syntax-highlighting/README.md
- contrib/earthfile-syntax-highlighting/syntaxes/earthfile.tmLanguage.json
* Fix FROM DOCKERFILE
* Fix highlighting for target and artifact refs in edge cases (eg `g++`)
* Make case-sensitive
> VS code syntax highlighting improvements.

- builder/builder.go
- buildkitd/Earthfile
- buildkitd/buildkitd.go
- buildkitd/dockerd-wrapper.sh
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- earthfile2llb/withdockerrun.go
- examples/tests/Earthfile
- examples/tests/config.yaml
- examples/tests/load-parallel.earth
This fixes two issues:
* Two DOCKER LOAD of the same target would cause a local dir key collision
* An error where two docker daemons being started at the same time would cause a race condition.
The errors looked like this
```
failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create FILTER isolation chain: iptables failed: iptables --wait -t filter -N DOCKER-ISOLATION-STAGE-2: iptables: Chain already exists.
```
```
failed to start daemon: Error initializing network controller: error obtaining controller instance: unable to add return rule in DOCKER-ISOLATION-STAGE-2 chain:  (iptables failed: iptables --wait -A DOCKER-ISOLATION-STAGE-2 -j RETURN: iptables: No chain/target/match by that name.
```
This also contains a few unrelated …
> Fix parallel dind's

- go.mod
- go.sum
current master version of urfave/cli has a bug where values set by the
environment var are not saved to the stringslice var.
Once https://github.com/urfave/cli/pull/1178 is merged, we can switch
back to using the upstream version.
> Use forked urfave/cli until upstream patch is merged

- Earthfile
- earth
The Idea with this new target, is we could have it built on master, then we can use a script like this:
```
set -e
function get_latest_binary {
docker pull alexcb132/earthlybinaries:latest
docker create --name binaryhack alexcb132/earthlybinaries
earthbinpath=/earth-linux-amd64
if [ "$(uname)" == "Darwin" ]; then
earthbinpath=/earth-darwin-amd64
fi
docker cp binaryhack:$earthbinpath ~/bin/earth-bin
docker rm binaryhack
}
LAST=`cat /tmp/last-earth-check 2>/dev/null || echo 0`
NOW=`date +%s`
since=$(expr $NOW - $LAST)
if [ $since -ge 3600 ]; then
echo pulling latest earth version
get_latest_binary
echo $NOW > /tmp/last-earth-check
fi
~/bin/earth-bin $@
```
to periodically check for latest pre-releases.
> package up binaries in docker for pre-release testing

- cmd/earth/main.go
- debugger/terminal/terminal.go
- go.mod
- go.sum
This added waiting gives `cleanupCollection.Close()` a chance to finish and remove any temp files and dirs lying around.
Fixes #244
> Perform proper cleanup on sigint and sigterm

- Earthfile
- earth
- earthfile2llb/converter.go
- earthfile2llb/dedup/targetinput.go
- earthfile2llb/variables/collection.go
- examples/tests/Earthfile
- examples/tests/non-transitive-args1.earth
- examples/tests/non-transitive-args2.earth
- examples/tests/transitive-args.earth
- release/Earthfile
- release/README.md
The logic is as follows:
A build arg override is passed transitively between targets within the same project (same Earthfile). If crossing projects, only immediate overrides are applied but not all transitive overrides.
In this case, the override will work, and the echo will print `override`.
```
one:
BUILD --build-arg VAR=override +two
two:
BUILD +three
three:
ARG VAR=default
RUN echo $VAR 
```
In this case, the override will not work, and the echo will print `default`:
`./Earthfile`:
```
one:
BUILD --build-arg VAR=override +two
two:
BUILD ./otherproj+three
```
`./otherproj/Earthfile`:
```
three:
ARG VAR=default
RUN echo $VAR 
```
-------
Additional, unrelated change:
* Use the tag `prerelease` for the prerelease earth+buildkitd, to avoid any local clash with a `:master` build of the …
> Consistent transitive override of build args

- earth
When performing bash auto completion, we can't check for updates because
it slows down the interactive experience and we can't print out anything
to stdout.
> Dont check for updates on autocompletion

- debugger/server/server_test.go
Use fatal instead of error for connection cases, otherwise if there's an
issue with the connection, it'll keep on running and then give us a nil
pointer exception which is confusing
> unittest improvement: use fatal to halt execution

- cmd/earth/main.go
- config/config.go
the brew install overrides $HOME to point to a sandbox; however when
using user.Current().HomeDir it doesn't pick this setting up ( see
https://github.com/golang/go/issues/26463 ).
> Use $HOME rather than user.Current().HomeDir

- earth
* ./earth command will fail if ~/bin doesn't exist; this will now print
an error message if it doesn't exist.
* remove earthly_binary container if it is already running.
> ./earth command should check that ~/bin exists

- cmd/debugger/main.go
- cmd/earth/main.go
- debugger/common/settings.go
* fixes #286 by correctly setting the TERM environment variable before
starting the interactive debugger shell.
> Pass along user's TERM type.

- cmd/earth/main.go
If a panic occurs during autocompletion, instead of dumping it to stderr
log it to ~/.earthly/autocomplete.log
This fixes #296
> recover panics during autocompletion

- cmd/earth/main.go
* fixes issue where "ssh agent provider: stat /run/host-services/ssh-auth.sock: no such file or directory"
error occurs when trying to access the ssh-auth.sock during CI testing (or
cases where the user doesnt have an ssh agent running)
> fix earth failure when ssh agent sock doesnt exist

- docs/earthfile/earthfile.md
move the secret example back to the correct secret location rather than where it was accidentally moved to the ssh section.
> fix earthfile secret example

- release/Earthfile
We were requested to use #{version} in https://github.com/Homebrew/homebrew-core/pull/61187
rather than have duplicate version strings in the formula.
> Use #{version} in homebrew PRs

- earth-buildkitd-wrapper.sh
> Increase timeout for buildkit wrapper start

- Earthfile
- buildkitd/dockerd-wrapper.sh
- earthfile2llb/converter.go
- earthfile2llb/listener.go
- earthfile2llb/shell.go
- earthfile2llb/variables/collection.go
- earthfile2llb/withdockerrun.go
- examples/tests/Earthfile
- examples/tests/with-docker-compose/Earthfile
- examples/tests/with-docker-compose/docker-compose.yml
- examples/tests/with-docker/Earthfile
Fixes https://github.com/earthly/earthly/issues/324
This also fixes two bugs, which were tangential:
* In certain circumstances `FROM DOCKERFILE` would cause a nil deref panic.
* `ARG` before `WITH DOCKER` caused a cryptic failure
There are still a few limitations:
* Ports exposed to the host can conflict with each other, causing issues with parallelism. We need to find a way to isolate these to the specific targets they run in.
* `WITH DOCKER --compose` installs docker-compose automatically as a separate layer from the RUN execution. However, if there are COPY's before the WITH DOCKER command, there will be noticeable re-installation of docker-compose every time those files change. A possible future solution for this is to require a specific Earthly-provided dind image, in which we put …
> Implement WITH DOCKER --compose

- docs/earthfile/builtin-args.md
- docs/earthfile/earthfile.md
- docs/examples/go.md
- docs/guides/basics.md
- docs/guides/ci-integration.md
- docs/guides/docker-in-earthly.md
- docs/guides/integration.md
Resolves some typos and grammatical mistakes found in the Earthly documentation pages.
> Fixed typos and grammatical errors in documentation

- .github/workflows/ci.yml
- Earthfile
- buildkitd/docker-auto-install.sh
- buildkitd/dockerd-wrapper.sh
- earthfile2llb/withdockerrun.go
- examples/tests/Earthfile
- examples/tests/dind-auto-install/Earthfile
- examples/tests/dind-auto-install/docker-compose.yml
Also, add official earthly/dind image, which contains docker-compose already installed. This is the recommended image to use for Docker-in-Earthly as it is the most cache-efficient.
CC @agbell
> Auto-install dockerd if not found and using WITH DOCKER

- Earthfile
- earthfile2llb/listener.go
- release/Earthfile
* Only push `earthly/dind:alpine` and `earthly/dind:ubuntu` during releases.
* Also add personalized messages for deprecated DOCKER LOAD and DOCKER PULL commands.
> WITH DOCKER release improvements

- cmd/earth/main.go
- llbutil/secrets.go
Here's an example of it working:
```
alex@mah:~/gh/earthly/earthly$ ./build/linux/amd64/earth register --email alex@example.com
An email has been sent to "alex@example.com" containing a registration token
alex@mah:~/gh/earthly/earthly$ ./build/linux/amd64/earth register --email alex@example.com --token 57271328
pick a password: 
confirm password: 
Which of the following keys do you want to register?
1) ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDtCpWpjWyMAPRDE8Kchr0u6eD/uhyPSyVy8dQfYx7/LLLvXQ9am1jZp0O44nkly92ETWY+TZdSIuNDSTMaeqhioKBKFF2cCertXzwKdHLuWzB3VAe9PeSiDejMn9TzGPih9XRFUsgPhDadxLEXJnZZVRNAMWwXFD4NlAHUtz0GULoZ8FB76tC1AmzT0CaM721NbkR94bKQweizvyXzPFBh75Ad13VIi6BX7JXgN2wai/z3Kka1puEH5C0IJL/V5OO2sfhvRa+4+ZQvxn0Cbs6MN1AOEYjagdCootOcmImo2AXezym9Rm6F524EEm+24KM9y+uvKacpxIZ0pmYuPB2f …
```
> Hook in secrets provider with secrets server

- cmd/earth/main.go
- secretsclient/client.go
example usage:
```
alex@mah:~/gh/earthly/earthly$ ./build/linux/amd64/earth secrets set /myorg/path/to/foo bar
alex@mah:~/gh/earthly/earthly$ ./build/linux/amd64/earth secrets set /myorg/path/to/other wow
alex@mah:~/gh/earthly/earthly$ ./build/linux/amd64/earth secrets set /myorg/path/friday is\ today
alex@mah:~/gh/earthly/earthly$ ./build/linux/amd64/earth secrets ls /myorg/
/myorg/data
/myorg/path/friday
/myorg/path/to/foo
/myorg/path/to/other
alex@mah:~/gh/earthly/earthly$ ./build/linux/amd64/earth secrets ls /myorg/path
/myorg/path/friday
/myorg/path/to/foo
/myorg/path/to/other
alex@mah:~/gh/earthly/earthly$ ./build/linux/amd64/earth secrets ls /myorg/path/to
/myorg/path/to/foo
/myorg/path/to/other
alex@mah:~/gh/earthly/earthly$ ./build/linux/amd64/earth secrets ls /myorg/path/to/ …
```
> list secret command (#401)

- buildkitd/Earthfile
- buildkitd/buildkitd.cache.template
- buildkitd/buildkitd.go
- buildkitd/buildkitd.toml.template
- buildkitd/entrypoint.sh
- config/config.go
Also, 0 now means to use buildkit's default, which automatically adapts to backing storage size.
This should improve performance as less GC is necessary.
> Make cache size limit 0 by default

- docs/guides/integration.md
- examples/integration-test/Earthfile
- examples/integration-test/src/smoketest/assert.sh
- examples/integration-test/src/smoketest/smoketest.sh
Updating Integration Testing example and documentation.
The documentation has been simplified to focus directly on use of `WITH DOCKER` and to remove other details.
> Updating Integration Testing example and documentation

- cmd/earth/main.go
- secretsclient/client.go
- secretsclient/lazy_ssh_agent.go
- prevent initializing the ssh agent client unless it's needed. This is
to prevent warning messages occuring if the SSH_AUTH_SOCK isn't set,
which shouldn't matter unless the secrets server is required.
> lazy init of ssh agent to avoid unneeded warnings

- cmd/debugger/main.go
- cmd/earth/main.go
- conslogging/conslogging.go
- docs/guides/ci-integration.md
Willing and ready for suggestions on this idea. I think this improves readability of the logs. Would love to detect max width of target names; and size down if possible on top of this, to make it feel less dead with small target names. But, this is a start toward that for now.
Still needs documentation pending decision on if this is worth doing.
Some examples of what this accomplishes:
Old (also now, but with `FULL_TARGETS`):
```
Deprecation: using SAVE IMAGE with no arguments is no longer necessary and can be safely removed
+base | --> FROM golang:1.13-alpine3.11
context | --> local context ./examples/go
+base | resolve docker.io/library/golang:1.13-alpine3.11@sha256:ec6dcf15073c307fbcfc3149efe8835f3ec2bd0a0cb49aaae …
```
> Add ability to align and control size of target name column in logs

- cmd/earth/main.go
- conslogging/conslogging.go
Some sample for how it will look with these changes:
```
buildkitd | Newer image available. Restarting buildkit daemon...
buildkitd | ...Done
g/e/hello-world:master+base | --> FROM busybox:1.32.0
+base | --> FROM golang:1.13-alpine3.11
context | --> local context ./examples/go
g/e/hello-world:master+base | resolve docker.io/library/busybox:1.32.0@sha256:a9286defaba7b3a519d585ba0e37d0b2cbee74ebfe590960b0b1d6a5e97d1e1d 100%
+base | resolve docker.io/library/golang:1.13-alpine3.11@sha256:ec6dcf15073c307fbcfc3149efe8835f3ec2bd0a0cb49aaaee4949cfc4c86b65 100%
context | transferring ./examples/go: 100%
+base | *cached* --> RUN apk add --update --no-cache bash bash-completion binutils ca-certificates coreutils curl …
```
> Fix environment variables, clever truncation on /, and allow ragged when wider than column

- Earthfile
- analytics/analytics.go
- cmd/earth/main.go
- fileutils/fileutils.go
- go.mod
- utils/utils.go
How about we allow overriding `EARTHLY_INSTALL_ID`, so we can exclude our own builds.
Then we'll track if it was triggered via a CI (assuming the CI env is set), which we could then use to filter out CI vs CLI executions.
> allow overriding install id

- examples/ecr-push/Earthfile
- examples/ecr-push/README.md
- examples/ecr-push/Readme.md
The current state of the world when pushing to ECR. Did not add it to the main Earthfile for running all the tests, because the only option would be localstack... and that seems to be flaky inside a `WITH DOCKER` (see the terraform example).
> Add early ECR example

- buildkitd/docker-auto-install.sh
- examples/tests/dind-auto-install/Earthfile
This will let you do a `WITH DOCKER` in an Amazon Linux container. This is especially advantageous for using other containers in combination with "amazon/aws-cli:<version>"
Amazon Linux 1 and 2 are supported.
> Allow DIND auto install on Amazon Linux

- cmd/earth/main.go
When --version is run, urfav/cli does not invoke the app.Before
function, this causes the config not to be parsed.
If a user had a config option to disable analytics, and ran the
--version flag, it would cause analytics to be reported.
> Ignore analytics for --version command

- analytics/analytics.go
- earthfile2llb/variables/collection.go
This will prevent having earth create a new installID when running the examples and other earth-in-earth tests.
> expose earthly env variable

- .buildkite/tests.sh
- Earthfile
- buildkitd/Earthfile
- buildkitd/buildkitd.toml.template
- buildkitd/cni-conf.json
- buildkitd/dockerd-wrapper.sh
- buildkitd/entrypoint.sh
- examples/tests/with-docker-compose/Earthfile
- examples/tests/with-docker/Earthfile
The net benefit of this is that `WITH DOCKER` can now run in parallel with other `WITH DOCKER`'s. No more networking-related race conditions. This also removes the lock that was preventing the race conditions before.
> Use CNI rather than host networking for buildkit

- earthfile2llb/converter.go
The error is improved from
```
node:14.15.0 | --> Load metadata
Error: build target: build main: bkClient.Build: failed to solve: rpc error: code = Unknown desc = parser failure: runtime error: invalid memory address or nil pointer dereference
```
to the slightly more useful
```
node:14.15.0 | --> Load metadata
Error: build target: build main: bkClient.Build: failed to solve: rpc error: code = Unknown desc = parse: from dockerfile: artifact +foo/Dockerfile not found; no SAVE ARTIFACT command was issued in +foo
```
The Earthfile used is
```
FROM node:14.15.0
WORKDIR /usr/build
foo:
RUN touch Dockerfile
bar:
FROM DOCKERFILE +foo/
```
Fixes https://github.com/earthly/earthly/issues/498
> Slightly better error message when no SAVE ARTIFACT command has been issued

- earthfile2llb/listener.go
- examples/tests/Earthfile
- examples/tests/escape.earth
A fix for the COPY issue @zenyui reported over on Gitter.
The fix is on line 233. The rest also addresses situations where files or artifacts with `+` are passed via build args.
> Fix for arg expansion in copy command

- builder/solver_monitor.go
- conslogging/color.go
- conslogging/conslogging.go
- earthfile2llb/converter.go
Fixes https://github.com/earthly/earthly/issues/338
The way it works:
* If output is not terminated by a `\n`, then we store the final line as an "open line" and repeat it on the next call. We print the open line as it is for now and append our own `\n`
* On the next call, any open line is pre-pended to the output
* So far this results in the following output for curl, which is an improvement:
* As an extra optimization, if there is an open line and the previous output was from the same vertex, then we go up one line using an ANSI control char and overwrite that line
* This results in this final output for curl (as well as meaningful visual updates while it's ongoing):
> Fix garbled output

- builder/builder.go
- builder/solver_monitor.go
Fixes https://github.com/earthly/earthly/issues/529
Fixes https://github.com/earthly/earthly/issues/496
Prints elapsed time after completing each command and also a summary at the end for total time spent on each target.
CC @agbell @dchw
> Print timing info on verbose

- cmd/earth/main.go
- also display as table
before:
```
alex@mah:~/gh/earthly/earthly$ go run cmd/earth/main.go org list
earthly-technologies
test123-vlad
alex (admin)
alexcb (admin)
acb (admin)
```
after:
```
alex@mah:~/gh/earthly/earthly$ go run cmd/earth/main.go org list
/test123-vlad/          member
/alex/                  admin
/alexcb/                admin
/acb/                   admin
/earthly-technologies/  member
```
> Prefix organizations with slash

- cmd/earth/main.go
- secretsclient/client.go
- The use-case is for when earthly is running in a CI, rather than have
the user issue "earth account login --token abc...", one can simply
export EARTHLY_TOKEN=abc... which will override the login logic.
> Allow EARTHLY_TOKEN env variable to override login

- cmd/earth/main.go
When no tokens exist, just exit.
> Don't print header when no tokens to list

- .github/workflows/ci.yml
- conslogging/conslogging.go
- when fetching secrets, if a warning occurs it's printed to stdout
rather than stderr, which breaks accessing secrets via the cli.
> Print warning messages to stderr rather than stdout

- secretsclient/client.go
- fixes bug where special chars in email were not being correctly
escaped, which prevented an email containing a + from being registered.
> Escape email and org names

- conslogging/color.go
- conslogging/conslogging.go
Fixes https://github.com/earthly/earthly/issues/548
> Fix metadata text color not being visible on solarized terminal theme

- cmd/earth/main.go
If a user is currently using password-based login, swtich to the newly
added ssh-key. Here's an example:
alex@mah:~/gh/earthly/earthly$ cat ~/.earthly/auth.token
plus+slash/under_hyphen-quote"@earthly.dev password MTIzNDU2Nzg5MA==
alex@mah:~/gh/earthly/earthly$ go run cmd/earth/main.go account add-key
Which of the following keys do you want to register?
1) ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDtCpWpjWyMAPRDE8Kchr0u6eD/uhyPSyVy8dQfYx7/LLLvXQ9am1jZp0O44nkly92ETWY+TZdSIuNDSTMaeqhioKBKFF2cCertXzwKdHLuWzB3VAe9PeSiDejMn9TzGPih9XRFUsgPhDadxLEXJnZZVRNAMWwXFD4NlAHUtz0GULoZ8FB76tC1AmzT0CaM721NbkR94bKQweizvyXzPFBh75Ad13VIi6BX7JXgN2wai/z3Kka1puEH5C0IJL/V5OO2sfhvRa+4+ZQvxn0Cbs6MN1AOEYjagdCootOcmImo2AXezym9Rm6F524EEm+24KM9y+uvKacpxIZ0pmYuPB2f /home/alex/.ssh/id_rsa
2) ssh-rsa …
> Automatically switch from password-based login to ssh

- .buildkite/tests.sh
- .buildkite/windows.yml
- docs/guides/integration.md
- examples/integration-test/Earthfile
- examples/integration-test/docker-compose.yml
- examples/tests/with-docker-compose/Earthfile
- examples/tests/with-docker-compose/docker-compose.yml
CC @alexcb FYI
We now use the Linux buildkite agent in Windows WSL2, rather than the Windows buildkite agent, outside of wsl2.
> Switch windows pipeline to use wsl2 buildkite agent

- secretsclient/client.go
- without this change, when the server returns a new field, the client
will reject it, thus breaking backwards-compatibility.
> Ignore unknown json fields when unmarshalling

- cmd/earth/main.go
- unfortunately colors and tabwriter don't mix (colors mess with the
column formatting).
> Display expired text for expired tokens

- cmd/earth/main.go
- go.sum
- also allow expiry to be submitted as YYYY-MM-DD, or never
example outputs:
```
alex@mah:~/gh/earthly/earthly$ go run cmd/earth/main.go account create-token --expiry never poop
created token "dAkOPv9fzauiuqJljYCHOhGj2xI5JSMHet7CENt3Sbe9lYjCJ6YsH3pu3S5k54cK" which will expire in a long while from now; save this token somewhere, it can't be viewed again (only reset)
alex@mah:~/gh/earthly/earthly$ go run cmd/earth/main.go account create-token --expiry 2020-12-12 poop
created token "m2UcF6JeuHa6DF5BDxc77OMRs7jWXRr69DwVXVldYhXYOeEF7JLJlHc8EvKLUtc8" which will expire in 1 week from now; save this token somewhere, it can't be viewed again (only reset)
alex@mah:~/gh/earthly/earthly$ go run cmd/earth/main.go account create-token --expiry 2021-02-12 poop
created token …
```
> Display token expiry after creation

- cmd/earth/main.go
- this setting should have been hidden as it doesn't apply to end users.
fixes #590 
> EARTHLY_SERVER is only meant for internal dev

- .github/workflows/ci.yml
- Earthfile
- buildkitd/dockerd-wrapper.sh
There was a conflict between host docker's IP address and the inner docker IP address. This caused the interactive debugger to not be able to find the right IP when it wanted to connect to the debug proxy.
> Fix interactive mode in WITH DOCKER

- secretsclient/client.go
- this will make it easier to debug cases where an empty string is
passed to the client.
> Validate email before registration

- cmd/earth/main.go
This changes how the earth command outputs the gRPC errors.
Example 1:
Original: `Error: build target: build main: bkClient.Build: failed to solve: rpc error: code = Unknown desc = syntax error: line 1:0 no viable alternative at input 'no-artifact:'`
Cleaned: `Error: line 1:0 no viable alternative at input 'no-artifact:'`
Example 2:
Original: `Error: build target: build main: bkClient.Build: failed to solve: rpc error: code = Unknown desc = parse: Invalid command LOL`
Cleaned: `Error: Invalid command LOL`
Fixes #537
> Pretty print some errors

- buildcontext/git.go
- builder/builder.go
- builder/solver.go
- builder/solver_monitor.go
- cmd/earth/main.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- earthfile2llb/withdockerrun.go
- llbutil/statetoref.go
Developer (cache read-only):
```
earth --remote-cache=<some-docker-tag> +<target>
```
CI (cache read-write):
```
earth --remote-cache=<some-docker-tag> --ci +<target>
```
The docker tag has to be a docker registry tag that is not used for anything else (eg should not overlap with a production docker tag). Good example: `my-company/my-service:cache`. Bad example: `my-company/my-service:latest`. The recommendation is to use a different Docker tag per each CI pipeline, in order to maximize efficiency.
See results of experimentation on this branch: https://github.com/earthly/earthly/issues/11#issuecomment-741307678
> Update remote cache implementation

- buildcontext/git.go
- builder/builder.go
- builder/solver.go
- builder/solver_monitor.go
- cmd/earth/main.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- earthfile2llb/withdockerrun.go
- llbutil/statetoref.go
- states/states.go
Re https://github.com/earthly/earthly/issues/11
This does not provide proper full support as there are many cases that need to be dealt with in order to properly use the cache. However since this is behind a feature flag, it can be merged as it is.
Changes:
* Push inline caches with every image push ~(should be very lightweight - no performance difference)~ EDIT: There is a significant performance penalty on subsequent run, in certain conditions. This has now been placed behind a flag that the user needs to activate manually (via `--inline-cache`).
* Support using any image declared in `SAVE IMAGE --push` as cache import too (if `--inline-cache` feature flag is enabled)
* Perform image pushes from within buildkit directly, rather than via `docker push`. This is necessary so that metadata …
> Support for inline cache

- builder/builder.go
- builder/solver.go
- builder/solver_monitor.go
- buildkitd/Earthfile
- cmd/earth/main.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- earthfile2llb/listener.go
- earthfile2llb/withdockerrun.go
- states/states.go
Depends on https://github.com/earthly/buildkit/pull/17
Re #11 
Changes:
* Separates some cache-related flags into import and export counterparts:
* `--use-inline-cache` - whether to attempt to import inline cache
* `--save-inline-cache` - whether to save inline cache in output image
* `--cache-from` - explicitly import cache from a docker tag (multiple can be specified by repeating the flag)
* `--cache-to` - save full (max-mode) cache to a specified docker tag (meant only for cache)
* Allows the user to push images without outputting them to the local Docker (this is now faster for CI use-cases). So `--no-output` + `--push` is now perfectly valid.
* Expands on the CI mode (`--ci`) from a previous PR. CI mode is now equivalent to using the flags
```
--use-inline-cache --save-inline-cache …
```
> Optimize inline cache for CI mode

- buildkitd/Earthfile
- buildkitd/entrypoint.sh
Display both the earthly git sha1 and buildkit image used for the release; this is to make debugging issues easier.
> Display startup message in earthly-buildkit

- Earthfile
- builder/builder.go
- builder/solver.go
- cmd/earth/main.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- earthfile2llb/listener.go
- llbutil/fakedep.go
- states/states.go
Re #11
Changes:
* Merge back `--from-cache` and `--to-cache` into a single flag: `--remote-cache`. The behavior is now such that pushing cache only happens if `--push` is used.
* Bring back fakedep from the dead. But improve its performance. There is a flag to disable it in case we suspect that it's causing performance issues. Fakedep allows us to tie back dangling layers not associated with any image (and therefore would otherwise require their own image which we would not export). This makes it possible for targets invoked with `BUILD` to still be associated with the inline cache of another image. eg
```Dockerfile
FROM ...
BUILD +something-else
SAVE IMAGE --push docker:tag
```
In this example, `+something-else` is now covered by the cache of `docker:tag`, assuming none of its inputs …
> Further tweaks to remote cache abilities

- builder/builder.go
- builder/solver_monitor.go
- go.mod
* If the progress related to a vertex and an update ID that we have just printed, go up one line and overwrite it
* In such cases, also don't delay the update (unless ANSI escape sequences are not supported)
* Use visual progress bars for these updates
The progress bar uses some special unicode characters for sub-character progress. Here are the different states of the progress bar:
> Show status progress updates as progress bars

- .buildkite/blog-examples-test.sh
- .buildkite/brew-upgrade-test.sh
- .buildkite/tests.sh
- .circleci/config.yml
- .github/workflows/ci.yml
- CONTRIBUTING.md
- Earthfile
- autocomplete/complete.go
- autocomplete/complete_test.go
- buildcontext/excludes.go
- builder/builder.go
- cmd/earthly/main.go
- docker2earth/convert.go
- domain/artifact.go
- domain/target.go
- earthfile2llb/converter.go
- earthfile2llb/lexer.go
- earthfile2llb/listener.go
- earthly
- earthly-buildkitd-wrapper.sh
- examples/ecr-push/README.md
- examples/tests/Earthfile
- examples/tests/autocompletion/Earthfile
- examples/tests/docker2earth/test.sh
- release/Earthfile
- scripts/install-all-versions.sh
- scripts/tests/private-repo.sh
- scripts/tests/self-hosted-private-repo.sh
- states/states.go
- when a user installs via brew, they type `brew install earthly`, so one would expect to find a command named `earthly` rather than `earth`
- this git repo is located at `github.com/earthly/earthly.git` and not `github.com/earthly/earth.git`
- Googling for `earthly` manages to find our documentation, where as the search-space for `earth` is much more crowded
- `earth` easily tabs completes into `earthly`
> Renaming earth to earthly

- Earthfile
- cmd/earthly/main.go
- termutil/is_tty.go
- if earth exists, delete it and symlink it to new earthly install
> Symlink earth to earthly during bootstrap

- .buildkite/windows.yml
- .circleci/config.yml
- .github/workflows/ci.yml
- go.sum
- rather than rely on GIT_INSTEAD_OF to switch from ssh to https, we can
make use of earthly's auto mode which detects to use https when no keys
are present.
> Remove GIT_INSTEAD_OF now that auto mode is supported

- cmd/earthly/main.go
Earthly CLI  help is really wide and wraps strangely.  Here I am trying to wrap it at around 150 characters wide.  This is still kind of wide but does look better.  
Before:
After:
Also, these are the first lines of go I have written so I might need some guidance.
> Idea: Wrap CLI help

- docs/earthly-command/earthly-command.md
- docs/earthly-config/earthly-config.md
- docs/examples/circle-integration.md
- docs/examples/codebuild-integration.md
- docs/examples/gh-actions-integration.md
- docs/guides/auth.md
- docs/guides/ci-integration.md
- git-instead-of is no longer required for CI setups
- document experimental setup of self-hosted git repos
> Update auth guide to remove git-instead-of

- cmd/earthly/main.go
- reorders commands to be consistent with our docs.
- rename `<org>` to `<path>` under permission management since it can be
used to grant fine-tuned permissions and not just permissions at the
top-level of the org.
> Reorder command help ordering

- Earthfile
- buildcontext/git.go
- buildcontext/local.go
- earthfile2llb/converter.go
- earthfile2llb/listener.go
- earthfile2llb/withdockerrun.go
- llbutil/copyop.go
These changes, together with https://github.com/moby/buildkit/pull/1905 allow us to use maximum cache.
Changes:
* Use `root:root` in misc copy operations and destination user in main copy operations. (Escape hatch: `COPY --keep-own` to keep source owner).
* Set a constant time for the creation time of all files. The constant is the day Earthly was first released ;-). (Escape hatch: `COPY --keep-ts` to keep timestamps).
* https://github.com/moby/buildkit/pull/1905 makes file modes consistent between `llb.Local` and `llb.Git`
> Flatten out file metadata as much as possible

- earthly
- display script commands when running `./earthly --help`:
```
$ ./earthly --help
------------------- earthly pre-release script help -------------------
NAME:
earthly - A wraper around the earthly binary that checks for updates once an hour
COMMANDS:
reset     Removes prerelease binary and associated docker containers
upgrade   Forces a new check for the latest version
---------------------------- earthly help -----------------------------
NAME:
earthly - A build automation tool for the container era
USAGE:
earth [options] <target-ref>
earth [options] --image <target-ref>
```
> Include pre-release script help

- analytics/analytics.go
- containerized CI systems will always generate a new install-ID, we
should ignore them.
> Ignore installID on CI

- .github/workflows/ci.yml
- earthfile2llb/converter.go
- earthfile2llb/runmount.go
- examples/tests/Earthfile
- examples/tests/secrets.earth
- scripts/tests/secrets-integration.sh
- variables/util.go
- variables/util_test.go
Implements a new `--secret-file` flag within the RUN command.
```
RUN --secret-file=/root/this-my-secret=+secrets/SECRET1 cat /root/this-my-secret)
```
> Support for mounting secrets as files

- .github/workflows/ci.yml
- Earthfile
- buildcontext/git.go
- builder/builder.go
- builder/docker.go
- builder/solver.go
- buildkitd/Earthfile
- cmd/earthly/main.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- earthfile2llb/withdockerrun.go
- examples/multiplatform/Earthfile
- go.sum
- llbutil/docker_test.go
- llbutil/dockertag.go
- llbutil/platform.go
- llbutil/statetoref.go
- release/Earthfile
- states/dedup/targetinput.go
- states/states.go
- variables/collection.go
- variables/collection_test.go
Re #536 
Depends on https://github.com/earthly/buildkit/pull/21
* If a build does not use any `--platform` flag, it should behave exactly the same as before
* Allows pushes with manifest lists (multiarch images)
* Locally multi-platform images are produced with separate tag suffixes
* Add an example that is also used as an integration test
* Propagate `--platform` setting similarly to build args (they do not cross Earthfile boundaries)
* Detect if there is a contradiction of platforms (eg call with `--platform linux/amd64` but it contains a `FROM --platform linux/arm/v7` command)
* Add arm64 earthly binary
> Support for multi-platform outputs

- analytics/analytics.go
Previous logic was never reaching `installID = fmt.Sprintf("%x", sha256.Sum256([]byte(ciName+repoHash)))` as `ciName` had to be `"false"`, but `ci` had to be `true`.
Or perhaps I'm misunderstanding this - not sure how this has been apparently working so far.
> Fix tracking of CI user IDs

- Earthfile
- builder/builder.go
- release/Earthfile
* Build buildkit image for both amd64 and arm64
* Don't install shellcheck unless running `+lint-scripts` (shellcheck not available on arm)
* Fix a bug where platform suffixes were being pushed but shouldn't have
> Support for Apple M1

- .buildkite/macOS.yml
- .gitignore
- buildcontext/git.go
- builder/builder.go
- earthfile2llb/converter.go
- earthfile2llb/listener.go
- examples/tests/Earthfile
- examples/tests/if-exists.earth
- llbutil/copyop.go
- states/states.go
It was super easy to add it to `COPY`; and seemed applicable because you can COPY artifacts from upstream targets (see the `CopyArtifact` function...)
I chose to implement it by exploiting the "Allow Empty Wildcard" option for the LLB copy; as that logic is exactly the logic I also want to follow; just with an exact file name. This changes the filename into a wildcard-type string (that is sufficiently constrained enough to only match the file we want), and then enables the "Allow Empty Wildcard" behavior for the optional artifacts.
Admittedly a hack; but it was certainly less invasive than evaluating where we were at in a `WITH DOCKER` style setup for each artifact, and some `COPY`s. 
Resolves #588.
> Add --if-exists to COPY and SAVE ARTIFACT

- .github/workflows/ci.yml
- Earthfile
- release/Earthfile
* Seems that darwin-arm64 binary cannot be built yet (https://github.com/golang/go/issues/40698#issuecomment-680134833). Though the amd64 one should work well enough via rosetta 2.
* We cannot support arm/v5 and arm/v6 as we cannot build buildkit images for them (No base images available). This should be fine generally, as these are older architectures superseded by arm/v7 and arm64.
> Fix multiarch build

- analytics/analytics.go
- previous call to "git config --get remote.origin.url ended with a
newline; ensure this is removed to make sure consistent repo name is
used between command-line usage and CI usage.
> trim whitespace to ensure consistent hashing of git repos

- docs/earthfile/earthfile.md
- docs/earthly-command/earthly-command.md
- these features were released with earthly v0.4.4, but were never
documented.
> Document the --secret-file and type=secret mount

- Earthfile
- buildkitd/Earthfile
- earthly
- release/Earthfile
* Ability to compile for darwin arm64 (requires Go 1.16 beta; everything else will use Go 1.15)
* Add darwin arm64 to the release list
* Force `+lint-scripts` to run on amd64 since shellcheck is not available on arm
* `+earthly` attempts to autodetect your current platform
> A series of fixes to better support Apple M1

- Earthfile
- builder/solver_monitor.go
- buildkitd/entrypoint.sh
Re #722 
* Print any build arg or platform overrides on every command
* Print detected architecture on buildkit startup
```
Detected container architecture is x86_64
```
* Other minor adjustments
The output is now a bit more verbose when using `--platform` or `--build-arg`, however, this should improve readability when trying to follow the logs.
Random screenshot of a particularly verbose output:
> Print overrides on every command

- builder/solver_monitor_test.go
- these tests were written to better understand how the vertex prefix parser works
> Add tests for solver monitor's parser method

- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- earthfile2llb/listener.go
- earthfile2llb/withdockerrun.go
- examples/tests/build-arg.earth
- examples/tests/remote-cache/Earthfile
- examples/tests/remote-cache/test.sh
- states/dedup/targetinput.go
- variables/collection.go
- variables/variables.go
Note to reviewer: it's easiest to review this commit-by-commit.
This enables the use of variable build args in non-RUN expressions. For example, something like the following is now possible:
```
ARG src=$(cat ./what-to-copy.txt)
COPY $src ./
```
It also simplifies the TargetInput-related logic as we don't have to account for the provenience tree of build args.
> Turn non-constant build args into constant ones on the spot

- analytics/analytics.go
- buildkitd/buildkitd.go
- cmd/earthly/main.go
- earthly
* Make `./earthly` pull the right buildkit image
* `docker run` the right platform for buildkit
* Include platform in version output
* Track platform in analytics
With this, `earthly -P +test` works on arm64, including `WITH DOCKER`. However, `earthly -P --platform=linux/amd64 +test` does not work when ran on an M1 mac, because `WITH DOCKER` qemu emulation is not functional yet.
> Improvements for Apple Silicon

- earthfile2llb/listener.go
- earthfile2llb/listener_test.go
- examples/tests/dind-auto-install/Earthfile
- examples/tests/with-docker-compose/Earthfile
- examples/tests/with-docker/Earthfile
Calls like these
```
BUILD --build-arg VAR=1 +target
BUILD --build-arg VAR=2 +target
```
can now be replaced with this
```
BUILD \
--build-arg VAR=1 \
--build-arg VAR=2 \
+target
```
Or calls like these:
```
BUILD --build-arg BASE_IMAGE=ubuntu:16.04 --build-arg NODE_VERSION=14 +test
BUILD --build-arg BASE_IMAGE=ubuntu:16.04 --build-arg NODE_VERSION=15 +test
BUILD --build-arg BASE_IMAGE=ubuntu:16.04 --build-arg NODE_VERSION=16 +test
BUILD --build-arg BASE_IMAGE=ubuntu:18.04 --build-arg NODE_VERSION=14 +test
BUILD --build-arg BASE_IMAGE=ubuntu:18.04 --build-arg NODE_VERSION=15 +test
BUILD --build-arg BASE_IMAGE=ubuntu:18.04 --build-arg NODE_VERSION=16 +test
BUILD --build-arg BASE_IMAGE=ubuntu:20.04 --build-arg NODE_VERSION=14 +test
BUILD --build-arg BASE_IMAGE=ubuntu:20.04 --build-arg …
```
> Support for build arg matrix

- .github/workflows/ci.yml
- earthfile2llb/converter.go
- earthfile2llb/listener.go
- examples/tests/local/Earthfile
- go.mod
This is still very much so a draft and is not ready for review.
This requires https://github.com/earthly/buildkit/pull/26 be merged first (then we can backout my buildkit/Earthfile change)
> Support for copying artifacts from LOCALLY target to containerized target

- examples/tests/local/Earthfile
- this will allow us to see the output even if it fails
> Replace grep with perl

- builder/builder_error.go
- builder/solver.go
- builder/solver_monitor.go
- cmd/earthly/main.go
Here's an example of the error-fix hint:
```
$ ./build/linux/amd64/earthly -i --platform arm64 github.com/earthly/hello-world:main+hello
buildkitd | Newer image available. Restarting buildkit daemon...
buildkitd | ...Done
busybox:1.32.0 | --> Load metadata linux/arm64
g/e/hello-world:main+base | platform=linux/arm64
g/e/hello-world:main+base | --> FROM busybox:1.32.0
g/e/hello-world:main+base | [██████████] resolve docker.io/library/busybox:1.32.0@sha256:bde48e1751173b709090c2539fdf12d6ba64e88ec7a4301591227ce925f3c678 ... 100%
g/e/hello-world:main+hello | platform=linux/arm64
g/e/hello-world:main+hello | --> RUN echo 'Hello, world!'
g/e/hello-world:main+hello | .buildkit_qemu_emulator: /usr/bin/earth_debugger: …
```
> Display hint for platform related errors

- .github/workflows/ci.yml
- Earthfile
- scripts/tests/export.sh
- scripts/tests/private-repo.sh
- scripts/tests/secrets-integration.sh
- scripts/tests/self-hosted-private-repo.sh
This test is for validating the exporting from earthly to docker works.
It's written in a way that a user can run `./scripts/tests/export.sh` locally to run the test, or allow CI to invoke the script.
> test earthly exports work

- Earthfile
- earthfile2llb/converter.go
- examples/tests/Earthfile
- examples/tests/build-arg-repeat.earth
- release/Earthfile
This was causing our earthly-linux-arm64 binary to be the same as earthly-darwin-arm64.
Fixes https://github.com/earthly/earthly/issues/789
> Fix for build arg issue when not overriding default value

- scripts/tests/export.sh
- test3 was never written in a way that was work (and was never executed
previously due to a bug in the earthly buildkit exporter which caused
test 1 and 2 to fail).
> Fix export test 3

- buildkitd/buildkitd.go
- buildkitd/settings.go
- cmd/earthly/main.go
- config/config.go
- earthfile2llb/converter.go
This is no longer used AFAICT.
Fixes https://github.com/earthly/earthly/issues/791
> Get rid of old RunPath config and mount

- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- llbutil/platform.go
* Don't use empty string for network in targetinput platform.
> Correctly detect when default platform matches specific platform for dedup reasons

- builder/builder.go
The implicit exclude of `.tmp-earthly-out` was not working because the temp dir contained some numbers at the end and the exclude pattern was simply `.tmp-earthly-out/`. With this PR, the temp dirs are now stored under `./.tmp-earthly-out/tmpXXXXXX` instead of `./.tmp-earthly-outXXXXXX`.
The wrapping `.tmp-earthly-out` dir is removed only if it's empty.
It may be possible in the future to also remove any old leftover temp dirs within `.tmp-earthly-out` using some file lock-based logic to detect whether the temp dir is still being used by some process (a parallel earthly run).
> Correctly exclude .tmp-earthly-out

- buildkitd/Earthfile
- earthfile2llb/converter.go
- earthfile2llb/interpreter.go
- examples/tests/local/Earthfile
- go.mod
- go.sum
implements copying artifacts from containerized targets to `LOCALLY` targets. This functionality is different from `SAVE ARTIFACT AS LOCAL`, in that it is performed during the build rather than at the end of the build during the export stage.
This depends on https://github.com/earthly/buildkit/pull/30
> Copy to localhost during solve

- Earthfile
- examples/cutoff-optimization/Earthfile
- examples/cutoff-optimization/src/main.cpp
This example demonstrates not repeating unnecessary subsequent steps after file changes.  This is called 'Early Cut Off Optimization' in the 'Build systems a la cart' paper.  
I also believe this is the behavior being referenced in #786 .
> Add early cutoff cache optimization example

- Earthfile
- ast/parser/Earthfile
- ast/parser/earth_lexer.go
- ast/parser/earth_parser.go
- ast/parser/earthparser_base_listener.go
- ast/parser/earthparser_listener.go
- builder/builder.go
- earthfile2llb/converter.go
- llbutil/platform.go
Turns out detecting a contradiction isn't great in some specific situations. Like the following, which should be perfectly valid:
```
build:
FROM --platform=platform1 ...
COPY +other/... ./...
other:
FROM --platform=platform2
...
```
Also, update antlr to `4.9.1`.
> Allow platform contradictions

- .github/workflows/ci.yml
- builder/builder.go
- cmd/earthly/main.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
Small prereq that can standalone as I add in support for `RUN --interactive`
Still needs an integration test though
> Initial implementation for strict flag

- cmd/earthly/main.go
- this was missed when we renamed the earth command to earthly
> rename zsh completion function _earth to _earthly

- config/config.go
Looser permissions, plus create directory separately.
> Create config path if missing

- cmd/earthly/main.go
- config/config.go
Adds help text for main command, and for keys (at the expense of being able to set a value to `--help`. 
Adds validation to ensure you can set the key to that value.
> Add more validation and help to config

- .buildkite/blog-examples.yml
- .buildkite/macOS-brew-m1.yml
- .buildkite/macOS-brew.yml
- .buildkite/macOS-m1.yml
- .buildkite/macOS.yml
- .buildkite/windows.yml
I came up with 55; so that brew install test pipelines alone cannot back eachother up.
> Buildkite Timeouts

- Earthfile
- analytics/analytics.go
- examples/tests/Earthfile
- examples/tests/autocompletion/Earthfile
- examples/tests/cloud-push-pull/Earthfile
- examples/tests/registry-certs/Earthfile
- examples/tests/remote-cache/Earthfile
* Disable analytics for our earthly image-based integration tests. This is not strictly necessary as we anyway perform filtering on the other side. This data is never useful, however, and it's better if it's not there so that we don't accidentally forget to filter it out.
* Treat the earthly docker image as CI for analytics purposes, just in case anyone is using the image extensively. It's not well supported - we should have some way to know if it has wide use.
* Add detection for GitLab CI.
> Analytics improvements

- Earthfile
- builder/builder.go
- builder/solver_monitor.go
- conslogging/conslogging.go
Here's what this looks like in practice (note the `ongoing | ... ` lines)
These get updated as time passes, if the terminal supports ansi. If not (usually in CI), the updates happen more rarely and are printed on new lines.
Also in this PR, a somewhat unrelated change: the artifacts and image targets are colored with the same color used for the target:
> Provide updates about what is ongoing if there is no output

- builder/builder.go
Before:
(Notice the `index-0` `index-1` in the artifact path)
After:
> Fix leaking index-X dir names in artifact printout

- contrib/earthfile-syntax-highlighting/README.md
- contrib/earthfile-syntax-highlighting/syntaxes/earthfile.tmLanguage.json
Some screenshots
Semantic type of target declarations has also been updated - so it has a different color now (matches the target references):
> Syntax highlighting for command references and command definitions

- examples/tests/local/Earthfile
- disable some flaky tests until we get them sorted out.
> LOCALLY tests are failing in GHA

- examples/tests/local/Earthfile
some of these tests are still flaky; let's disable them all and then I will work on re-enabling them once we sort out the underlying issue.
> disable all locally tests

- ast/parser/Earthfile
- the generate-railroad-diagrams target will save two html files locally
which can be used to visualize the lexer and parser antlr code.
here's an example of a screenshot of a generated html page containing the railroad diagram.
> generate railroad diagrams for lexer and parser

- examples/tests/local/Earthfile
- the dockerhub cache was in a bad state due to a locally-specific
snapshotting bug that didn't correctly walk the snapshot files which
produced conflicting hashes; the buggy code was never merged into
main; however the cache persisted. To rebuild the cache, I
1) added a `--no-cache` option to the earthly calls under the CI,
2) triggered a new PR build, then 3) removed the --no-cache option.
> re-enable locally-tests

- earthfile2llb/converter.go
- earthfile2llb/interpreter.go
- variables/collection.go
This is s.t. stuff like this doesn't happen: https://github.com/earthly/lib/blob/main/Earthfile#L4 (we can instead just say `+install-dind-script`).
> Refs in UDCs should be relative to where the UDC is defined

- .buildkite/blog-examples.yml
It fails on JVM stuff, see more recent builds segfaulting on `sbt`.
> Do not run examples builds on the M1

- ast/validator.go
- examples/tests/Earthfile
- examples/tests/reserved-target-names.earth
- adds a check for invalid target names that conflict with reserved
target names
```
FROM alpine:latest
base:
RUN echo foo > /data
foo:
FROM +base
RUN ls /data
```
will now produce the following error:
```
$ ./build/linux/amd64/earthly ~/broken/base+foo
buildkitd | Starting buildkit daemon as a docker container (earthly-buildkitd)...
buildkitd | ...Done
Error: resolve build context for target /home/alex/broken/base+foo: 1 validation issues.
- /home/alex/broken/base/Earthfile line 4:0 invalid target "base": base is a reserved target name
```
> Check for reserved target names (e.g. base)

- buildcontext/gitlookup.go
- scripts/tests/self-hosted-private-repo.sh
- fix our handling of non-standard (e.g. self-hosted) git repos; this bug only affected accessing subdirectories of self-hosted git repos.
- extend our self hosted private repo test to reference commands that are stored remotely but from a local Earthfile
> fix mapping of custom projects to self-hosted git repos

- analytics/analytics.go
- buildkitd/buildkitd.go
- cmd/earthly/main.go
* Nicer Buildkit pull message
* Perform buildkit pull and start as part of bootstrap
* Don't classify detached head as CI due to possible false positives
> Earthly installation improvements

- cmd/debugger/main.go
- go.mod
- the debugger should produce an .ash_history file incase the user
enters ash instead of bash.
> Write to ash_history too

- .github/workflows/ci.yml
- earthfile2llb/converter.go
- earthfile2llb/interpreter.go
- earthfile2llb/withdockerrunlocal.go
- examples/tests/local/Earthfile
- examples/tests/local/with-docker-compose-local/Earthfile
- examples/tests/local/with-docker-compose-local/docker-compose.yml
- examples/tests/local/with-docker-compose-local/fetch.sh
the code needs some loving, but here's an initial not-ready-for-review draft of running with docker locally.
> With docker locally

- debugger/terminal/terminal_other.go
- go.mod
- go.sum
- rather than print to stderr when the shell repeater exits, use log
instead.
> log interactive shell repeater messages

- builder/builder.go
- cmd/earthly/main.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- earthfile2llb/interpreter.go
- earthfile2llb/withdockerrun.go
- earthfile2llb/withdockerrunlocal.go
- examples/tests/Earthfile
- examples/tests/allow-privileged.earth
- states/dedup/targetinput.go
- states/states.go
- states/visited.go
- We should avoid running local and priviledged commands that are
referenced from remote Earthfiles.
- We will design a way to configure trusted repos in a follow up PR.
> Disallow privileged and local execution from remote Earthfiles

- earthfile2llb/flags.go
- earthfile2llb/interpreter.go
- go.mod
- go.sum
- move interpreter flags to separate file for clearer visibility of flags
- switch from go's flag library to go-flags which supports both short and long names
> move interpreter flags to separate file

- Earthfile
- analytics/analytics.go
- cliutil/earthlydir.go
- cmd/earthly/main.go
- secretsclient/client.go
~Uses the magical incantation `eval echo ~$SUDO_USER` to figure out the sudo user's home dir and use that dir for `install_id`.~
TIL https://golang.org/pkg/os/user/#Lookup
> `sudo earthly bootstrap` should use the same `install_id` as the calling user

- .github/workflows/ci.yml
- .gitignore
- buildkitd/buildkitd.go
- buildkitd/settings.go
- cmd/earthly/main.go
- release/README.md
Pull in more details that have leaked into the main `earthly` command. Additionally, use the same retry logic when a provided buildkit address is used.
> More Buildkit Cleaning

- .github/workflows/ci.yml
- scripts/tests/auth/Earthfile
- scripts/tests/auth/README.md
- includes a script that regenerates github action integration tests
for auth related tests that can't run via earthly in earthly.
> Include GHA workflow generation script for auth tests

- examples/tests/Earthfile
- util/llbutil/secrets.go
Previously if one referenced a secret which was not available, earthly
would fail and simply return "Error: not found"; this changes the
behavious to display which secret was not found.
For example, consider an Earthfile like:
foo:
FROM alpine:latest
RUN --secret password=+secrets/password env
If you invoke earthly +foo (without passing a value for the password secret), now it will display
an error such as:
Error: unable to lookup secret password: not found
Where as previously it just displayed:
Error: not found
> Display which secret was not found in error message

- .github/workflows/ci.yml
- analytics/analytics_test.go
- this is to prevent us from changing the hashing function
which would make it impossible to track repos
> Add test to make sure repo hash stays the same

- docs/earthly-command/earthly-command.md
I put the docs above `account` because its lesser used, and it was long enough so as to bury this command. It also felt like a more natural positioning?
> Add config docs.

- .github/workflows/ci.yml
- buildcontext/gitlookup.go
- scripts/tests/auth/test-hello-world-empty-netrc.sh
- fixes a panic that occurs when a ~/.netrc file exists but is either
empty, invalid, or doesn't contain login information for the host that
is being looked up.
> fix panic when netrc file exists but doesnt contain host

- release/Earthfile
- release/README.md
- release/apt-repo/Earthfile
- release/apt-repo/README.md
- release/apt-repo/test/Earthfile
- release/yum-repo/Earthfile
- release/yum-repo/README.md
- release/yum-repo/test/Earthfile
- expand the release process to release apt and yum repos.
- move the location to search for aws credentials to the user-namespace
of earthly secrets store.
> add apt and yum repo release to main release process

- autocomplete/complete.go
- cmd/earthly/main.go
- examples/tests/Earthfile
- util/cliutil/earthlydir.go
- util/fileutil/expand.go
- util/fileutil/homedir.go
- util/fileutil/homedirs.go
Typically the shell will expand paths such as `~/foo`; however when given
as an argument to `--secret-file secret=~/foo`, the shell did not expand
this path. This addresses this issue.
> expand secret-file path

- earthfile2llb/converter.go
- examples/tests/Earthfile
- examples/tests/cache-mount-arg.earth
- states/dedup/targetinput.go
* Cache mount ID now depends on a target input hash which does not include inactive variables
* Cache mount base image is now simply scratch (previously it was an empty host dir, but this seems unnecessary now)
Fixes https://github.com/earthly/earthly/issues/996
> Fix cache mount depending on inactive args

- Earthfile
- scripts/tests/auth/test-self-hosted.sh
- scripts/tests/secrets-integration.sh
Th M1 continues to fail in CI when it comes to Shellcheck. This should enable Shellcheck natively on the M1, eliminating the emulation layer as a source of problems.
This is finding some lint issues, but appears to make it further more consistently than before.
> Try using direct aarch64 shellcheck download?

- ast/version.go
- examples/tests/version/Earthfile
- examples/tests/version/single-line-with-comment.earth
fixes handling of comments directly after a VERSION without any line
continuations.
> Fix VERSION parser handling of comments

- cmd/earthly/main.go
- examples/tests/bootstrap/test-bootstrap.sh
- release/README.md
Add a section to hold all the one-time release items I am generating, and include a one-time item for updating `bootstrap` invocations on the website.
> One-time section, include docs update.

- examples/tests/Earthfile
- states/dedup/targetinput.go
- variables/builtin.go
- variables/builtin_test.go
Adds `EARTHLY_TARGET_PROJECT_NO_TAG` builtin arg, which is the canonical Earthly project ref minus the tag.
I've created a test in this repository: https://github.com/earthly/test-builtin-args/blob/main/subdir/Earthfile
Fixes https://github.com/earthly/earthly/issues/1005
> Add a variant for the Earthly target project without the tag

- examples/tests/Earthfile
- examples/tests/allow-privileged-import.earth
- examples/tests/allow-privileged.earth
- examples/tests/reject-privileged-import.earth
The remote repo used for testing has grown beyond priviledged tests,
The Earthfile from github.com/earthly/test-privileged has been copied to
github.com/earthly/test-remote/privileged. Once merged, we can remove
the old github.com/earthly/test-privileged repo.
> Reference renamed remote repo for tests

- analytics/analytics.go
- buildcontext/gitlookup.go
- buildkitd/buildkitd.go
- cmd/earthly/main.go
- secretsclient/client.go
- util/cliutil/earthlydir.go
Earthly attempts to find the config path under the $SUDO_USER's ~/.earthly path, otherwise if $SUDO_USER isn't set, then under $HOME/.earthly, then the users' home directory (for cases where the HOME env isn't set), then if all of those fail, "/etc". If any of these heuristics fail, errors will be silently ignored.
`GetEarthlyDir()` has been changed to always return a string, without any error as the heuristic will always fallback to `/etc`.
A new function: `GetOrCreateEarthlyDir()` has been created which will call `GetEarthlyDir()` and additionally create the path if it does not exist. This function will continue to return errors which occur during directory creation.
This PR additionally deduplicates some of the path look up code to ensure there's only one mechanism that constructs the …
> Ignore errors while detecting earthly home dir

- .github/workflows/ci.yml
- scripts/tests/interactive-debugger/Earthfile
- scripts/tests/interactive-debugger/test-interactive.py
Creates a new interactive debugger to test earthly presents an
interactive debugger which can execute a command. This test is different
from the examples/tests/interactive test in that it actually issues a
test via python's pexpect library, and verifies the command's output.
> Interactive debugger test that checks a command can be run

- cmd/debugger/main.go
- cmd/earthly/main.go
- conslogging/conslogging.go
- conslogging/conslogging_others.go
- conslogging/conslogging_windows.go
New Debugf and DebugBytes will print their messages only when
conslogging is running under verbose mode.
> Add verbose calls to conslogging

- cmd/shellrepeater/main.go
- debugger/server/server.go
- debugger/server/server_test.go
This creates a logger for the shell repeater with the app label set to
"shellrepeater" to make it easier to view shellrepeater logs vs buildkit
logs via:
docker logs earthly-buildkitd 2>&1 | grep shellrepeater
> Add debug logs to shell repeater

- cmd/earthly/main.go
- debugger/terminal/terminal_other.go
- debugger/terminal/terminal_windows.go
Since the debug terminal is called within earthly, it should use the
conslogger along with an "internal-term" prefix. The previous logrus
logger was no correctly logging debug messages due to
logrus.StandardLogger().Out = ioutil.Discard
being set (to prevent other imported libraries from logging).
> Use conslogging for logging debug term messages

- Earthfile
- cmd/debugger/main.go
- cmd/shellrepeater/main.go
- debugger/server/server.go
- debugger/server/server_test.go
- slog/context.go
- slog/logging.go
Structured logging should only be used by servers (e.g. shellrepeater),
and should not be used by the earthly command. This renames logging to
slog and gives a comment describing when to use slog.
> rename logging to slog (structured log)

- buildcontext/provider/provider.go
- examples/tests/Earthfile
display bytes as MB, kB, or B rather than just bytes.
> Humanize bytes in verbose logging

- release/apt-repo/Earthfile
- release/apt-repo/earthly.control
- release/apt-repo/postinst
- release/apt-repo/postrm
I tried to make use of `dh $@ --with bash-completion` in a rules file however I just couldn't get auto-completion to persist when I logged out and back in. Ultimately I figured we could stick with the approach that homebrew uses to have the earthly binary output the auto-completion contents.
> Auto install bash completion file on debian

- release/yum-repo/Earthfile
- release/yum-repo/earthly.spec
Post install script to enable bash completion and earthly bootstrapping.
> post install script for rpms

- .github/workflows/ci.yml
I'll add a ref to our docs there so we have something on the public repositories. Its not quite working, and the dev loop on debugging that isn't worth the effort right now to get a release out.
> Remove auto-update DockerHub docs.

- autocomplete/complete.go
The --help and --version flags are added automatically to urfav, and aren't
included in the flags we define for earthly; therefore we must
explicitly add them.
> Include version and help flags in autocomplete

- .github/workflows/ci.yml
Now that permissions have been sorted, we can re-add this. I have tested the action locally and successfully updated the descriptions.
> Re-add DockerHub docs to the CI process.

- cmd/earthly/main.go
Users can disable analytics by setting the env variable
`EARTHLY_DISABLE_ANALYTICS` to `1`, `true`, or `TRUE`.
Users can also continue to disable analytics via the config setting
under ~/.earthly/config.yml; which can be done by running:
earthly config global.disable_analtyics true
> Option to disable analytics via env variable

- earthfile2llb/interpreter.go
Should allow `COPY +target/file .` on Windows.
> Adjust destination with comment when using artifact copy form

- buildkitd/buildkitd.go
verbose-print earthly-buildkit details to help debug container restart
issues.
> print earthly-buildkit image name and settings hash

- Earthfile
- buildkitd/Earthfile
When version is not given, it defaults to the current git branch.
This causes a problem if someone checks out a previous branch of
earthly, modifies some code (while debugging a problem), and runs
earthly +earthly. This will overwrite the released buildkit image.
This PR adds a "dev-" prefix the buildkit when earthly is built
directly.
When performing a release via ./release+release, the VERSION tag is set
to whatever value is passed by RELEASE_TAG, (thus overridding the
default value (which includes the dev- prefix)).
> prefix buildkit image with dev- when building +earthly

- domain/reference.go
- examples/tests/Earthfile
- examples/tests/absolute-reference-with-relative.earth
Fixes a bug where absolutely referencing an earthfile that contains a
relative import fails.
> bugfix: absolute referenced target's relative import fails

- docs/earthfile/earthfile.md
provide an example of how to use LOCALLY, and describe how the working
directory is set.
> expand LOCALLY docs

- cmd/earthly/main.go
This follows the suggestion of https://consoledonottrack.com/
to adopt a single environment variable to disable tracking users.
Without this environment variable set, earthly will collect
anonymized data as discussed under https://docs.earthly.dev/docs/misc/data-collection
> Disable analytics collection when DO_NOT_TRACK is set

- buildkitd/buildkitd.go
- buildkitd/settings.go
- cmd/earthly/main.go
This allows a user to switch between volume caches, which increases the
speed of testing operations where one needs to reset the volume cache.
> Allow user to override container and volume names

- release/Earthfile
Since earthly is BSL, we had to move to our own tap under github.com/earthly/homebrew-earthly;
earthly was disabled in homebrew-core https://github.com/Homebrew/homebrew-core/pull/80842
> update homebrew release to use github.com/earthly/homebrew-earthly

- buildkitd/buildkitd.go
- cmd/earthly/main.go
- go.mod
- go.sum
expand crash logs to include docker version, and OS version (and
distribution).
> Include docker version in crash logs

- autocomplete/complete.go
- autocomplete/complete_test.go
- cmd/earthly/main.go
Autocomplete hidden flags when using any version that starts with a
"dev-" prefix (which gets added to all non-release builds built via the
+earthly target), or when the env variable EARTHLY_AUTOCOMPLETE_HIDDEN is set to "1"
> Autocomplete hidden flags on dev versions

- .github/workflows/ci.yml
- buildcontext/git.go
- buildcontext/local.go
- buildcontext/resolver.go
- builder/builder.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- earthfile2llb/local_state_cache.go
- earthly-entrypoint.sh
- examples/tests/Earthfile
- examples/tests/copy-verbose.earth
- util/inodeutil/inode_other.go
- util/inodeutil/inode_windows.go
- util/llbutil/llbfactory/llb_factory.go
This sets the IncludePattern on local sources. Without this, the entire
directory is copied.
> Set the IncludePattern on Local Source

- cmd/earthly/main.go
- earthly
Forces the --referenced-save-only flag to be enabled for all VERSION
commands.
Renames EARTHLY_FEATURE_FLAG_OVERRIDES to EARTHLY_VERSION_FLAG_OVERRIDES
to reflect that this env is *only* for overriding feature flags that are
defined within a VERSION command context, and is not used to change
global features.
> enable referenced-save-only mode for ./earthly

- release/Earthfile
- release/README.md
fixes issue where PR was from `griswoldthecat/homebrew-earthly` was
opened against `griswoldthecat/homebrew-earthly` rather than `earthly/homebrew-earthly`
Update instructions to document how to apply the `pr-pull` label.
This label must be applied manually once the test checks complete and is
equivalent to approving the PR. For this reason this label can not be
automatically applied.
> fix homebrew release process and instructions

- buildcontext/gitlookup.go
https://github.com/earthly/earthly/pull/1111 accidentally swapped http for https, changing back.
> bugfix: insecure check was checking for https rather than http

- earthfile2llb/interpreter.go
- examples/tests/Earthfile
- examples/tests/true-false-flag-invalid.earth
- examples/tests/true-false-flag.earth
- go.mod
- go.sum
- util/flagutil/parse.go
This is to allow passing --flag=$ARG; where $ARG is set to true/false elsewhere.
This implements #1109
This includes [some changes](https://github.com/alexcb/go-flags/compare/master...alexcb:argument-modifier?expand=1) to the flags library to support a flag value modifier function.
> Allow boolean flags to be passed with option value

- examples/tests/Earthfile
- examples/tests/true-false-flag.earth
The use of the --no-cache flag for this test was producing inconsistent results on cases where the cache was garbage collected between runs which led to a race condition. Instead use both --privileged and --no-cache to have a consistent result we can use to test.
> use --privileged flag instead of --no-cache for bool flag value test

- examples/tests/Earthfile
This test has still failed intermittently on GHA; cat the output so we
have more information if it happens again.
> cat ouput before running true-false-flag test

- Earthfile
- cmd/earthly/main.go
- examples/tests/autocompletion/Earthfile
When 61cc32c55c7bd8578e57b31aed963715eecd473a was introduced, the
integration test tag should have also have been updated to include the
"dev-" prefix.
Without this, whenever ./build/linux/amd64/earthly
./example/tests+some-test is run, it will overwrite ./build/linux/amd64/earthly
with a new version which compiles a new version of earthly without the
"dev-" version prefix.
> integration test was setting incorrect tag

- buildcontext/excludes.go
Issue:
https://github.com/earthly/earthly/issues/1029
What?:
- Allow for the ignore file `.earthignore` to be incorporated/used as `.earthlyignore`.
- If both exist then return an error
How:
- Check both the possible filenames to see if they both exist
- If both Exists then return error and implicit exclusion
- If only one exists then treat it as the ignore file
- If neither exist then return just implicit exlusion (as was behaviour before)
Acceptance:
- `.earthlyignore` files can be used in the place of `.earthignore`files
-  If both exist then an error is thrown or registered
Notes:
- Not sure that I threw the error correctly - Maybe if both exists it should be a hard stop
- I am sure the code could be more consise and cleaner
> Incoorporating .earthlyignore - Issue #1029

- buildcontext/excludes.go
change constants to non-exported, as they aren't used anywhere else and
were currentlying causing a lint error as one wasn't documented.
> change constants to non-exported

- earthfile2llb/converter.go
- earthfile2llb/interpreter.go
- earthfile2llb/withdockerrun.go
- earthfile2llb/withdockerrunlocal.go
Currently we only need to know if the command being passed is "FROM"; however, in a future PR the prepBuildTarget() method will have to include this check:
opt.DoSaves = (cmdT == buildCmd && c.opt.DoSaves)
> change isFrom to pass command name

- .github/workflows/ci.yml
- builder/builder.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- examples/tests/Earthfile
- examples/tests/save-artifact-legacy.earth
- examples/tests/save-artifact-selective-remote.earth
- examples/tests/save-artifact-selective.earth
- examples/tests/save-images/new-behaviour-remote/Earthfile
- examples/tests/save-images/new-behaviour/Earthfile
- examples/tests/save-images/old-behaviour-build/Earthfile
- examples/tests/save-images/old-behaviour-copy/Earthfile
- examples/tests/save-images/old-behaviour-from/Earthfile
- examples/tests/save-images/old-behaviour-remote/Earthfile
- examples/tests/save-images/test.sh
Re https://github.com/earthly/earthly/issues/896
Artifacts will only be saved locally when their target is directly
referenced, or referenced by a BUILD.
This will cause targets that are referenced from a FROM, or COPY from
*not* saving artifacts as a side-effect.
> Only save artifacts when they are directly referenced

- Earthfile
- earthfile2llb/converter.go
- earthfile2llb/flags.go
- earthfile2llb/interpreter.go
- earthfile2llb/shell.go
- earthfile2llb/withdockerrun.go
- examples/tests/Earthfile
- examples/tests/for.earth
- features/features.go
- variables/collection.go
- variables/scope.go
Part of https://github.com/earthly/earthly/issues/779
> Implement `FOR ... IN ...`

- Earthfile
- release/Earthfile
Main branch build is failing due to this.
The base image `docker:dind` is no longer released for `linux/arm/v7`. It seems that this issue is the root cause: https://github.com/docker-library/docker/issues/260
> Remove dind support for arm/v7

- .github/workflows/ci.yml
On pushing to main, we run a `--push`, which requires the service account to be logged in. Add back the login in just these two cases.
> Add login so we can push examples on merge to main

- .github/workflows/ci.yml
Missed this because it doesn't run on branches, and also doesn't run when the examples failed on the main branch. Upon examination it also needs to login to push prerelease images.
> Add a login to the prerelease `--push`.

- .buildkite/tests.sh
- .github/workflows/ci.yml
This used to be flaky in the past but seems to be fine now.
> Enable conversion parallelism in all our CIs

- states/dedup/targetinput.go
- util/gitutil/detectgit.go
- variables/builtin.go
`EARTHLY_SOURCE_DATE_EPOCH` will be set to the timestamp of the last git commit. If that is not available then it defaults to the string `0`.
This ensures that there is always a reproducible timestamp to use, either the UNIX epoch itself, or the UNIX timestamp of the last git commit.
This PR also restores `EARTHLY_GIT_COMMIT_TIMESTAMP` to the same behaviour as other `EARTHLY_GIT_` args that return an empty string when the value is unavailable.
Background: https://reproducible-builds.org/docs/source-date-epoch/
> Add EARTHLY_SOURCE_DATE_EPOCH to support reproducible builds

- docs/earthfile/builtin-args.md
Documentation for `EARTHLY_SOURCE_DATE_EPOCH` - goes with PR #1137
> Add docs for EARTHLY_SOURCE_DATE_EPOCH

- .github/workflows/ci.yml
- earthly
feature flip --use-copy-include-patterns in ci and ./earthly script.
> enable use-copy-include-patterns in ci and ./earthly

- ast/tests/if-exists.ast.json
- earthfile2llb/converter.go
- earthfile2llb/interpreter.go
- examples/tests/Earthfile
- examples/tests/if-exists.earth
extend --if-exists to support the clasic COPY command for copying files
from the local host; if the file doesn't exist, the copy doesn't execute
and earthly continues to the next command.
> Extend COPY --if-exists to classical COPY

- earthfile2llb/converter.go
- earthfile2llb/flags.go
- earthfile2llb/interpreter.go
- examples/tests/Earthfile
- examples/tests/save-artifact-dont-overwrite.earth
- examples/tests/save-artifact-dot.earth
- examples/tests/save-artifact-overwrite.earth
- features/features.go
Currently if a user specifies
SAVE ARTIFACT some-file AS LOCAL .
This error occurs:
$ ./earthly ~/broken/save-dot+sd
alpine | --> Load metadata linux/amd64
/h/a/b/save-dot+sd | --> FROM alpine
/h/a/b/save-dot+sd | [██████████] resolve docker.io/library/alpine@sha256:eb3e4e175ba6d212ba1d6e04fc0782916c08e1c9d7b45892e9796141b1d379ae ... 100%
/h/a/b/save-dot+sd | --> RUN ls -la > output
/h/a/b/save-dot+sd | --> SAVE ARTIFACT output /home/alex/broken/save-dot+sd/output AS LOCAL .
output | --> exporting outputs
output | [██████████] copying files ... 100%
================================ SUCCESS [main] ================================
Error: build target: rm /home/alex/broken/save-dot: remove /home/alex/broken/save-dot: …
> Prevent saving artifacts to parent directories

- release/apt-repo/postrm
- release/yum-repo/earthly.spec
earthly cache should only be removed on uninstalls.
> dont remove cache on upgrade

- contrib/earthfile-syntax-highlighting/syntaxes/earthfile.tmLanguage.json
If have more than 1 space after EXPOSE. It'll highlight:
After fix:
> Fix vscode not highlight port number when have space after EXPOSE more than 1 space

- builder/builder.go
- builder/builder_test.go
The temp output directory should only be created when needed; without
this PR, running a target that doesn't output artifacts (or running
under --no-output), will still cause the temp directory to be created,
which will fail if earthly is being run on a read-only directory.
> Only create outdir when needed

- buildcontext/gitlookup.go
- examples/tests/bootstrap/test-bootstrap.sh
- util/cliutil/earthlydir.go
- util/fileutil/expand.go
- util/fileutil/homedir.go
- util/fileutil/iswritable_other.go
- util/fileutil/iswritable_windows.go
Both cliutil and fileutil contain similar code to detect the home
directory; this combines the two functions into a single function.
This will ensure we consistently use the same home dir detection.
> move DetectHomeDir to fileutil

- Earthfile
- docs/earthfile/earthfile.md
- release/msi/Earthfile
rather than using ubuntu:latest for our dind image, pin to a specific
version to speed up release times so we don't have to rebuild it as
frequently.
> pin ubuntu to 20.10

- CHANGELOG.md
- Earthfile
- buildkitd/Earthfile
- release/Earthfile
- release/README.md
- release/apt-repo/Earthfile
- release/changelogparser.py
- release/release.sh
This PR introduces a new release target `+all`; which will
build earthly and release it to github and our homebrew repo.
In a follow up PR we will also chain up the apt and yum releases into a
single task.
This PR additionally requires this new task be merged before we perform a new deploy: https://github.com/earthly/homebrew-earthly/pull/12 ; that PR implements the new homebrew automatic build and merge on `release-v...` branches being pushed, without having to create a PR.
Note: This PR has a very ugly hack: the `+all` target is a `LOCALLY` target which calls earthly on the individual targets. This was done as we had to run `+release-github` along with the push, before `+release-homebrew` could begin (otherwise `+release-homebrew` would try to download files which had yet to be uploaded …
> Merge github, dockerhub, and homebrew release into one command

- Earthfile
- builder/builder.go
- builder/docker.go
- buildkitd/buildkitd.go
- cmd/earthly/main.go
- cmd/earthly/settings_test.go
- config/config.go
- examples/tests/Earthfile
- go.mod
- go.sum
- util/containerutil/docker.go
- util/containerutil/frontend.go
- util/containerutil/frontend_test.go
- util/containerutil/podman.go
- util/containerutil/shell_shared.go
- util/containerutil/stub.go
- util/containerutil/types.go
Adds podman as a compatible frontend for Earthly to use when exporting images, and running buildkit. Podman works in rootless and rootful modes, daemonless or not. As far as I have tested.
Also, autodetects some compatibility issues and ensures they are properly dealt with rather than relying on user configuration.
---
Its a draft for now, a few more tweaks need to be made and GoDoc comments to pass the linter. Its necessarily a large PR (I mean, creating the seam for pluggable container frontends was just touching a _lot_ of code), so any head start is probably worth it in reviewing.
> Add Podman Support, Automatic Configuration

- CHANGELOG.md
- Earthfile
- release/Earthfile
- release/README.md
- release/changelogparser.py
- Ensure the CHANGELOG.md file can be correctly parsed
- Changed parser to be more strict in what is accepted:
- all unordered items must start with `- `,
- only 'Added', 'Changed', 'Removed', 'Fixed' H3 headers are allowed
under version releases
- errors now display the corresponding changelog line number
- Allow changelogparser to read from stdin
> perform linting of CHANGELOG.md

- .buildkite/tests.sh
- .buildkite/windows.yml
Remove Native Windows Tests in favor of a native Windows build setup in the future. Also only do +test on these.
We will still need to modify the schedule on Buildkite itself AFAICT
> Small Build Cleanup

- cmd/earthly/main.go
- debugger/terminal/terminal_other.go
- internal terminal warnings tend to be red herrings, we should only
display them when running under verbose mode.
> only show interactive terminal warnings under verbose

- docs/earthfile/builtin-args.md
- states/dedup/targetinput.go
- util/llbutil/platform.go
- variables/builtin.go
resolves #1228 
This adds the built-ins for `USERPLATFORM`, `USEROS`, `USERARCH`, and `USERVARIANT` for the host platform.
Are there any other places that these need to be documented? I added it in the `built-ins.md`, but I'm not sure if there's anywhere else it needs to be added. Also, should these be considered experimental similar to how `TARGET*` are?
> Add user platform built-in vars

- util/containerutil/frontend_test.go
The image being used for unit/integration tests was old, and did not have an arm platform image avaliable. This swaps over to an NGINX build, from the official Docker repositories to remedy this.
Tested on an M1 by hand.
> Fix containerutil Tests on M1

- release/release.sh
This ensures that the DOCKERHUB_USER is not overridden when performing
a regular release to the earthly/earthly.git repo.
Additionally, expanded examples in the release.sh to cover
test-releases, release-candidates, and regular releases.
Examples now use `env -i` to prevent users from unintentially overriding
a different bash variable.
> ensure DOCKERHUB_USER is not overridden when git repo is earthly

- cmd/earthly/main.go
- util/containerutil/frontend.go
I had an error where `docker` was not on my PATH, and running earthly
displayed `auto frontend could not be initialized, but trying anyway`
without letting me know the issue. It wasn't obvious that a `-V` would
display the error message. Upon adding -V I got:
`auto frontend initialization error: failed to autodetect a supported frontend`.
This PR will now display the reason autodetect failed:
auto frontend initialization failed due to failed to autodetect a supported frontend: 2 errors occurred:
* docker-shell frontend failed to initalize: command failed: docker info --format={{.SecurityOptions}}: exec: "docker": executable file not found in $PATH: : exec: "docker": executable file not found in $PATH
* podman-shell frontend failed to initalize: command failed: podman info …
> Always display frontend detection errors

- CHANGELOG.md
- release/changelogparser.py
- release/release.sh
- changelog entry (previously the updated buildkit version was
incorrectly put under rc1 rather than unreleased; this rollsback that
change and correctly identifies the update being done in rc2)
- fixes changelog parser's is_intro and ignore start/stop handling.
> v0.6.0rc2 related updates

- go.mod
- go.sum
Update fsutil and docker versions to match https://github.com/earthly/buildkit/blob/earthly-main/go.mod
> update fsutil and docker to match buildkit

- util/containerutil/docker.go
`docker info --format={{.SecurityOptions}}` fails in some cases
and gives a `panic: reflect: indirection through nil pointer to embedded struct`,
lets try to prevent this from happening when the docker process is not
up.
Before, we would get:
```
2021-11-02T20:41:45.3028861Z [36m              +test3[0m | auto frontend initialization failed due to failed to autodetect a supported frontend: 2 errors occurred:
2021-11-02T20:41:45.3031192Z [36m              +test3[0m | 	* docker-shell frontend failed to initalize: command failed: docker info --format={{.SecurityOptions}}: exit status 2: panic: reflect: indirection through nil pointer to embedded struct [recovered]
2021-11-02T20:41:45.3033018Z [36m              +test3[0m | 	panic: reflect: indirection through nil pointer to embedded …
```
> test docker info works

- tests/remote-cache/Earthfile
Disable flaky tests. We will work on re-enabling them in a seperate
branch.
> disable remote-cache testing

- go.mod
- go.sum
buildkit no longer has such a replace, remove it to match buildkit's
`go.mod`.
> remove stargz replace to match buildkit

- autocomplete/complete.go
- autocomplete/complete_test.go
- cmd/earthly/main.go
- tests/Earthfile
- tests/autocompletion/Earthfile
- util/reflectutil/setbool.go
autocomplete already suggests hidden flags; however when running --help
those flags are not displayed. This extends the logic to cover both
autocompletion and help text.
> show hidden help when running dev versions

- builder/solver.go
In `cmd/earthly/main.go`, we set either the `cacheExport` or the `maxCacheExport` field into the Builder. But when generating cache export options for buildkit, we we're always using cacheExport even when `--max-remote-cache` is set.
Signed-off-by: Andrew Sy Kim <andrew@earthly.dev>
> fix cache export when using --max-remote-cache

- .github/workflows/ci.yml
- buildkitd/Earthfile
- go.mod
- go.sum
Additionally creates a new test to validate the buildkit info log
"running server on ..." is found in the earthly-buildkitd logs.
> Update buildkit to fix logging

- .buildkite/tests.sh
The cache was getting weirdly out of whack across builds. This appears to clean it up.
> Add prune to startup script

- buildkitd/Earthfile
- go.mod
- go.sum
This sets us to use https://github.com/earthly/buildkit/tree/version-for-earthly-v0.6
> update buildkit version used for earthly v0.6.0

- release/Earthfile
github disabled password-based login; this changes the homebrew release
to use a ssh key to push up changes.
> update homebrew release to use griswoldthecat ssh key

- builder/builder.go
Fixes https://github.com/earthly/earthly/issues/1422
This PR fixes the corner case of inferring whether a path is directory for the value "."
> Fix issue #1422

- buildkitd/buildkitd.go
While troubleshooting another issue, I noticed that the last error when buildkit client tries to connect is not logged which made it hard to troubleshoot the issue. This PR includes the error message in the error. 
Signed-off-by: Andrew Sy Kim <andrew@earthly.dev>
> surface last connection error from buildkitd client

- earthly
if `./earthly` is executed via a symlink, this fixes the following error
/home/alex/bin/earthly: line 99: /home/alex/bin/.earthly_version_flag_overrides: No such file or directory
> earthly wrapper should check for symlink

- release/Earthfile
- release/README.md
- release/apt-repo/Earthfile
- release/release.sh
- release/yum-repo/Earthfile
Move apt and yum repo deployment under ./release.sh script
so we only have to run a single command.
Update the homebrew release message to point out the URL's branch will
be deleted by GHA (under https://github.com/earthly/homebrew-earthly/blob/main/.github/workflows/test-and-publish.yml#L86)
Update the readme to suggest using `env -i`, to make it obvious which
environment variables are being passed to `release.sh`.
> Perform apt+yum deploy under ./release.sh

- docs/earthfile/earthfile.md
- docs/earthly-command/earthly-command.md
- docs/guides/build-args.md
I think I lost some `earthfile.md` changes in the past. I remember making some of these exact changes before.
Changes:
* Update `earthfile.md` to use the new build arg syntax
* Clarify in the build arg and secrets guide the various ways in which these can be passed over to Earthly
> Improve docs for build-args and secrets

- docs/ci-integration/guides/gitlab-integration.md
- release/README.md
Some minor adjustments based on feedback after this PR was merged: https://github.com/earthly/earthly/pull/1471
One outstanding question that was asked on Slack: "Does the GitLab integration work on the [Earthly image](https://hub.docker.com/r/earthly/earthly)?" 
- I was not able to get it working, however, some more testing could be done. For example:
- Does it work locally or elsewhere within the Earthly image? 
- Maybe I was missing something in my GitLab config? 
- Can we get a copy of the `.gitlab-ca.yml` from the user who was having issues with it?
- Nonetheless, I think the current guide showing Docker's own image is still appropriate, as it's what is [suggested by GitLab](https://docs.gitlab.com/ee/ci/docker/using_docker_build.html) to run Docker commands in their CI.
> Update GitLab Integration Guide

- earthly
MacOS does not support "readlink -f"
> fix ./earthly to work on MacOS

- Earthfile
I accidentally broke this in dcdc7faf951c5247d554823f46a9e8bf964f535b
> fix prerelease ARG

- CHANGELOG.md
- cmd/earthly/main.go
Currently --interactive does not work with a remote buildkit instance,
until this is implemented, we should display a more clear error message.
> Error out if interactive and buildkit-host flags

- buildcontext/git.go
- builder/builder.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- earthfile2llb/withdockerrun.go
- util/llbutil/statetoref.go
This fixes a bug where IF statements were still being cached when a user
provided the --no-cache flag.
> fix: --no-cache cli flag didn't apply to IF

- buildcontext/gitlookup.go
- buildcontext/gitlookup_test.go
keyscan warnings such as:
failed to parse key scan "...": SplitHostPort on "github.com" failed: address github.com: missing port in address
were being incorrectly warned when a missing port (which defaults to 22) is allowed.
> fix ssh keyscan warning when port doesnt exist

- earthfile2llb/earthfile2llb.go
- earthfile2llb/interpreter.go
- tests/autocompletion/Earthfile
- tests/autocompletion/fake.earth
autocompletion for ARGS with flags (e.g. ARG --required FOO)
was incorrectly suggesting
+target ----required
rather than
+target --FOO`.
> fix autocompletion of ARGs containing flags

- .buildkite/tests.sh
Don't set `EARTHLY_VERSION_FLAG_OVERRIDES` until after the first build is
done with the released binary, since the values in `EARTHLY_VERSION_FLAG_OVERRIDES`
might not work with the released version of earthly and only apply to
the newly built binary.
> set EARTHLY_VERSION_FLAG_OVERRIDES after initial build

- scripts/tests/auth/test-with-git-url-instead-of.sh
Currently if main is broken, and fixed in a PR,
this test will fail until main is fixed. This makes it impossible
to submit a PR and validate the PR fixes main until after it gets
merged to main.
> test against current branch rather than main

- docs/best-practices/best-practices.md
- docs/examples/examples.md
- docs/guides/integration.md
GitBook currently has a bug where any references to an "Earthfile" gets confused with "docs/Earthfile" and somehow appends a /README.md
e.g. https://github.com/earthly/earthly/blob/main/Earthfile is changed to https://github.com/earthly/earthly/blob/main/Earthfile/README.md
This is a workaround they suggested we could use until they fix the
issue.
> use tinyurl to reference Earthfile due to gitbook bug

- Earthfile
- docs/earthfile/earthfile.md
- examples/cobol/Earthfile
- examples/cpp/Earthfile
- release/apt-repo/Earthfile
- release/msi/Earthfile
- scripts/tests/auth/test-with-git-url-instead-of.sh
Ubuntu 20.04 has long-term-support; 20.10 does not.
20.10 deb repos are no longer maintained and some mirrors are now
returning 404s which are causing builds to break.
> use ubuntu 20.04 rather than 20.10

- CHANGELOG.md
- cmd/earthly/main.go
- tests/Earthfile
- tests/autocompletion/Earthfile
- tests/ls.earth
Displays a list of all targets under an Earthfile.
usage:
earthly ls
earthly ls ./sub-dir-containing-an-earthfile
This commit is dedicated to jazzdan.
> earthly ls: lists targets under an Earthfile

- buildkitd/buildkitd.go
This fixes #1413 -- IsStarted was not checking for errors.
> bugfix: error handling for IsStarted

- buildkitd/dockerd-wrapper.sh
Under heavy load, `dockerd` can't start `containerd` in time. The timeout is not configurable, so retries to catch it under lesser load seem simple enough.
The alternative would be to start `containerd` ourselves. We can go there and make sure its compatible... but it seems easier to let the dependency manage itself if we can get away with it.
> Add a retry for starting `dockerd` when using `WITH DOCKER`

- ast/tests/Earthfile
- ast/tests/quotes.ast.json
- ast/tests/quotes.earth
Expand AST tests to validate strings can be joined together
without requiring a space.
> Add test for joining two quoted strings

- builder/builder.go
- earthfile2llb/converter.go
Fixes https://github.com/earthly/earthly/issues/1543
Also, improve the error message when the same image is attempted to be pushed from more than one target
> Fix race condition caused by UDC args incorrectly causing the same target to look like a different one

- ast/tests/build-arg.ast.json
- earthfile2llb/converter.go
- tests/build-arg.earth
- tests/if.earth
The IF command stores the exit code to a file.
This file must be writable by the current user.
/run is only writable by root; however /tmp
should be writable by all users (unless an earthly user goes out of
their way to change the permissions of /tmp).
Fixes #1547
> fixes IF statements not working as non-root

- .github/workflows/ci.yml
This PR cuts `+all-buildkitd` into 3 steps in GHA.
This introduces some duplication but seems to take build time from 60 minutes to 30 minutes.
See here:
https://github.com/earthly/earthly/actions/runs/1684389244
> Build Speed up

- analytics/analytics.go
- autocomplete/complete.go
- buildcontext/excludes_test.go
- buildcontext/git.go
- buildcontext/gitlookup.go
- builder/builder.go
- cmd/debugger/main.go
- cmd/earthly/main.go
- config/config.go
- debugger/common/common.go
- dockertar/dockertar.go
- earthfile2llb/converter.go
- earthfile2llb/withdockerrun.go
- earthfile2llb/withdockerrunlocal.go
- secretsclient/client.go
- tests/docker2earth/app.go
- util/fileutil/homedirs.go
The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
> refactor: move from io/ioutil to io and os packages

- Earthfile
- tests/docker2earth/Dockerfile2
io/ioutil is deprecated and no longer used in our codebase. This is to
keep it that way.
> lint: ioutil is deprecated

- states/states.go
Fixes #1565 
Turns out that when comparing two targets to figure out if they are the same (to understand whether the target has already run or not), the platform that needs to be compared should be the initial platform with which the target was originally invoked as, and not the final platform that the target ends up becoming.
CC @adamgordonbell
> Fix a bug causing some targets to execute twice

- tests/Earthfile
Introduces a new ARG to RUN_EARTHLY which can be used to verify a string
(grep pattern) exists in the earthly output.
Previously we used post_command to call a perl regex (or grep); however
that approach did not allow us to test the exit code for cases where we
wanted to test that earthly failed AND displayed a correct message in
the log (testing that it failed the correct way).
> Add output_contains ARG to RUN_EARTHLY

- docs/earthly-command/earthly-command.md
- docs/guides/auth.md
Without a user, earthly will use the current username.
> update docs to include git as sample user

- Earthfile
- cmd/earthly/main.go
- docs/guides/cloud-secrets.md
- earthfile2llb/converter.go
- scripts/tests/auth/README.md
- states/dedup/targetinput.go
- tests/Earthfile
- tests/builtin-args-invalid-default.earth
- tests/builtin-args-invalid-pass.earth
- variables/builtin.go
- variables/parse.go
- variables/reserved/names.go
- variables/reserved/names_test.go
builtin ARGs can not be overridden. This introduces
an explicit check and raises an error. Previously
the overridden value was simply ignored.
> Raise error if builtin ARG has value set by user

- tests/Earthfile
- tests/with-docker-via-command/Earthfile
This test replicates the issue reported in https://github.com/earthly/earthly/issues/1582
which produces the error:
Error: build target: build main: bkClient.Build: failed to solve: image my/image:test is defined multiple times for the same default platform
This issue is in earthly v0.6.3; however was fixed in https://github.com/earthly/earthly/pull/1577
> test for duplicate with docker load failure

- builder/builder.go
- earthfile2llb/converter.go
- earthfile2llb/interpreter.go
- features/features.go
- states/states.go
Fixes https://github.com/earthly/earthly/issues/1582
For the most part, in #1582, Earthly is behaving as intended. The additional `ARG` passed to the UDC actually propagates through to the image, causing Earthly to believe that they are two different images (it doesn't know that the arg is actually not used anywhere), that happen to have the same name.
What is perhaps surprising is that some users may have been relying on this behavior before we introduced the duplicate-image check. So this PR makes that check a feature flag that is enabled in 0.6 onwards.
FWIW, this isn't reproducing in 0.6, because the image is not output automatically as a result of a `WITH DOCKER --load`. Version 0.6 makes the control of which image is output a bit more fine-grained for the user. I couldn't reproduce …
> Fix error if multiple images with the same name are output in `VERSION 0.5`

- builder/docker.go
Fixes #1590 
I'm seeing random reports that Docker GC's some images if there is little space left on the device: https://support.capiot.com/support/solutions/articles/42000074528-docker-images-automatically-getting-deleted. This (or some manual parallel user-issued prune) could be the cause of this.
Using `docker images rm -f` should help in these cases. (`-f` prevents the command from returning exit code 1 if the image is not found).
> Use docker images rm -f when removing docker image

- docs/earthfile/earthfile.md
- docs/guides/build-args.md
Adds an example of how to use FROM dockerfile with a different build
context.
> docs: FROM dockerfile with different build context

- CHANGELOG.md
- cmd/earthly/main.go
- tests/Earthfile
Allow a user to specify an alternative `.env` file to source
environment variables from.
A user may load multiple `.env` files using process
substitution. For example, if a user has `.env` committed to git
containing:
PUBLIC_VALUE=this-is-public-information
MY_TOKEN=
And a second `.env.local` which is not committed to git:
MY_TOKEN=secretvalue
A user can then have earthly combine these two files using:
earthly --env-file <(cat .env && cat .env.local) +some-target
When multiple values are defined, the last one takes precedence.
> --env-file arg to support different .env file

- .earthly_version_flag_overrides
- builder/builder.go
- features/features.go
Fixes https://github.com/earthly/earthly/issues/1594
I've also decided to move check-duplicate-images feature to 0.7, given that it has created problems so far.
> Move duplicate images check to 0.7. Fix SAVE IMAGE --cache-hint

- cmd/earthly/main.go
- tests/Earthfile
This fixes a bug that was introduced in c056afc75f6daeb25cd1f7144acaa958dfcbbea4
which caused help text to be output when --version was run, and
duplicated help text for --help.
> fix --version and --help text output

- .earthly_version_flag_overrides
- Earthfile
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- earthfile2llb/interpreter.go
- features/features.go
- util/syncutil/serrgroup/serrgroup.go
Fixes https://github.com/earthly/earthly/issues/1589
In the original repro script, it seems that `+slow` and `+fast` do actually convert in parallel, but there is nothing triggering the execution for `+slow` after the conversion, which leads to limited parallelism.
This change forces execution after each parallel conversion, to encourage more parallelism. This seems to address the problem in #1589. The parallel workers are now also started via a global error group and the top-most earthfile2llb will wait for all children to finish before returning control.
> Use force execution after parallel build conversion

- CHANGELOG.md
- analytics/analytics.go
- autocomplete/complete.go
- buildcontext/excludes.go
- buildcontext/gitlookup.go
- buildkitd/buildkitd.go
- cmd/earthly/main.go
- config/config.go
- docker2earthly/convert.go
- earthfile2llb/converter.go
- secretsclient/client.go
- tests/config/Earthfile
- tests/config/hello.earth
- util/cliutil/earthlydir.go
- util/fileutil/expand.go
- util/fileutil/fileutil.go
Error handling needs to be performed to catch permission-related errors
from obscuiring if a file exists or not.
> Perform error handling when checking if file or dir exists

- earthly
This fixes issues where periodic update text ends up clobbering secrets,
e.g.
export token="$(secrets get -n /path/...)"
would contain text such as "updating earthly...".
> ./earthly should print to stderr

- .circleci/config.yml
- tests/git-ssh-server/setup/Earthfile
- util/fileutil/homedir.go
- util/fileutil/iswritable_other.go
circle CI is being run as user `circleci` with `SUDO_USER="root"`; however the circleci user does not have access to `/root/.earthly/config.yml` therefore, we must unset the `SUDO_USER`; otherwise we will get this error: `open /root/.earthly/config.yml: permission denied`
> remove SUDO_USER from circleci test

- go.mod
- go.sum
this updates fsutil to match the same version that is required by buildkit
> update fsutil to latest version

- tests/git-ssh-server/Earthfile
- tests/git-ssh-server/setup/Earthfile
- tests/git-ssh-server/setup/no-interactive-login
Perform a sanity-check to validate the sshd server and ssh-agent
work together before moving on to testing earthly;
This it to make it easier to debug
earthly -P ./tests/git-ssh-server+test-rsa-only
which is failing in a development-branch I am currently working on.
> verify ssh git@git.example.com works

- cloud/client.go
- cmd/earthly/main.go
Edge case where this can cause an infinite recursive loop. 
Basically, an authenticated request would 401 (e.g. list secrets but not logged in) which would trigger a login request  (re-auth) -> which would 401 and trigger SSH discovery -> which would request an "auth challenge" -> which would 401, and trigger another login request (re-auth) -> which would trigger SSH discovery again -> ... etc
The solution here prevents the 401 on a login request from retrying.
> Don't re-authenticate requests which don't have a JWT

- tests/git-ssh-server/setup/Earthfile
- tests/git-ssh-server/setup/sshd_config
Due to https://github.com/golang/go/issues/39885
if we only allow rsa-sha2-256,rsa-sha2-512 golang/x/crypto
doesn't work as it presents the key as a regular ssh-rsa (which
fallsback to using sha1 hashes which are insecure)
> explicitly allow sshd to accept ssh-rsa

- cmd/earthly/main.go
- conslogging/conslogging.go
Had to reorder some things, and make sure that when using the bundler, it gets put in as the root `io.Reader`. Sample output: https://ci.earthly.dev/logs?logId=07ed7d96-cec5-4d31-ae12-4ee2ce26dbe3
> Capture missing phase output in `_full`.

- CHANGELOG.md
- autocomplete/complete.go
- tests/autocompletion/Earthfile
fixes two autocompletion bugs
- when directory has both an Earthfile and subdir containing an earthfile.
- when directory has two subdirectories where one is a prefix of the other.
> autocompletion bugfix

- conslogging/bundle.go
Report timing in milliseconds, and exempt _full from affecting whole-build status.
cc @mirho - this should fix some builds showing as cancelled when they were really completed successfully.
> Fix some remote log manifest data

- analytics/analytics.go
- cloud/client.go
- cmd/earthly/main.go
When the JWT is set, send it in the analytics request, so the server can record the user's ID with the event.
> Use JWT in Analytics Request

- release/yum-repo/Earthfile
Centos 8 has reached end-of-life, and mirror URLs need to be changed
to continue working.
We should update our yum repo release process to use a newer version of
centos in a follow-up PR.
> fix mirrors required for yum release

- cmd/earthly/main.go
Let users know they can sign up for an account using github OAuth.
Here's what the updated `--help` looks like:
earthly account register --help
NAME:
earthly account register - Register for an Earthly account
USAGE:
You may register using GitHub OAuth, by visiting https://ci.earthly.dev
Once authenticated, a login token will be displayed which can be used to login:
earthly [options] account login --token <token>
Alternatively, you can register using an email:
first, request a token with:
earthly [options] account register --email <email>
then check your email to retrieve the token, then continue by running:
earthly [options] account register --token <token>
DESCRIPTION:
Register for an Earthly account
OPTIONS:
--email value                      Email address
--token value …
> Display GitHub OAuth account registration in help

- .github/workflows/staging-deploy.yml
This changes staging releases to be of the form
0.<unix-timestamp>.<git-sha-in-decimal>
> include git sha in semver

- conslogging/bundle.go
Encode bundle target names with percent encoding. Also blacklist the `buildkitd` init prefix.
> Small log bundle fixes

- builder/solver_monitor.go
- conslogging/conslogging.go
Better accounting for build cancellation in log bundles. Cancellation is the most precedent of all statuses or results, when determining what to do.
> Better handle cancellation of builds in bundle creation

- examples/terraform/README.md
When trying the example `build_arg` failed and after looking closer at the output I realised the earthly cli help menu describes it as `build-arg`.
```
--build-arg value               A build arg override, specified as <key>=[<value>] [$EARTHLY_BUILD_ARGS]
```
> Rename build_arg to build-arg

- release/apt-repo/Earthfile
The aws s3 sync command was sometimes failing to pickup changes to
Release or Package files which resulted in hashes no longer matching.
> force apt release to always upload metadata

- .github/workflows/pkg-tests.yml
Checks are performed within a docker container and single line to make it easier to run these checks locally via a single one-liner that can be copy/pasted.
> cron test for apt/yum repos

- release/yum-repo/Earthfile
aws s3 sync doesn't always detect changes in repomd.xml
which results it a stale repo, force a cp of this file.
> force upload of yum repomd.xml data

- .circleci/config.yml
This updates the circle CI image from 16.04 to 20.04
> circleci is deprecating 16.04 image

- earthfile2llb/interpreter.go
- earthfile2llb/withdockerrun.go
- earthly-entrypoint.sh
- tests/Earthfile
- tests/ssh.earth
This fixes an issue where `--ssh` was not correctly passed to the `WITH
DOCKER` handler.
> fix RUN --ssh WITH DOCKER

- Earthfile
The if statment was previously executing the contents of $DOCKERHUB_AUTH
rather than just looking at its value.
> fix IF statement in EARTHFILE

- docs/basics/part-1-a-simple-earthfile.md
- docs/basics/part-1b-detailed-explanation.md
- docs/basics/part-2-running-the-build.md
- docs/basics/part-3-adding-dependencies.md
- docs/basics/part-4-caching-dependencies.md
- docs/basics/part-5-reducing-code-duplication.md
[Gitbook link](https://docs.earthly.dev/~/revisions/rrmLhAaanneYk5ykOWnh/)
Biggest change was to make it easier to differentiate between examples based on programming language. It was particularly difficult to pick out the beginning and end of say, the Javascript section, in Part1b: Detailed Explanation, but thought this would be beneficial on all pages. 
It would have been cool to do this with [tabs](https://docs.gitbook.com/editing-content/rich-content/with-command-palette#tabs) but I could not figure out how to do that outside of the Gitbook UI. Do changes made in the UI re sync with this repo? Wasn't sure how much we wanted to stick to standard markdown for now.
Other than that I made a couple small changes to wording to add a little context.
> Add language sections to tutorial

- ast/tests/with-docker-compose.ast.json
- earthfile2llb/withdockerrun.go
- tests/with-docker-compose/Earthfile
In the following, `earthly/redis:main` is not detected properly when used in `WITH DOCKER --load`. This PR fixes that.
```Earthly
redis:
FROM redis:6.2
SAVE IMAGE earthly/redis:main
integration-test:
FROM earthly/dind:alpine
WORKDIR /workspace
COPY ./docker-compose.yml ./
WITH DOCKER \
--compose docker-compose.yml \
--service=redis \
--load=+redis \
--load=+logstream-integration
RUN docker-compose up --exit-code-from=integration integration
END
```
> Fix inferring WITH DOCKER --load image name doesn't work well in combination with compose

- CHANGELOG.md
- cmd/debugger/main.go
According to the CNI spec, our `host-local` ipam module will always put the gateway at `.1` inside our subnet. If the derived address from the config fails to connect, fallback and try the internal CNI gateway. Should improve compatibility when the container does not have an IP, such as rootless configurations.
Fixes #1573.
> Try to fallback to CNI gateway when regular address fails.

- .earthly_version_flag_overrides
- CHANGELOG.md
- config/config.go
- features/features.go
This is a flag that does not affect compatibility (so it can be safely turned on in 0.6). It has been turned off so far, to help with rolling out gradually. We've used this internally for a few weeks without any issues and it's now time for this feature to see the light of day.
The flip of this switch will make Earthly 15-30% faster for large builds.
Original PR: https://github.com/earthly/earthly/pull/1602.
Re #1589.
> Flip on exec-after-parallel feature flag

- examples/rust/Earthfile
I lost a game of rock-paper-scissors so I'm fixing the Rust example that seems to have broken the `+examples2` target recently.
> Update Rust Example

- .earthly_version_flag_overrides
- buildcontext/git.go
- earthfile2llb/converter.go
- features/features.go
- util/llbutil/copyop.go
- util/llbutil/pllb/state.go
This helps with slightly improved cache reuse in a series of consecutive COPY operations.
> Use the equivalent of `COPY --link`, which is based on an LLB MergeOp

- util/llbutil/copyop.go
Reverts earthly/earthly#1705
Fixes https://github.com/earthly/earthly/issues/1712
> Revert "Use the zero time for the timestamp used when flattening file metadata"

- tests/Earthfile
- tests/mtime.earth
This is to prevent https://github.com/earthly/earthly/issues/1712 from reoccurring.
> Add mtime test

- .earthly_version_flag_overrides
- CHANGELOG.md
- ast/tests/with-docker.ast.json
- builder/builder.go
- builder/solver.go
- cmd/earthly/main.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- earthfile2llb/interpreter.go
- earthfile2llb/withdockerrun.go
- earthfile2llb/withdockerrunlocal.go
- features/features.go
- tests/with-docker/Earthfile
- util/syncutil/semutil/multisem.go
- util/syncutil/semutil/sem.go
- util/syncutil/semutil/weighted.go
Re https://github.com/earthly/earthly/issues/1268. This addresses point 2 in this comment: https://github.com/earthly/earthly/issues/1268#issuecomment-938261849.
This PR takes the multiple `--load`s and `--pull`s in a `WITH DOCKER` and builds the necessary image tars in parallel. This includes converting the referenced targets in parallel, but also outputting the tars in parallel.
To enable this feature use `VERSION --parallel-load 0.6`.
Separately, this also fixes https://github.com/earthly/earthly/issues/1724. No feature flag is needed to benefit from this.
> Parallel conversion for `WITH DOCKER --load`

- docs/basics/final-words.md
Rather than get a link to https://docs.earthly.dev/docs/guides/
gitbook is linking to 	https://github.com/earthly/earthly/blob/main/docs/earthfile/guides/README.md
(which doesn't exist); use a tinyurl to point to the correct location
instead (as suggested by gitbook support).
> docs: workaround gitbook bug

- docs/guides/auth.md
This makes our docs easier to quickly read for users who are having
troubles using ssh-agent and auto-mode.
The goal is to have the majority of our users use ssh-based auth via
the zero-config auto mode.
> docs: clarify how auto-auth mode is used

- util/llbutil/copyop.go
This fixes #1751.
The `docker/dockerfile-copy` image doesn't need to be run on the target platform, and somehow running the image on emulated linux/amd64 platform over linux/arm64 will hang.
Reference:
https://github.com/moby/buildkit/blob/863c99ceb928f18fbbba5cb653acedb1a528a5dd/frontend/dockerfile/dockerfile2llb/convert.go#L1150
> Run dockerfile-copy image on the build platform

- Earthfile
- podman-setup.sh
This config change allows the +unit-test target to run
on systems that have cgroups v2 installed.
> disable podman cgroups

- .earthly_version_flag_overrides
- CHANGELOG.md
- ast/tests/with-docker.ast.json
- earthfile2llb/converter.go
- earthfile2llb/interpreter.go
- earthfile2llb/shell.go
- earthfile2llb/withdockerrun.go
- features/features.go
- tests/shell-out/Earthfile
- tests/shell-out/new.earth
- tests/with-docker/Earthfile
- util/flagutil/parse.go
- util/shell/envVarTest
- util/shell/equal_env_unix.go
- util/shell/equal_env_windows.go
- util/shell/lex.go
- util/shell/lex_test.go
- util/shell/wordsTest
- variables/collection.go
- variables/parse.go
ARG values such as `foo$(cat data)` were not being expanded.
> Change ARG shell-execution

- .earthly_version_flag_overrides
- CHANGELOG.md
- Earthfile
- ast/validator.go
- builder/builder.go
- builder/solver.go
- earthfile2llb/withdockerrun.go
- earthfile2llb/withdockerrunlocal.go
- features/features.go
- states/builderfun.go
Some recent buildkit changes are causing some duplicate output when building images that are to be loaded via `WITH DOCKER`. This PR fixes that.
To benefit from these changes, you need to enable this via the feature flag: `VERSION --no-tar-build-output 0.6`. This is experimental for now.
Summary of changes:
* Enables `--parallel-load` and `--exec-after-parallel` feature flags for everyone. These don't cause compatibility issues so they can be safely enabled retroactively. These two flags will force execution of the every loaded tar build within the main build session. This means that their output will show up as part of the main build.
* Introduces a feature flag `--no-tar-build-output` which disables output for any tar build (this side-build is needed to turn the images into tar files to …
> Disable output when building a tar for loading via WITH DOCKER

- buildcontext/gitlookup.go
The default SSH timeout value is 20 minutes, this causes
earthly to hang when outbound ssh connection packets are silently
dropped. Instead, if an ssh connection can not be established within 3
seconds, default to using http(s).
> Use 3 second ssh timeout rather than default 20min

- tests/scrub-https-credentials/Earthfile
This test doesn't require the username to exist, this
PR adds a note to reflect that.
> update scrub-https-credentials test user

- Earthfile
- earthly
This prevents an explicit pull to docker.io/earthly/earthlybinaries:prerelease
in the +earthly-script-no-stdout target which can lead to rate-limiting.
> prevent docker pull in +earthly-script-no-stdout

- CHANGELOG.md
New entry for v0.6.12 and fixes the --shell-out-anywhere
entry which was merged into the wrong section.
> CHANGELOG for v0.6.12

- Earthfile
- earthly-entrypoint.sh
- tests/git-webserver/Earthfile
This works around https://github.com/earthly/earthly/issues/1764
and fixes some indentation issues which were preventing running our
tests against a self-hosted insecure pullthrough cache.
With this PR, I can now run our tests against a self-hosted cache:
env -i HOME=$HOST PATH=$PATH ./build/linux/amd64/earthly --env-file=<(echo "") --config=$HOME/.earthly/config.yml -P ./tests+all --DOCKERHUB_AUTH=false --DOCKERHUB_MIRROR=192.168.0.80:5000 --DOCKERHUB_MIRROR_INSECURE=true
Note that `env -i HOME=$HOST PATH=$PATH`, and `--env-file=<(echo "")`
are used to ensure no additional cache environment variables are
accidentally fed into earthly.
> fix tests with insecure dockerhub mirror

- .github/workflows/staging-deploy.yml
- release/Earthfile
- release/release.sh
The staging-release occurs automatically whenever a PR occurs,
if the process starts before midnight and the date changes before
we check the CHANGELOG release date, the release will fail.
Since the release date is automatically generated for staging releases,
we can remove this check.
> Skip the date check for staging-release

- docs/ci-integration/pull-through-cache.md
This extends the pull-through-cache docs to include
a quick start guide on how to run an insecure pull through cache on a
trusted network.
> Quick-start example for insecure dockerhub mirror

- CONTRIBUTING.md
Update the CONTRIBUTING.md guide to provide an example of
how to run tests with an insecure pull through cache.
> CONTRIBUTING: how to run tests with insecure cache

- release/release.sh
The previous fix in 51b44439523616ce4437c6ad57e9a4b2de2807ec
needed to also pass through the SKIP_CHANGELOG_DATE_TEST
build-arg for the release-github target too.
> ignore date check for staging +release-github

- Earthfile
* Fix M1 build (and also make it more efficient)
* Enable use-copy-link for our common usage of our own Earthfile
> Fix M1 build

- cmd/earthly/main.go
When prompting the user to pick a password, the cursor should be
displayed on the same line as the prompt:
for example:
pick a password: <cursor>
Previously the prompt looked like:
pick a password
<cursor>
> Display cursor on same line as prompt

- CHANGELOG.md
- buildkitd/docker-auto-install.sh
- buildkitd/dockerd-wrapper.sh
- tests/dind-auto-install/Earthfile
If /etc/docker/daemon.json already exists, rather than overwrite
it, we should simply update it with the new network IP ranges.
This, for example, allows a user to define an Earthfile which
configures the WITH DOCKER instance to use a different mirror:
test:
FROM earthly/dind:alpine
RUN mkdir -p /etc/docker && echo '{"registry-mirrors" : ["http://192.168.0.80:5000"]}' > /etc/docker/daemon.json
WITH DOCKER
RUN --no-cache \
cat /etc/docker/daemon.json && \
docker run --rm alpine:3.15 hostname
END
> Keep existing daemon.json data

- buildcontext/git.go
- tests/Earthfile
- tests/git-metadata/Earthfile
- tests/git-metadata/test.earth
- tests/git-ssh-server/setup/Earthfile
- util/gitutil/detectgit.go
This fixes a bug where EARTHLY_GIT_SHORT_HASH was not set when building
a remote target -- this is due to the codepath being different for
locally referenced targets and remote targets.
This fix introduces a test to validate EARTHLY_GIT_SHORT_HASH and
EARTHLY_GIT_HASH are correctly set in both cases.
> set EARTHLY_GIT_SHORT_HASH on remote targets

- Earthfile
jq is now required when using `WITH DOCKER` (dependency was introduced
in https://github.com/earthly/earthly/commit/88f94c5ed342a0162c202f5ce666d8350bf3fcc4), it is installed
automatically via `docker-auto-install.sh`.
dind-ubuntu already installs dependencies with this script, we should
use it for the alpine version as well to be consistent. Note that the
underlying docker:dind already provides dockerd, so only docker-compose
and jq will be installed.
> jq is now required when using `WITH DOCKER`

- earthfile2llb/converter.go
- earthfile2llb/interpreter.go
This prevents expandArgs from executing when handling BUILDs during
the async phase.
This fixes https://github.com/earthly/earthly/issues/1785
> prevent expanding args during async BUILDs

- release/README.md
dind images are built independently from earthly versions.
> release-dind doesn't use the RELEASE_TAG

- CHANGELOG.md
- builder/builder.go
- earthfile2llb/converter.go
- earthfile2llb/flags.go
- earthfile2llb/interpreter.go
- features/features.go
- scripts/tests/export.sh
- states/states.go
To enable this experimental feature you must use `VERSION --use-no-manifest-list 0.6`.
This PR implements support for `SAVE IMAGE --no-manifest-list`. This option disables creating a multi-platform manifest list for the image, even if the image is created with a non-default platform. This allows the user to create non-native images (e.g. amd64 image on an M1 laptop) that are still compatible with AWS lambda (AWS lambda does not support multi-platform images).
> `SAVE IMAGE --no-manifest-list`

- CHANGELOG.md
- cmd/earthly/main.go
- tests/Earthfile
- tests/earthlyargs.earth
.env should only contain earthly cli flag env values; build-args and
secrets should be stored in .earthlyargs and .earthlysecrets
respectively.
> split build-args and secrets into seperate files

- cmd/earthly/main.go
I might need some pointers on this. I am trying to improve an error message.
Old Error message for the file does not exist:
```
Error: build target: build main: failed to solve: failed to compute cache key: failed to calculate checksum of ref 4z7jcxhngtwp6n799l897lhff::54sya1iypr5uovhhi03tce12r: "/bla": not found
```
New error:
```
Error: File not found "/bla"
```
The actual error for `file not found` is in checksum.go and private so the only way I could figure to get the context out was via text matching. Is there a better way?  Ideally, I'd like to actually get the line number of the Earthfile out as well, so the error would be:
```
Earthfile:58  "/bla" not found`
```
> Better file missing error message

- cmd/earthly/main.go
- util/llbutil/secretprovider/cloud.go
- util/llbutil/secretprovider/map_store.go
- util/llbutil/secretprovider/secrets.go
This refactors the secretprovider to accept an arbitraty chain of stores
which could potentially return the secret. This will make it easier to
insert new secret stores in the future.
> refactor secretprovider to use chain of stores

- docs/guides/auth.md
> Document earthly can use the ~/.netrc file

- docs/earthfile/earthfile.md
A user was under the impression ARGs are evaluated without the `-c` flag
of `/bin/sh`. This clarifies `ARG` and `RUN` follow the same shell
wrapper code-paths.
> docs: ARG uses same shell as RUN

- util/containerutil/podman.go
podman masks off `/sys/fs/cgroup` as read-only by default, which prevents earthly from managing cgroup v2 limits.
> unmask cgroups for podman

- cmd/earthly/main.go
non-released versions are displaying the gitsha twice.
before:
earthly version dev-acb_simplify-version-string-5a6b598faaaa647b15fbee961dbe9d4741dcd082 5a6b598faaaa647b15fbee961dbe9d4741dcd082 linux/amd64; Ubuntu 20.04
after:
earthly version dev-acb_simplify-version-string 5a6b598faaaa647b15fbee961dbe9d4741dcd082 linux/amd64; Ubuntu 20.04
> simplify --version value

- docs/ci-integration/guides/gh-actions-integration.md
This is to address a PR a user opened, thinking it was possible to use
the `ref` argument to checkout a branch instead of our suggested `git
checkout -b ...` workflow.
> docs: Add note on reason actions/checkout ref is not used

- earthfile2llb/converter.go
Minor change for error messages when missing required args. May improve debug-ability for large Earthfiles with multiple required args.
Changes made:
1. print the key of the missing `ARG --required` in error message
Local testing:
```
build/darwin/arm64/earthly +run
1. Init 🚀
3. Build 🔧
Share your logs with an Earthly account (experimental)! Register for one at https://ci.earthly.dev.
Error: build target: build main: failed to solve: Earthfile line 5:2 apply ARG: value not supplied for required ARG: please_set_me
in              +run
```
> Print key of missing arg in error message

- Earthfile
- tests/dind-auto-install/Earthfile
The 20.10.15 Docker image seems to have introduced a bug/issue. Let's pin our version for now until it's fixed.
```
Repeating the output of the command that caused the failure
./t/dind-auto-install+test *failed* | BASE_IMAGE=../..+dind-alpine
./t/dind-auto-install+test *failed* | --> WITH DOCKER RUN --privileged true
./t/dind-auto-install+test *failed* | Loading images...
./t/dind-auto-install+test *failed* | Loaded image: hello-world:latest
./t/dind-auto-install+test *failed* | ...done
./t/dind-auto-install+test *failed* | Network _default  Creating
./t/dind-auto-install+test *failed* | Network _default  Created
./t/dind-auto-install+test *failed* | Container -hello-1  Creating
./t/dind-auto-install+test *failed* | Error response from daemon: Invalid container name (-hello-1), only …
```
> Pin dind version as 20.10.15 is failing

- tests/dind-auto-install/Earthfile
Docker Compose v2 is referencing the directory name when choosing a container name. If we run at `/` the name is empty and causes an error. This change uses `WORKDIR` to resolve that problem.
Related: https://github.com/earthly/earthly/pull/1884
> Add WORKDIR to dind test for Compose image name issue

- cmd/earthly/main.go
It's a bug of `osutil`.
So maybe we could just avoid it, and wait for this pr to be merged.
https://github.com/wille/osutil/pull/10
> Avoid panic in osutil

- cmd/earthly/main.go
This fixes a nil-pointer exception which occurs if NewStubFrontentd
fails.
> avoid panic if frontend stub fails

- CHANGELOG.md
- util/llbutil/secretprovider/cmd.go
This allows the custom secret provider access to the user's environment
variables (which might contain required authorization data needed to
access the user's secret-data-store)
> secretprovider: pass user's env

- docs/earthfile/earthfile.md
This documents the mode mount option, which is useful for mounting
secrets.
> docs: mount mode option

- CHANGELOG.md
- cmd/earthly/main.go
- go.mod
- tests/secret-provider-config/Earthfile
- tests/secret-provider-config/test-secret-provider
- tests/secret-provider-config/test.earth
- util/llbutil/secretprovider/cmd.go
This allows a user to pass args to a secret provider, e.g.
secret_provider: my-secret-lookup-script --key=$HOME/.ssh/id_rsa
Additionally, users can set env variables with:
secret_provider: KEY="my value" my-secret-lookup-script
> secretprovider: allow args

- .github/workflows/ci.yml
- tests/wait-block/Earthfile
- tests/wait-block/test.sh
This introduces tests for the `VERSION --wait-block` feature.
It runs a registry on the localhost's docker, pushes an image to it,
then performs a curl against the regsitry to verify the image was pushed
in the correct order.
> wait-block: initial tests

- Earthfile
- docs/SUMMARY.md
- docs/ci-integration/guides/kubernetes.md
- docs/ci-integration/use-earthly-ci-image.md
- docs/docker-images/all-in-one.md
- earthly-entrypoint.sh
- tests/autocompletion/Earthfile
- tests/locally-in-command/Earthfile
This PR removes the setting `SRC_DIR` in favor of simply using the current working directory (which also defaults to `/workspace`, just as `SRC_DIR` did before). The user can now override this by using `-w` instead of `-e SRC_DIR` in a typical `docker run` command.
In addition, this also adds a separate page about using the `earthly/earthly` image in general.
> Add docs on how to use earthly/earthly image and remove `SRC_DIR`

- .github/workflows/ci.yml
- .github/workflows/staging-deploy.yml
- Earthfile
- ast/parser/Earthfile
- release/Earthfile
- release/release.sh
f95c65e4e573f445ee95171fc1ab0465b36d8289 propagated the platform into
the parser, which then caused the parser to attempt to fetch an arm7
version of openJDK which is not supported. ARM7 support was experimental
and was targeting older raspberry pi platforms -- it never worked.
Additionally prevents the prerelease from erroneously pushing a
pre-released version to the latest tag; however the latest tag
is reserved for the latest released version, not pre-released versions.
> fix staging release pipeline

- release/apt-repo/Earthfile
- release/common-repo/Earthfile
- release/common-repo/assume-developer-role.sh
- release/yum-repo/Earthfile
This introduces a new assume-developer-role.sh script which can be used
to assume the developer role. It must be called in each RUN command via
an `eval $(assume-developer-role.sh)` call.
The assume-developer-role.sh can only be called once every few seconds,
otherwise it will re-use the same TOTP token code, which AWS denies, as
a result one can call `eval $(assume-developer-role.sh N)`, where N is
the next Nth token produced in the sequence.
> update s3-related release scripts with MFA

- buildkitd/Earthfile
- buildkitd/buildkitd.go
- go.mod
- go.sum
Depends on: https://github.com/earthly/buildkit/pull/79
The current buildkit TLS client configuration seems to assume that the remote buildkit is configured to handle the TLS connection; especially for an mTLS type configuration.
This, in conjunction with the mentioned buildkit PR, allows just regular old TLS.
This could also be broken out into its own `client.ClientOpt`, but it seemed like it was more code on the `buildkit` side, especially when integrating it with the existing TLS config options. Less code over there means fewer future merge conflicts.
> Add TLS configuration for satellites

- buildkitd/dockerd-wrapper.sh
(needed for e.g. https://github.com/earthly/earthly/issues/1929)
> Add more debug info when failing to rm the dind dir

- release/ami/Earthfile
- release/ami/imagebuilder.tf
- release/release.sh
* AMI Release now works in the script (added this missing `$` :disappointed: ).
* Changed up the targets in the Earthfile to work with the new MFA on our AWS account.
* Small Terraform fixes to the build component.
I hand-ran just these targets to build v0.6.14-17, inclusive.
> Fix AMI Release

- cloud/client.go
I was frequently getting `unexpected EOF` error messages trying to delete satellites. The satellite delete would still work behind the scenes, but the request would get disconnected early after about 1 minute. 
I'm mostly sure the change in this PR fixes it, but to be honest, I'm still not sure which component is the one causing the disconnect. The request is hung up on a few places when it times out: `earthly-core -> pipelines-gateway -> pipelines-grpc -> builder-grpc` and I haven't been able to find any error messages on any of the components (other than the one I pasted above from earthly-core). 
However, the header I'm setting here is a [standard protocol](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) for controlling gRPC request timeouts and is supported by …
> Longer timeout for requests to delete or launch a Satellite

- earthly-entrypoint.sh
It is difficult to view the buildkit log (/var/log/buildkitd.log), if
the earthly/earthly docker image crashes (technically a user could
create a snapshot of the exited container, and re-tag it under a new
docker image, then run that new image and cat the contents of the log).
Instead, this change will tail the contents of the log to stdout when BUILDKIT_DEBUG=true
> tail buildkit log when BUILDKIT_DEBUG=true

- cmd/earthly/main.go
Simple solution, but a tad ugly. I'd like to remove it someday before Satellites exits beta. Hopefully, we can have a proper backend solution in the near future.
> Force re-auth on satellites commands

- cmd/earthly/main.go
CC @dchw 
This came up in a call with a user. They were confused about why the SSH key was necessary. They did not realize it could be used as a form of login. This PR adds a prompt, to clarify the intention of how an SSH key would be used (and to give the user another chance to skip this step).
> Confirm that the user wants to, before asking the specific SSH key

- CHANGELOG.md
- buildkitd/entrypoint.sh
- earthly-entrypoint.sh
if the earthly is run via the earthly/earthly docker image, it
will first run earthly-entrypoint.sh as the root process (with PID=1),
which will then start up the buildkitd/entrypoint.sh script as a sub
process. That subprocess will then setup earthly and buildkit cgroups
but will fail with `sh: write error: Resource busy` while attempting to
enable pids via `echo +pids > /sys/fs/cgroup/cgroup.subtree_control`.
That fails because `/sys/fs/cgroup/cgroup.procs` contains both the
current process **and** it's parent process. The solution is to ensure
the parent process is in a different cgroup.
> move earthly-entrypoint.sh to seperate cgroup

- cmd/earthly/main.go
- go.mod
- go.sum
Hello 
Third Package `osutil` look like desperated and have risen a problem #1898  which failed to parse env,even if #1902 have set unknwo as default
To better solve the problem, I found this pkg [go-sysinfo](https://github.com/elastic/go-sysinfo) is uesful that is reading windows  
version from windows registry instead of parse it from cmd env
this is my demo code
I've tested in Ubuntu 20 and Windows 10 
**Ubuntu 20.04**
$ ./earthly
```
· · · · ·
VERSION:
linux/amd64; Ubuntu 20.04.4 LTS (Focal Fossa)
· · · · ·
```
**Windows**
D:\>earthly.exe
```
· · · · ·
windows/amd64; Windows 10 Home China 10.0
· · · · ·
```
> refactor: replace osutil with sysinfo

- cmd/earthly/main.go
- tests/autocompletion/Earthfile
This PR enables the following usages:
* `earthly --sat=something +build` (run this specific build on a satellite)
* `earthly --no-sat +build` (run this specific build locally)
This PR also, unhides the `earthly satellite` subcommand.
> Add `--satellite` flag to be used with builds. 

- cmd/earthly/root_cmds.go
- cmd/earthly/secret_cmds.go
This PR adds support for the new project-based secret commands. The baseline secret commands are pretty much equivalent to the previous versions but they make use of the new project-based secret endpoints and include some temporary flags/envs that specify the relevant org and project. It's still not 100% worked out, but the `PROJECT` command will likely replace those flags.
I'll also be replacing user IDs with email addresses in some of the new endpoints and commands in a followup PR: https://linear.app/earthly-technologies/issue/ET-226/standardize-use-of-emails-for-user-identifier
Copied secret commands:
```
earthly preview secret (ls|get|set|rm)
```
New commands:
```
earthly preview secret permission ls <path>
earthly preview secret permission rm <path> <user-id>
earthly preview secret …
```
> New project-based secret commands

- .github/workflows/satellites.yml
Our poor Satellite can't keep up with all the commits we make on PRs. Let's dial it back a bit until we improve the stability on our instance.
> Don't run Satellites on PR commits

- CHANGELOG.md
- earthfile2llb/converter.go
See #1980. Do I need to feature flag this?
I wasn't sure how to add a test case for this, as it's interactive but I tested it with the following code.
```
interactive-save-art:
FROM alpine:3.15
RUN echo "to file" > test.txt
RUN --interactive-keep /bin/sh
SAVE ARTIFACT /test.txt AS LOCAL test.txt
```
Any changes made to test.txt in the interactive session show up in the local file.
> Adding support for saving interactive artifacts

- buildkitd/Earthfile
- cmd/earthly/debug_cmds.go
- cmd/earthly/root_cmds.go
- go.mod
- go.sum
Depends on https://github.com/earthly/buildkit/pull/82
This adds the following functionality:
* Buildkit binary is now tagged with the same version as Earthly. This version is reported in Buildkit's info call.
* `earthly prune` works now with satellites
* The following debug commands have been added to introspect buildkit's state:
* `earthly debug buildkit-info` - prints version and number of active sessions
Example output:
```
Buildkit version: dev-main
Buildkit revision: f9b1fc160d49dd40f859123b91674784fd19e845.m
Buildkit package: github.com/earthly/buildkit
Num sessions: 2
```
* **Buildkit version** is set to any string we want - this PR sets it to the exact same version of Earthly itself during release.
* **Buildkit revision** is the git SHA of buildkit.
* **Buildkit package** is set …
> Add debug calls for buildkit info items. Make prune work with satellites

- ast/parser/Earthfile
This should eliminate the random multi-platform build crashes we're sometimes seeing in CI
> Use native arch for the parser generation

- builder/image_solver.go
- builder/solver.go
- buildkitd/buildkitd.go
- cmd/earthly/buildkit.go
- outmon/solvermon.go
- tests/remote-buildkit/remote-buildkit-test.sh
Sample output:
```
buildkitd | Version github.com/earthly/buildkit v1.2.3 04bab2d652bea77688beb7d454abdc6b8a75907d
buildkitd | Platforms: linux/arm64 (native) linux/amd64 linux/amd64/v2 linux/riscv64 linux/ppc64le linux/s390x linux/386 linux/mips64le linux/mips64 linux/arm/v7 linux/arm/v6
buildkitd | Utilization: 1 other builds, 3/20 op load
```
For local buildkits this is only shown in `--verbose` mode.
The op load can also be e.g. 43/20 (20/20 currently running + 23 waiting), thus indicating if Buildkit is overwhelmed. In such cases warnings such as `Warning: Currently under heavy load. Performance will be affected` are shown.
Additionally, there are warnings / notices if the buildkit is not an **Earthly** Buildkit and if Earthly's version is different than Buildkit's version.
When …
> Print buildkit/satellite metadata on startup and when waiting on buildkit (ongoing updates)

- buildkitd/buildkitd.go
Earthly will display this if the `Info` call in unavailable, instead of just crashing
> Make the new buildkit info call more backward compatible

- cmd/earthly/main.go
- util/stringutil/random.go
This moves the random string generating logic into a seperate function,
to facilitate code-reuse in an upcomming PR.
> move session generation to RandomAlphanumeric func

- cloud/client.go
- cloud/project.go
- cloud/secret_new.go
- cmd/earthly/project_cmds.go
- cmd/earthly/secret_cmds.go
- go.mod
- go.sum
This PR updates the Cloud client to account for a change to how project members are identified (email instead of user ID).
> Use email instead of user ID for all new projects/secrets commands

- buildkitd/Earthfile
- buildkitd/buildkitd.go
- cmd/earthly/debug_cmds.go
- go.mod
- go.sum
- outmon/solvermon.go
Depends on https://github.com/earthly/buildkit/pull/83
This PR adds the following:
* GC stats as part of `earthly debug buildkit-workers` command
* Print a select few GC statistics on startup, if buildkit is remote (or satellite)
* Print warnings on startup if GC is either slow right now, or has been slow historically
* Print out GC info if GC is ongoing right now during `ongoing` output
* Print a warning if the GC is either slow right now, or has been slow historically during `ongoing` output
> Add GC stats

- builder/builder.go
- builder/image_solver.go
- builder/solver.go
- buildkitd/Earthfile
- earthfile2llb/withdockerrun.go
- earthfile2llb/withdockerrunlocalreg.go
- earthfile2llb/withdockerrunreg.go
- go.mod
- go.sum
- states/builderfun.go
- tests/with-docker-registry/Earthfile
Depends on https://github.com/earthly/buildkit/pull/85
This adds the digests of the images being loaded into `WITH DOCKER` into the LLB, such that if any of them change, the cache gets busted automatically.
@alexcb - note that there are changes in the PullPing callback. I hope it doesn't impact the stuff you're working on!
> Fix `WITH DOCKER` registry caching

- docs/earthly-command/earthly-command.md
This change reflects how earthly now splits options under global and
build commands.
This additionally documents the --config, --output, --auth-token, and
--verbose options.
> docs split options into global and build sections

- CHANGELOG.md
- ast/tests/builtin-args.ast.json
- earthfile2llb/converter.go
- earthfile2llb/interpreter.go
- features/features.go
- tests/builtin-args.earth
- variables/builtin.go
- variables/reserved/names.go
This is set to `true` or `false` when executing locally or within a container, respectively.
> introduces EARTHLY_LOCALLY arg

- buildcontext/provider/provider.go
- builder/builder.go
- builder/solver.go
- buildkitd/Earthfile
- go.mod
- go.sum
- outmon/vertexmeta.go
- tests/Earthfile
- tests/copy-verbose.earth
- util/fsutilprogress/progress.go
When running under `--verbose` mode, display individual files (and
filesize) being copied from containers onto the host.
> display detailed progress on receving files

- scripts/tests/interactive-debugger/test-interactive.py
Not all python 3.X versions implicitly import `importlib.util` when only the
parent `importlib` is imported.
> fix python import

- docs/guides/cache.md
Add a hint indicating how to check current cache size of the local
earthly-cache docker volume.
> docs: add hint on using du -h for cache size

- cloud/account.go
- cloud/client.go
- cmd/earthly/account_cmds.go
- go.mod
- go.sum
This adds two new calls:
earthly account reset --email <email>
which sends a request to the server for a password reset token to be
send to the supplied email.
and:
earthly account reset --email <email> --token <token>
which then prompts for a new password, which is then sent to the server,
to perform a password reset.
This additionally fixes the password prompt to prevent displaying a
newline before the cursor that accepts a hidden password on stdin (this
mimics the behaviour of the sudo command).
> account password reset

- cloud/client.go
- cloud/org_new.go
- cmd/earthly/org_cmds.go
This PR adds a simple invitation accept command that can be used to complete the invitation flow from the CLI.
Here's an example:
```
$ earthly org invite accept <invite-code>
```
Perhaps we can expand the command later such that codes aren't required.
```
$ earthly org invite accept
You have a few invites. Please select one to accept:
other-org
> cool-org
less-cool-org
<return>
You've been added to "cool-org" as a "read-only" member.
```
> Add simple org invite accept command

- tests/local/with-docker-compose-local-reg/Earthfile
- tests/local/with-docker-compose-local/Earthfile
Update locally tests to use "docker compose" instead of deprecated
docker-compose.
> use docker compose rather than docker-compose

- Earthfile
The M1 buildkite instance is struggling to complete unit-tests under the
default timeout value of 10m; this increases it to 20m.
> increase unit-test timeout

- tests/Earthfile
updates test to display output of earthly in cases where the test fails.
> copy-verbose-tests should always display output

- CHANGELOG.md
- builder/image_solver.go
- buildkitd/buildkitd.go
- buildkitd/dockerd-wrapper.sh
- buildkitd/settings.go
- cmd/earthly/flags.go
- cmd/earthly/main.go
- earthfile2llb/withdockerrun.go
- earthfile2llb/withdockerrunbase.go
- earthfile2llb/withdockerrunreg.go
- states/builderfun.go
- tests/with-docker-registry/Earthfile
Fixes https://github.com/earthly/earthly/issues/2071
This PR goes the extra mile to maintain forwards-backwards compatibility given the usage of the feature flag via satellites. Besides the automated test added, I have also manually tested old earthly + new buildkit and new earthly + old buildkit (this particular bug is not fixed in these combinations, but everything else still works).
Minor hidden addition as part of this PR: a way to inhibit buildkit updating and restarting (`earthly --no-buildkit-update`) - this helps test an old buildkit with a new earthly.
> Fix `WITH DOCKER` loading when image contains port number

- builder/builder.go
- builder/image_solver.go
- builder/solver.go
- cmd/earthly/build_cmd.go
- cmd/earthly/flags.go
- cmd/earthly/main.go
- earthfile2llb/converter.go
- earthfile2llb/wait_block.go
- earthfile2llb/withdockerrunbase.go
- states/cacheimports.go
- util/llbutil/statetoref.go
Related #1693
I added `--cache-from` option as experimental to import caches from registries.
This feature leads to help us to efficiently run CI in a topic branch.
Usages:
```
earthly --cache-from=someone/image1:latest +example
```
```
earthly --remote-cache=someone/image:topic-branch \
--cache-from=someone/image:main \
--cache-from=someone/image:stable \ 
+example
```
> Add `--cache-from` option for `build` command to import caches from registries

- release/ami/imagebuilder.tf
Amazon Linux introduces some rare networking bugs which we are encountering in our Cloud builds during integration tests using `kind`.
> Satellite AMI Release as Ubuntu

- Earthfile
- buildkitd/Earthfile
This renames the buildkit+update-buildkit target, to avoid confusion
regarding which `+update-buildkit` target users should run when updating
earthly to use a different buildkit version.
> rename buildkit+update-buildkit target to avoid confusion

- docs/earthfile/earthfile.md
This has been a point of confusion for a few users. The BUILD docs have some explanation under "What is being outputted", but users might miss that if they look at the docs for SAVE ARTIFACT.
> Explain when local artifacts are produced

- earthfile2llb/converter.go
- earthfile2llb/interpreter.go
- tests/wait-block/run-push/Earthfile
- tests/wait-block/run-push/test.sh
This implements handling of the `RUN --push` command
under the WAIT/END block; the command is essentially converted into:
```
ARG EARTHLY_PUSH
IF [ "$EARTHLY_PUSH" = "true" ]
RUN --no-cache ...
END
```
> WAIT/END handling of RUN --push commands
