- buildcontext/detectgit.go
- buildcontext/local.go
- examples/tests/build.earth
> Make remote URL parsing more robust

- README.md
> Added homebrew installation instruction

- earthfile2llb/converter.go
- examples/tests/build.earth
- examples/tests/from-expose.earth
> Fix issue with expose after from

- earthfile2llb/converter.go
- earthfile2llb/image/image.go
- examples/tests/build.earth
- examples/tests/scratch-test.earth
> Support for FROM scratch

- buildkitd/buildkitd.go
- buildkitd/settings.go
- cmd/earth/main.go
- docs/earth-command/earth-command.md
> User-configurable use of loop device

- cmd/earth/main.go
- earthfile2llb/cmdinterpreter.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- earthfile2llb/listener.go
- earthfile2llb/shell.go
- earthfile2llb/variables/collection.go
- earthfile2llb/variables/util.go
Also, add an interface for command interpreter.
> Move all build arg and env var related logic to variables package

- Earthfile
- config/config.go
The golint command wasn't actually scanning all code; this fixes that.
> fix golint and corresponding issues

- cmd/earth/main.go
> Evaluate potential symlinks in SSH_AUTH_SOCKET

- cmd/earth/main.go
> Slightly clearer error message when no target is provided

- .github/workflows/ci.yml
- builder/solver.go
- builder/solver_monitor.go
- cmd/earth/main.go
- conslogging/conslogging.go
- go.mod
- go.sum
> Improvements to error output

- Earthfile
- cmd/debugger/main.go
- cmd/earth/main.go
- debugger/common/common.go
- debugger/server/debugger_server.go
- debugger/server/shell_session.go
- go.mod
- go.sum
This interactive reverse debugger shell uses pty which allows bash to
use tabs, arrows, etc.
> Create a pseudo tty to provide an upgraded shell

- README.md
- docs/earth-command/earth-command.md
- docs/earth-config/earth-config.md
- docs/earthfile/earthfile.md
- docs/examples/circle-integration.md
- docs/examples/gh-actions-integration.md
- docs/guides/cache.md
- docs/guides/ci-integration.md
- release/README.md
* Document the new `FROM DOCKERFILE` feature
* Recommend to use pinned earth version in CI
* Update docs on cache
* Update docs on loop device
> Update several pieces of documentation

- buildkitd/buildkitd.go
Buildkitd wasn't correctly restarting when settings or version changes were detected due to a bug in `WaitUntilStopped`. This fixes that bug.
> Fix buildkitd restart

- config/config.go
We can remove the functionality altogether once we get more validation from the community.
> Disable loop device by default

- examples/js/package-lock.json
update serialize-javascript package to fix CVE-2020-7660 vulnerability
> update JS deps

- cmd/earth/main.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
> Remove unused interactive debugger variable

- .circleci/config.yml
- .github/workflows/ci.yml
- examples/tests/Earthfile
* Also fix: GH actions should not attempt to run on fork PRs as it will fail on docker login anyway.
> Add a test for private image

- Earthfile
- autocomplete/complete.go
- autocomplete/complete_test.go
- cmd/earth/main.go
- earthfile2llb/earthfile2llb.go
- go.mod
- go.sum
To enable auto completion, a user must enter:
complete -o filenames -C "/path/to/earth" earth
> Bash auto completion

- Earthfile
- buildkitd/entrypoint.sh
I only added `./buildkitd/entrypoint.sh` to start, but we could expand it to more scripts if we like this direction?
> add shellcheck into lint

- cmd/earth/main.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- earthfile2llb/withdockerrun.go
- go.sum
I don't see any difference between the force pull and the prefer local modes. Unsure about this works or not - hence marked the option as hidden.
> Add option to force pull images on build

- .gitignore
- cmd/earth/main.go
- earthfile2llb/variables/collection.go
- examples/tests/Earthfile
- examples/tests/dotenv.earth
- go.mod
- go.sum
> Support for .env files

- earth
small change to make the script work on macOS
> fix earth script to work on macOS

- cmd/earth/main.go
Create a bootstrap command which automatically installs bash
autocompletion.
> Auto install bash autocompletion

- autocomplete/complete.go
- cmd/earth/main.go
- config/config.go
* fix autocompletion to work with ~/ prefixes
> extend autocompletion to work with ~/ prefix

- docs/guides/basics.md
View here https://app.gitbook.com/@earthly/s/earthly-staging/v/python-basic-tutorial/guides/basics
> Python examples on basics tutorial 

- README.md
- docs/README.md
- docs/SUMMARY.md
- docs/definitions/definitions.md
- docs/earth-command/earth-command.md
- docs/examples/go.md
- docs/guides/basics.md
- docs/guides/target-ref.md
> Create Definitions Page, remove references to layers and implicit targets in basics page.

- contrib/earthfile-syntax-highlighting/syntaxes/earthfile.tmLanguage.json
Fixes https://github.com/earthly/earthly/issues/295
> Fix syntax highlighting issue when plus is in quotes

- cmd/debugger/main.go
- go.mod
- go.sum
* start shell prompt on new line
* write last failed command to bash history
* include ash shell as potential shell
> Improve interactive debugger

- docs/earth-command/earth-command.md
Also, promote interactive mode to **beta** status. cc @alexcb 
Preview:
* https://app.gitbook.com/@earthly/s/earthly-staging/~/revisions/-MHxPl4aaUO3Qxu9H_26/v/vlad%2Fdocs-env/earth-command#environment-variables-and-env-file
> Docs for .env

- builder/solver.go
- cmd/earth/main.go
* fix bug where close() was being called continually
* add --profiler flag to enable http-based CPU profiler
> Fix pegged CPU bug

- earthfile2llb/listener.go
These show up if there's an invalid flag used.
> Add usage text to Earthly command flags

- Earthfile
- examples/ruby/Earthfile
- examples/ruby/Gemfile
- examples/ruby/Gemfile.lock
- examples/ruby/src/hello.rb
Adding ruby example using gem files to install package dependencies.
> Earthly ruby example

- cmd/earth/main.go
- secretsclient/client.go
- fixes listing secret error
- display error when no authorized keys were found via the ping call
> Improve secrets client error message

- earthfile2llb/listener.go
- earthfile2llb/withdockerrun.go
- examples/tests/with-docker/Earthfile
> WITH DOCKER --load: infer image name from loaded target

- docs/earth-config/earth-config.md
- docs/guides/cache.md
Reverts earthly/earthly#417
Meant to merge this into `next`
> Revert "Update docs to take into account newly updated default value for cache size"

- docs/earth-config/earth-config.md
- docs/guides/cache.md
Reviewed in https://github.com/earthly/earthly/pull/416
> Update docs to take into account newly updated default value for cache size

- builder/builder.go
- earthfile2llb/converter.go
- earthfile2llb/listener.go
- examples/tests/config.earth
- examples/tests/with-docker-compose/Earthfile
- states/states.go
> SAVE IMAGE is now implicit

- cmd/earth/main.go
- secretsclient/client.go
- this displays all users who have been granted read or read+write
access to the org.
example output:
```
$ earth org list-permissions /earthly-technologies
/earthly-technologies/          test@earthly.dev                           rw
/earthly-technologies/subpath/  test_user_4812440969352287828@earthly.dev  r
$ earth org list-permissions /earthly-technologies/subpath
/earthly-technologies/subpath/  test_user_4812440969352287828@earthly.dev  r
```
> add list-permissions command

- docs/guides/integration.md
- examples/integration-test/Earthfile
Reverting integration example to use docker in docker to work around #422
> Reverting integration example to use docker in docker 

- examples/tests/Earthfile
- examples/tests/autocompletion/Earthfile
- examples/tests/autocompletion/fake.earth
- creates two basic tests for autocompletion
> initial autocomplete tests

- docs/examples/circle-integration.md
- docs/examples/gh-actions-integration.md
- docs/guides/ci-integration.md
- release/Earthfile
- release/README.md
* Update release instructions
* Reduce amount of testing as it has all been automated now
* Update links to latest version in docs
> Release chores

- buildcontext/detectgit.go
> Evaluate symlink when detecting gitRelDir

- README.md
- examples/tests/Earthfile
this is mostly a test PR to make sure everything works after our rename from master to main.
> include reference to main in readme

- docs/SUMMARY.md
- docs/earthfile/earthfile.md
- docs/earthfile/earthignore.md
- examples/js/.earthignore
Fixes https://github.com/earthly/earthly/issues/483
> Document .earthignore

- buildcontext/detectgit.go
- buildcontext/local.go
- examples/tests/Earthfile
- examples/tests/empty-git.earth
- examples/tests/with-docker/Earthfile
Fixes https://github.com/earthly/earthly/issues/490
> Properly handle empty git repos (no hash, no remote, no branch etc)

- domain/artifact.go
- domain/domain_test.go
- domain/target.go
- earthfile2llb/converter.go
- earthfile2llb/listener.go
- examples/tests/Earthfile
- examples/tests/escape-dir1.earth
- examples/tests/escape-dir2.earth
- examples/tests/escape.earth
- go.sum
Fixes https://github.com/earthly/earthly/issues/502
> Support COPYing files and artifacts containing + in them

- README.md
> Add slack to readme

- buildkitd/dockerd-wrapper.sh
Fixes https://github.com/earthly/earthly/issues/515
CC @agbell
> Fix for dind conflict

- Earthfile
- builder/solver_monitor.go
... also don't reprint it if nothing was added to it.
> Limit frequency of output if reprinting the same line

- secretsclient/client.go
Signed-off-by: Alex Couture-Beil <alex@mofo.ca>
> Don't retry auth failures

- cmd/earth/main.go
Signed-off-by: Alex Couture-Beil <alex@mofo.ca>
> Default to ls / when no path given

- cmd/earth/main.go
> Add help usage text to secrets commands

- earthfile2llb/variables/collection.go
- examples/tests/Earthfile
- examples/tests/build-arg.earth
Fixes https://github.com/earthly/earthly/issues/527
CC @agbell
> Don't clear args on FROM

- secretsclient/client.go
> don't retry errors related to connecting to ssh-agent

- .github/workflows/ci.yml
- .tests/private-repo.sh
- Earthfile
- makes use of secrets service to fetch shared-ssh key
- uses shared ssh key to clone from a private repo
> integration test clonning remote private repos

- cmd/earth/main.go
For once this is live: https://github.com/earthly/website/pull/4
> Add links for ToS and Privacy Policy

- cmd/earth/main.go
> Allow users to register without adding a public key

- cmd/earth/main.go
> Add missing [y/N] prompt to ToS acceptance prompt

- secret-readme.md
> Initial readme for using the new secret store

- release/Earthfile
> Post a message to #release upon completion

- cmd/earth/main.go
> Improve usage text for secret and account commands

- cmd/earth/main.go
> Display warning when no ssh-agent is running during login

- secretsclient/client.go
- this will allow our irish-fancy to override the auth.token during
testing
> Allow override auth.token directory

- Earthfile
- scripts/install-all-versions.sh
This script will install all released versions under ~/bin/earth-v0.X.Y
> Script to install all released versions

- Earthfile
- examples/cobol/Earthfile
- examples/cobol/fibonacci.cob
I saw an article about a new GNU Cobol release and thought it was a travesty that we weren't on the COBOL train yet
> Nobody asked for this, but it exists now

- secretsclient/client.go
Signed-off-by: Alex Couture-Beil <alex@mofo.ca>
> Fix location of auth.token

- scripts/install-all-versions.sh
- update install all versions script to correctly detect which binary
name to use
> Update install-all-versions to detect bin name

- Earthfile
- cmd/earthly/main.go
- docker2earthly/convert.go
- examples/tests/docker2earth/test.sh
Signed-off-by: Alex Couture-Beil <alex@mofo.ca>
> rename docker2earth to docker2earthly

- .buildkite/tests.sh
- .circleci/config.yml
- .github/workflows/ci.yml
- Earthfile
- buildkitd/Earthfile
- docs/examples/cpp.md
- docs/guides/integration.md
- examples/cobol/Earthfile
- examples/cpp/Earthfile
- examples/dotnet/Earthfile
- examples/elixir/Earthfile
- examples/go/Earthfile
- examples/integration-test/Earthfile
- examples/integration-test/src/smoketest/smoketest.sh
- examples/java/Earthfile
- examples/js/Earthfile
- examples/multirepo/Earthfile
- examples/python/Earthfile
- examples/ruby-on-rails/Earthfile
- examples/ruby/Earthfile
- examples/scala/Earthfile
- scripts/tests/private-repo.sh
The effects of this should be visible once merged to `main`, so that the cache gets a chance to get pushed.
> Use inline caching in CI

- .buildkite/blog-examples-test.sh
- .buildkite/brew-upgrade-test.sh
- if earthly doesn't exist, fall back to using earth
> Update scheduled tests to use earthly or earth

- scripts/tests/self-hosted-private-repo.sh
> Run self-hosted private ssh test with verbose flag

- cmd/earthly/main.go
> Automatically use https when no ssh keys exist

- cmd/earthly/main.go
> Warn if using earth instead of earthly

- docs/earthly-command/earthly-command.md
Initial documentation for earthly account registration and administration commands.
> Docs secrets

- docs/earthly-command/earthly-command.md
> Document org commands

- secretsclient/client.go
> Fix error message on list org permissions

- docs/earthfile/earthfile.md
- docs/guides/cloud-secrets.md
- docs/guides/shared-cache.md
* Small improvements to experimental guides
* Document `--keep-ts` and `--keep-own`
* Use-case for mac-cache setting.
> Small documentation tweaks

- docs/earthly-config/earthly-config.md
Go to main with these docs since its already released.
> Document buildkit additional args

- scripts/install-all-versions.sh
- install-all-versions.sh didn't work when multiple binaries existed for
a single release
> bugfix: fix script to work with multiple binaries

- cmd/earthly/main.go
- if the secret value starts with a '@', then load the contents of the
file it points to.
> Load secret data out of a file

- Earthfile
- analytics/analytics.go
- cmd/earthly/main.go
- syncutil/wait.go
> Send analytics to api.earthly.dev/analytics

- .buildkite/blog-examples.yml
- .buildkite/macOS-brew.yml
- .buildkite/macOS.yml
- .buildkite/windows.yml
- .github/workflows/ci.yml
> override install ID during tests

- cmd/earthly/main.go
> Rename earth to earthly in help text

- cmd/earthly/main.go
- this will make calling wrap() slightly less verbose
> Change wrap to take varargs

- buildcontext/detectgit.go
- buildcontext/git.go
- buildcontext/local.go
- dockertar/dockertar.go
- domain/target.go
- earthfile2llb/converter.go
- earthfile2llb/listener.go
- earthfile2llb/runmount.go
> errors should start with a lower case

- cmd/earthly/main.go
Example usage:
alex@mah:~/gh/earthly/earthly$ echo -n woot | go run cmd/earthly/main.go secrets set --stdin /user/testttt
alex@mah:~/gh/earthly/earthly$ go run cmd/earthly/main.go secrets get /user/testttt
woot
alex@mah:~/gh/earthly/earthly$ go run cmd/earthly/main.go secrets get -n /user/testttt
wootalex@mah:~/gh/earthly/earthly$
> Option to store secret read from stdin

- buildcontext/git.go
- buildcontext/local.go
- builder/builder.go
- builder/solver.go
- cmd/earthly/main.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- earthfile2llb/listener.go
- earthfile2llb/runmount.go
- earthfile2llb/withdockerrun.go
- go.sum
- llbutil/constants.go
- llbutil/fakedep.go
- llbutil/platform.go
- variables/collection.go
Re https://github.com/earthly/earthly/issues/536
Integration tests to follow in additional PRs.
> Support for multi-platform builds

- Earthfile
- analytics/analytics.go
- buildcontext/gitlookup.go
- cmd/earthly/main.go
- docker2earthly/convert.go
- fileutil/fileutil.go
- secretsclient/client.go
- all other util packages are singular, fileutils should be fileutil
> rename fileutils to fileutil to be consistent

- docs/guides/integration.md
Adding link to the article on integration testing
> Adding see also blog

- variables/collection.go
- variables/collection_test.go
- getProjectName was not working for https-based authentication
- fixes #671
> Fix get project name

- .gitignore
- builder/builder.go
- examples/tests/Earthfile
- examples/tests/multi-subdirectory-wildcard.earth
> Handle mixed files and subdirectories on wildcard

- analytics/analytics.go
> Only send analytics data to api.earthly.dev

- docs/earthfile/earthfile.md
> Small clarification on files kept

- README.md
- docs/README.md
- docs/installation/installation.md
Re https://github.com/earthly/earthly/issues/331
> Update installation instructions for syntax highlighting

- Earthfile
- examples/rust/Cargo.toml
- examples/rust/Earthfile
- examples/rust/src/main.rs
Hi,
This is an attempt at a rust example project for Earthly. I am by no means an expert in Rust or in Earthly so any feedback is appreciated.
> Rust example project for earthly/earthly#341

- earthfile2llb/listener.go
- examples/tests/Earthfile
- examples/tests/copy.earth
- llbutil/copyop.go
Fixes https://github.com/earthly/earthly/issues/705
> Fix inconsistencies related to COPY --dir

- docs/SUMMARY.md
- docs/guides/auth.md
- docs/guides/guides.md
- docs/guides/pushing-images-to-ECR.md
> Cloud Docker Repo Guides

- docs/guides/shared-cache.md
I manually tested each with `--remote-cache` and with `--ci`
> Add --remote-cache compatibility matrix

- Earthfile
- buildkitd/Earthfile
- cmd/earthly/main.go
- earthfile2llb/converter.go
- earthfile2llb/listener.go
- llbutil/platform.go
Re https://github.com/earthly/earthly/issues/722
In addition, an empty platform string is allowed and it represents "the default platform".
> Propagate platform between projects

- docs/earthfile/earthfile.md
> Add documentation for LOCALLY directive

- earthfile2llb/converter.go
> Ignore FROM busybox... under locally mode

- earthfile2llb/converter.go
- earthfile2llb/listener.go
- examples/tests/local/Earthfile
> Support for build args for LOCALLY directive

- go.mod
- go.sum
- previous version had a bug which prevented builds on darwin
> Update buildkit version

- docs/guides/basics.md
Addresses feedback from a user about the learning curve of the basics page.
> Add context around what the COPY artifact does from the get-go

- scripts/tests/self-hosted-private-repo.sh
- github actions changed localhost to point to IPv6; so we will create a
new ipv4-localhost to point to 127.0.0.1 which will work with our
sshd service
> Fix self-hosted private sshd git repo test

- .buildkite/brew-upgrade-test.sh
> Fix linting error from buildkite test script change

- earthfile2llb/converter.go
- earthfile2llb/interpreter.go
- earthfile2llb/shell.go
- earthfile2llb/withdockerrun.go
- examples/tests/if.earth
> Support IF locally

- builder/solver_monitor.go
Fixes https://github.com/earthly/earthly/issues/798
> Fix segfault when no output and error

- earthfile2llb/converter.go
- earthfile2llb/interpreter.go
- examples/tests/Earthfile
- examples/tests/first-command.earth
- states/states.go
... plus some exceptions, like `BUILD` and `ARG`.
Fixes https://github.com/earthly/earthly/issues/807
> Detect first command and error out if it's not a FROM-like command

- buildcontext/git.go
Let me know if you can think of any downsides if we do this.
Fixes https://github.com/earthly/earthly/issues/813
> Keep git dir in git build context

- analytics/analytics.go
* Better detection for Jenkins
> Improve analytics

- cmd/earthly/main.go
> Use current executable path when generating auto completion script

- cmd/earthly/main.go
> fix zsh autocompletion

- docs/earthfile/earthfile.md
Add bare documentation for this feature, with two examples.
> Add documentation for `RUN --interactive`

- buildkitd/buildkitd.go
* Fix detection on Mac (`-b` flag is not supported in `du`)
* Add `--rm` to the `docker run` command used.
* Threshold for waiting extra time is now 10GB on a mac, rather than 30GB.
* Add information about how to reduce cache size.
> Cache size detection improvements

- .github/workflows/ci.yml
- earthfile2llb/converter.go
- earthfile2llb/interpreter.go
- examples/tests/Earthfile
- examples/tests/local/Earthfile
- go.mod
- go.sum
> Add test for locally WORKDIR

- docs/SUMMARY.md
- docs/earthfile/earthfile.md
- docs/guides/target-ref.md
- docs/guides/udc.md
Preview: https://app.gitbook.com/@earthly/s/earthly-staging/~/revisions/-MW6acp3S4kvi1vZtWUT/v/vlad%2Fdocs-new-commands/guides/udc
> Add docs for the latest commands: IF, DO, COMMAND, IMPORT

- examples/tests/local/Earthfile
Reverts earthly/earthly#878
CC @alexcb
> Revert "re-enable locally-tests"

- config/config.go
- gitconfig creation is no longer used; this code was never removed when
we switched to the new buildkit ssh forwarder implementation.
> remove dead code

- buildkitd/Earthfile
- buildkitd/cni-conf.json.template
- buildkitd/entrypoint.sh
> CNI should use an MTU that matches that of the default adapter.

- buildkitd/buildkitd.go
- buildkitd/settings.go
- cmd/earthly/main.go
- config/config.go
Simple as `earthly config global.cni_mtu 12345`.
> Add code to allow overriding MTU from earhly YAML.

- analytics/analytics.go
> detect if earthly is run via a terminal

- docs/alt-installation.md
- if a user wishes to remove earthly, we should document the additional
files which will need to be removed.
> Include a list of commands to remove earthly

- .github/workflows/ci.yml
- cmd/earthly/main.go
- docker2earthly/convert.go
- earthfile2llb/converter.go
- examples/tests/docker/Dockerfile
- examples/tests/docker/a.txt
- behind the scenes we 1) convert the Dockerfile into an Earthfile, 2)
run an interactive build on the converted Earthfile, then 3) delete the
generated Earthfile.
> new command to run Dockerfile directly

- docs/alt-installation.md
Re https://github.com/earthly/earthly/issues/923
> sudo earthly bootstrap

- earthfile2llb/converter.go
- examples/tests/Earthfile
- examples/tests/from-dockerfile-arg.earth
> Fix dockerfile arg

- docs/earthfile/earthfile.md
> docs for allow-priviledged flag

- ast/tests/command.ast.json
- earthfile2llb/converter.go
- examples/tests/command.earth
- variables/collection.go
> Fix global args in combination with UDCs

- docs/earthfile/earthfile.md
Re https://github.com/earthly/earthly/issues/619
> Docs for `FROM DOCKERFILE -f`

- scripts/tests/private-repo.sh
- expand test to cover case where an unauthorized key is also loaded
> test that unauthorized keys dont affect public access

- cmd/earthly/main.go
quick fix for https://github.com/earthly/earthly/issues/958
> Issue warning if flag is prefixed by build-arg=

- cmd/earthly/main.go
- examples/tests/autocompletion/Earthfile
Unhide the config command. Docs coming next.
> "Release" `earthly config`

- docs/guides/shared-cache.md
Tested myself with Inline cache.
> Add GitLab Container Registry as compatible with shared cache

- docs/alt-installation.md
- create docs for installing earthly via the deb and rpm repos.
> Docs for apt and yum repos

- docs/alt-installation.md
- Warn users that our yum and apt repos are currently experimental, and might change.
> add experimental warning to repos

- builder/docker.go
- cmd/earthly/main.go
- earthly
- examples/tests/bootstrap/test-bootstrap.sh
- util/cliutil/earthlydir.go
Should address most comments from https://github.com/earthly/earthly/pull/989 that was unintentionally automerged.
> Autobootstrap Cleanup

- .github/workflows/ci.yml
- cmd/earthly/main.go
- examples/tests/bootstrap/test-bootstrap.sh
- util/cliutil/earthlydir.go
- util/fileutil/fileutil.go
Only works with `sudo`.
Also other cleanups:
* Only print messages for autocompletion if we install the autocompletion
* Different method for detecting homedir
> Bootstrap ensures permissions of everything within it. 

- docs/alt-installation.md
- docs/earthly-command/earthly-command.md
Update bootstrap documentation.
> Update docs for next release.

- docs/earthfile/builtin-args.md
> Add docs for `EARTHLY_TARGET_PROJECT_NO_TAG`

- analytics/analytics.go
- analytics/counters.go
- buildcontext/git.go
- buildcontext/local.go
- earthfile2llb/interpreter.go
> Instrument frequency of earthfile commands

- docs/alt-installation.md
I think this is why I cant make a direct link, and the indentation is funny when you look closely.
> Add new line so I can link to this section

- docs/alt-installation.md
I had written the text, but neglected the links because they didn't exist yet.
> Add some links to the Windows install section

- cmd/earthly/main.go
This should surface any future errors properly as well.
The TCP is there to help ensure some consistency in how we specify addresses that connect to external services. This also allows us to implement shared validation for these URLs as well.
cc @alexcb
> Shellrepeater client doesn't handle the specifying the network as a URL Scheme

- docs/earthly-config/earthly-config.md
Preview: https://app.gitbook.com/@earthly/s/earthly-staging/~/revisions/-MbcpsuYbJPJmqXf9AsQ/v/vlad%2Fdocs-tip-config/docs/earthly-config
> Tip on how to change config options

- ast/tests/cache1.ast.json
- ast/tests/cache2.ast.json
- examples/tests/Earthfile
- examples/tests/cache1.earth
- examples/tests/cache2.earth
* To double-check on one of the issues we were seeing when we spoke with @jazzdan
Seems to be working as intended. Maybe it was a GC thing.
> Add a test to check that changes to the cache mount don't affect previously cached runs

- docs/SUMMARY.md
- docs/guides/build-args.md
- docs/guides/cloud-secrets.md
here's a quick link to the preview: https://app.gitbook.com/@earthly/s/earthly-staging/~/revisions/-Mbw9Zrr6M34py5BBEBo/v/secret-docs/docs/guides/build-args
> Create docs on build-args and secrets

- .buildkite/tests.sh
- .buildkite/windows.yml
Freezing appears to be gone in agent version 3.30.
> Add Windows CI

- .buildkite/tests.sh
- .github/workflows/ci.yml
This is a sandbox for using the pull-through cache until its ready to go.
> Use Mirror

- docs/docker-images/all-in-one.md
- docs/docker-images/buildkit-standalone.md
- release/README.md
also reword the release notes to make it more clear that *you* (the
releaser), has to perform this task.
> update docker image doc versions

- docs/guides/build-args.md
> fix broken link to earthfile.md

- buildkitd/entrypoint.sh
Should fix #1092 (or at least improve it).
> Swap to the nf_tables compatibility if ip_tables is not loaded.

- builder/builder.go
- cmd/earthly/main.go
- earthfile2llb/earthfile2llb.go
- features/features.go
- features/features_test.go
> Allow overriding features via env

- buildkitd/buildkitd.go
> dont pass empty variables to earthly-buildkit run

- buildcontext/gitlookup.go
Contributing to solving https://github.com/earthly/earthly/issues/961
I've tried running tests locally with `./earthly -P +test` but after some minutes I got:
```
Error: build target: build main: bkClient.Build: failed to solve: failed to lookup secret "/earthly-technologies/dockerhub/user" from secrets server: no authorized public keys found
```
First I thought it was due to my changes, but I get the same error when I'm on `main` branch. So, not sure if these tests are meant to be run on CI only.
> Define gitProtocol variables

- .github/workflows/ci.yml
- cmd/earthly/main.go
> interactive flag should not be possible with ci flag

- builder/builder.go
- cmd/earthly/main.go
- util/gwclientlogger/client.go
when running under debug mode, log all interactions with the buildkit
gateway client.
> Create verbose client debugger

- docs/SUMMARY.md
- docs/earthfile/earthfile.md
- docs/earthfile/features.md
> Add docs for VERSION

- .buildkite/tests.sh
- .github/workflows/ci.yml
- Earthfile
- builder/builder.go
- earthfile2llb/converter.go
- examples/tests/save-images/test.sh
- states/states.go
`./earthly -P +test` was failing because of this
> Fix inferred docker load when do save is disabled. Test new save in our CIs

- docs/earthfile/earthfile.md
- docs/earthfile/features.md
> Docs for FOR and for --use-copy-include-patterns

- licenses/BSL
* Update BSL Additional Use Grant to explicitly allow use when contracting
* Other minor inconsequential updates
> Update BSL Additional Use Grant text

- cmd/earthly/main.go
> reword help text for --artifact

- features/features.go
counting which features are being used will help us understand when
certain features can be sunset.
> instrument which features are being used

- examples/tests/Earthfile
- examples/tests/sequential-locally.earth
This test is to ensure all LOCALLY blocks are executed sequentially.
> test for sequential runs

- docs/earthfile/earthfile.md
> Document --if-exists options

- docs/earthly-command/earthly-command.md
https://github.com/earthly/earthly/pull/1162 rewords the artifact form
help text; update the docs to match them.
> update artifact form docs

- .buildkite/tests.sh
- .earthly_version_flag_overrides
- .github/workflows/ci.yml
- earthly
This ensures that both GHA and buildkite are using the same defined
features.
> set feature flag overrides in a single location

- buildkitd/buildkitd.go
- cmd/earthly/main.go
- cmd/earthly/settings_test.go
- config/config.go
- conslogging/conslogging.go
Also add unit tests for unified config.
> Fix config, unify feature flag and URL scheme.

- docs/earthfile/earthfile.md
> document the SAVE ARTIFACT --force flag

- docs/earthfile/earthfile.md
Fixes https://github.com/earthly/earthly/issues/1201
> Clarifications for `LOCALLY` and for `SAVE ARTIFACT` of dirs

- release/Earthfile
- release/ensure_gha_passing.py
> Ensured GHA checks are passing before releasing

- cmd/earthly/main.go
> Earthly --ci mode should allow outputs in some cases

- CHANGELOG.md
> release notes for v0.5.24

- release/Earthfile
- release/README.md
- release/changelogparser.py
- release/release.sh
- push to slack once homebrew branch is pushed
- check for overwritting existing release (and provide option to
confirm)
- seperate dind build target
> release process fixes

- release/README.md
> Notes for performing rollbacks

- Earthfile
- docs/examples/examples.md
- examples/README.md
- examples/c/Earthfile
- examples/c/src/CMakeLists.txt
- examples/c/src/fibonacci.c
- examples/c/src/fibonacci.h
- examples/c/src/main.c
- examples/c/test/CMakeLists.txt
- examples/c/test/test.c
Adds a C example with an Earthfile that can build a Docker image and run unit tests.
> Add C example (#357)

- Earthfile
- examples/c/Earthfile
> files should contain unix-style newlines

- release/README.md
> Include buildkite build badges

- domain/command.go
- domain/target.go
- examples/tests/Earthfile
- examples/tests/import/Earthfile
- examples/tests/import/lib1/Earthfile
- examples/tests/import/lib2/Earthfile
Fixes https://github.com/earthly/earthly/issues/1243
> Fix import being inconsistent vs no-import

- CHANGELOG.md
> update changelog with buildkit version

- buildkitd/Earthfile
- go.mod
- go.sum
> Bump buildkit

- CHANGELOG.md
> CHANGELOG for v0.6.0

- .github/workflows/ci.yml
- buildkitd/Earthfile
- go.mod
- go.sum
- tests/remote-buildkit/Earthfile
- tests/remote-buildkit/remote-buildkit-test.sh
fixes https://github.com/earthly/earthly/issues/1439
> update buildkit to fix remote buildkit mTLS support

- earthfile2llb/interpreter.go
- tests/Earthfile
- tests/build-arg-dynamic-with-empty-base.earth
This fixes https://github.com/earthly/earthly/issues/1448
> Prevent parallel builds when arg is dynamic

- earthfile2llb/interpreter.go
Adds better errors for https://github.com/earthly/earthly/issues/1437
The fix will require more effort and is not immediately clear, as we
eventually will run into the "Transient run not supported with LOCALLY"
errors if we manage to correctly indicate we have a locally arg that
requires a run.
> improve LOCALLY errors when args perform shel commands

- CHANGELOG.md
> CHANGELOG for v0.6.1

- buildkitd/certificates.go
> remove unused code

- util/gitutil/detectgit.go
> Uses os.SameFile for checking paths in filesystem agnostic way

- docs/earthfile/earthfile.md
I fixed the broken table. ( #1427 )
> Cosmetic change a broken table of description for VERSION command

- buildcontext/gitlookup.go
earthly comes pre-configured with ssh-rsa keyscans for github, gitlab,
bitbucket.
GitHub must have recently added a ecdsa-sha2-nistp256 keyscan, which
the crypto package favoured when passing it to our custom HostKeyCallback
function. This PR instructs the callback to favour passing the ssh-rsa
key when it exists.
> favor ssh-rsa keyscans

- docs/earthfile/earthfile.md
Fixes https://github.com/earthly/earthly/issues/1463
> Fix VERSION table

- CHANGELOG.md
> changelog for v0.6.2

- docs/guides/shared-cache.md
> reference --save-inline-cache in cache guide.

- docs/ci-integration/guides/gitlab-integration.md
- docs/ci-integration/overview.md
Full demo on GitLab running here: https://gitlab.com/brandon176/earthly-demo/-/tree/main
> Added GitLab integration example to docs

- docs/earthfile/earthfile.md
fixes https://github.com/earthly/earthly/issues/1451
> docs: COPY does not support leading slash

- earthly
> update ./earthly to force update when flag overrides change

- Earthfile
> update Earthfiles to use new build-arg format and VERSION tag

- cmd/earthly/main.go
Fixes: https://github.com/earthly/earthly/issues/1491
> Update help doc for earthly config

- Earthfile
- examples/secrets/Earthfile
I wasn't able to find a lot of examples of secrets except in our tests, but those are a bit verbose and use earthly-in-earthly. This PR just adds a simple Earthfile that uses Secrets in a very basic way. 
Signed-off-by: Andrew Sy Kim <andrew@earthly.dev>
> Add some examples using earthly secrets

- docs/earthly-config/earthly-config.md
> document strict_host_key_checking

- README.md
- docs/README.md
- docs/SUMMARY.md
- docs/basics/final-words.md
- docs/best-practices/best-practices.md
- docs/guides/udc.md
Preview: https://app.gitbook.com/o/-MB5s2W0v8S4xFU5ELti/s/iZfkHzyR9lPa2mtTFR0D/best-practices
> Best practices page

- tests/for.earth
> test for works with non-root

- cmd/earthly/main.go
- release/Earthfile
- release/apt-repo/Earthfile
- release/yum-repo/Earthfile
EARTHLY_VERSION is a built-in ARG that can't be overridden.
> fixes for the release

- earthfile2llb/converter.go
- tests/Earthfile
- variables/collection.go
Fixes https://github.com/earthly/earthly/issues/1572
> Fix variable arg default value causing duplicate execution

- scripts/tests/auth/setup.sh
> test cleanup

- scripts/tests/secrets-integration.sh
> update secrets-integration test

- CHANGELOG.md
- ast/tests/secrets.ast.json
- earthfile2llb/runmount.go
- tests/secrets.earth
This allows a user to set the file mode when mounting a secret, which
fixes https://github.com/earthly/earthly/issues/1434
> option to set mounted secret file mode

- docs/guides/docker-in-earthly.md
> docs: link to the best practices from with-docker guide

- docs/earthfile/earthfile.md
> docs: COPY examples to show how to use build-args

- Earthfile
- buildkitd/Earthfile
- release/Earthfile
Updates Earthfiles to make use of the ARG --required flag.
> Use ARG --required

- cmd/earthly/main.go
- scripts/tests/secrets-integration.sh
> Display error when logout is called with EARTHLY_TOKEN

- .github/workflows/staging-deploy.yml
- release/Earthfile
- release/release.sh
> staging release script

- CHANGELOG.md
> Update CHANGELOG to include log-sharing

- CHANGELOG.md
- buildkitd/Earthfile
- go.mod
- go.sum
Fixes https://github.com/earthly/earthly/issues/1635
> Update buildkit to fix layer index issue

- buildkitd/dockerd-wrapper.sh
While we can't say for certain that this will fix issues like #1647, It does fix all the ways I could make it replicate; and improve logging for when it may fail again.
> DIND Cleanup Improvements

- docs/earthfile/earthfile.md
- docs/guides/build-args.md
Fixes https://github.com/earthly/earthly/issues/1700
> Clarify how to use dynamic args

- docs/earthfile/earthfile.md
> expand FROM example to show subdirs and remote targets

- docs/earthly-config/earthly-config.md
- docs/guides/cache.md
> Documentation of new cache percentage setting

- .circleci/config.yml
Successful circle run: https://app.circleci.com/pipelines/github/earthly/earthly/7865/workflows/52462788-f079-440d-bb9d-1d5c159054f0/jobs/6404
> Install binfmt in circle ci

- CHANGELOG.md
- ast/parser/Earthfile
- buildcontext/git.go
- buildcontext/local.go
- buildcontext/parsefeatures.go
- buildcontext/resolver.go
- features/features.go
> Warn when encountering an Earthfile with no VERSION specified

- docs/earthfile/earthfile.md
- docs/earthfile/features.md
> document --shell-out-anywhere

- buildcontext/gitlookup.go
If /etc/ssh/ssh_known_hosts exists, the known hosts entries should also
be loaded.
> load /etc/ssh/ssh_known_hosts

- docs/earthfile/earthfile.md
> docs: simplify the WORKDIR description

- docs/earthfile/earthfile.md
> docs: HOSTS command

- CHANGELOG.md
- earthfile2llb/converter.go
- tests/Earthfile
- tests/cache-cmd.earth
> CACHE command to not share cached data among targets

- cmd/earthly/main.go
- util/llbutil/secretprovider/map_store.go
- util/llbutil/secretprovider/secrets.go
> refactor: move secretprovider into seperate package

- docs/earthly-config/earthly-config.md
> docs for secret_provider

- CHANGELOG.md
- builder/builder.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- states/states.go
- tests/Earthfile
- tests/build-after-from.earth
Fixes https://github.com/earthly/earthly/issues/1823
> Fix outputs in `BUILD` after `FROM` case

- CHANGELOG.md
- buildcontext/gitlookup.go
- tests/git-ssh-server/Earthfile
- tests/git-ssh-server/git-clone-funnyserver.earth
This fixes https://github.com/earthly/earthly/issues/1757
> fixes GIT CLONE of self-hosted repo

- autocomplete/complete_test.go
- cmd/debugger/main.go
- cmd/earthly/main.go
- conslogging/conslogging.go
- tests/autocompletion/Earthfile
- util/containerutil/frontend_test.go
- util/containerutil/settings_test.go
This fixes https://github.com/earthly/earthly/issues/1837
> conslogger should be silent during autocompletion

- .github/workflows/ci.yml
- docs/ci-integration/guides/gh-actions-integration.md
- docs/guides/multi-platform.md
> Use actions/checkout@v3 instead of v2

- docs/guides/docker-in-earthly.md
Noticed a broken link when browsing around 🙂
> Fix WITH DOCKER link from docker guide

- docs/earthfile/earthfile.md
Closes https://github.com/earthly/earthly/pull/1964
> Document how to add multiple tags to an image

- docs/ci-integration/build-an-earthly-ci-image.md
If a user wishes to override the earthly/earthly entrypoint, they must
move the root process into an isolated cgroup.
> document custom-entrypoint cgroup v2 requirements

- ast/tests/with-docker.ast.json
- buildkitd/dockerd-wrapper.sh
- tests/with-docker-registry/Earthfile
- tests/with-docker/Earthfile
Fixes https://github.com/earthly/earthly/issues/1899
> Fix retagging when using `WITH DOCKER` registry-based loading

- cloud/client.go
- go.mod
- go.sum
This PR adds support for the new projects, secrets, and org endpoints in Earthly Cloud. These will act as the basis for the forthcoming command changes.
> Adds new client methods for project, secret, & org invite endpoints.

- builder/builder.go
- builder/image_solver.go
removes duplicated code in favour of using gatewaycrafter
> deduplicate export docker image code

- cloud/client.go
- cloud/project.go
- cmd/earthly/main.go
- tests/autocompletion/Earthfile
This PR includes the command definitions and callbacks for interacting with Cloud Projects and their members.
Included:
* Create a new project
* Remove a project
* List projects
* Update a project
* List project members
* Add a project member
* Remove a member
* Update a member's permission
Questions:
* Do we want to print success messages for commands that don't otherwise expect output (project create, etc.)?
> New Cloud Project commands

- cloud/project.go
- cloud/secret_new.go
- cmd/earthly/project_cmds.go
- cmd/earthly/secret_cmds.go
Some fixes and output improvements for issues I came across while testing.
> Some fixes and tweaks for new commands

- CHANGELOG.md
- builder/builder.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- states/states.go
- tests/Earthfile
- tests/push-arg.earth
- tests/remote-cache/test.sh
- variables/builtin.go
- variables/collection.go
- variables/reserved/names.go
This adds an EARTHLY_PUSH builtin arg which is set to "true" or "false"
which mimics the behaviour of a RUN --push command.
> add EARTHLY_PUSH arg

- CHANGELOG.md
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
Fixes https://github.com/earthly/earthly/issues/1991
> Fix errors frequently being reported as context cancelled

- cloud/org_new.go
- cmd/earthly/org_cmds.go
A couple small fixes that came up while testing.
> Org invite command fixes

- .github/workflows/ci.yml
- builder/builder.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- earthfile2llb/wait_block.go
- tests/wait-block/common/test.sh
- tests/wait-block/no-output/Earthfile
- tests/wait-block/no-output/test.sh
- tests/wait-block/save-image/Earthfile
- tests/wait-block/save-image/test.sh
- tests/wait-block/save-multi-platform-image/Earthfile
- tests/wait-block/save-multi-platform-image/test.sh
- util/gatewaycrafter/pullpingmap.go
- util/stringutil/alphanumeric.go
This implements exporting images to the local docker instance;
previously only `SAVE IMAGE --push` logic was implemented.
> implement WAIT/END SAVE IMAGE logic

- CHANGELOG.md
- release/Earthfile
> build earthly/earthly docker image with arm64

- builder/image_solver.go
Fixes https://github.com/earthly/earthly/issues/2015
> Fix duplicate execution in `--use-registry-for-with-docker`

- buildkitd/entrypoint.sh
- cmd/shellrepeater/main.go
- disables running shellrepeater when DISABLE_SHELL_REPEATER=true
- display error if shell repeater dies
> Allow option to disable shell repeater

- cloud/project.go
- cmd/earthly/secret_cmds.go
Adds a new "secret migration" command that copies secrets from an existing organization to a target project (under the same or different organization).
`earthly preview secrets --org <dest-organization> --project <dest-project> migrate <source-organization>`
Example:
`earthly preview secrets --org mikeorg --project mikeproject migrate earthly-technologies`
By default the command prints out `.`'s but users can pass `--verbose` to review all copied secrets.
```
➜  earthly git:(mh/secret-migrate) ✗ earthly preview secrets --org mikeorg --project mikeproject migrate earthly-technologies
Copying 103 secrets to mikeproject
.......................................................................................................
103 secrets migrated successfully!
➜  earthly git:(mh/secret-migrate) …
```
> Secret migration command

- cmd/earthly/main.go
- conslogging/conslogging.go
- util/fsutilprogress/progress.go
Adds new debug level for logging, and enables per-file stat debug
logging when transfering files.
> debug level logging

- CONTRIBUTING.md
- Earthfile
- buildkitd/Earthfile
This adds a new section to CONTRIBUTING outlining how to submit changes
to the earthly forks of buildkit or fsutils.
> update CONTRIBUTING to reflect buildkit contributions

- earthfile2llb/interpreter.go
- go.mod
- tests/Earthfile
- tests/with-docker-expose/Earthfile
This fixes https://github.com/earthly/earthly/issues/1986
> parse EXPOSE ports using docker parser

- docs/SUMMARY.md
- docs/cloud/overview.md
- docs/cloud/satellites.md
- docs/cloud/satellites/managing.md
- docs/cloud/satellites/using.md
This adds a separate page about using satellites, to forward to people being invited.
> Docs on using satellites

- .buildkite/tests.sh
- Change the OS/arch detection to happen automatically rather than
requiring an `EARTHLY_OS` arg to be set.
- Only checkout the buildkite branch when in detached HEAD state.
> Make buildkite test runnable without env vars

- Earthfile
> Optional arg to limit unit-test target to run specific test

- buildkitd/Earthfile
- buildkitd/entrypoint.sh
- cmd/earthly/debug_cmds.go
- go.mod
- go.sum
Also, allow the buildkit entrypoint to exit gracefully (exit code 0).
This depends on https://github.com/earthly/buildkit/pull/91
> Add debug call for buildkit `ShutdownIfIdle`

- docs/cloud/satellites.md
- docs/guides/shared-cache.md
[Preview](https://docs.earthly.dev/~/revisions/hvID5h4RR4PUbLmlnoMa/earthly-cloud/satellites)
> Add a comparison between satellites and shared cache

- buildkitd/Earthfile
- cmd/earthly/debug_cmds.go
- go.mod
- go.sum
> Revert "Update Buildkit and show new field "Seconds since last run""

- cloud/client.go
This does two things:
* Does not retry on context deadline exceeded
* Does not unwrap context canceled and context deadline exceeded before returning the error from cloud client
> Fix retry on context deadline exceeded

- cmd/earthly/org_cmds.go
- cmd/earthly/root_cmds.go
* Language tweaks for new commands
* Success message when accepting an invite
* Fix for checking member update args
> A few tweaks and fixes for project/org commands

- cmd/earthly/buildkit.go
- cmd/earthly/flags.go
- cmd/earthly/main.go
- cmd/earthly/org_cmds.go
- cmd/earthly/project_cmds.go
- cmd/earthly/root_cmds.go
- cmd/earthly/satellite_cmds.go
- cmd/earthly/secret_cmds.go
A few tweaks for the new project commands.
> Use project flag for project commands and cliFlags

- cmd/earthly/root_cmds.go
Org name wasn't being set correctly.
> Fix org flag destination

- .github/workflows/ci.yml
- CHANGELOG.md
- scripts/tests/export.sh
- util/llbutil/fakedep.go
Fixes https://github.com/earthly/earthly/issues/1945
> Fix Earthly hanging on remote cache in some situations

- builder/builder.go
...for "earthly --push ...".
This fixes #2088.
> feat(logging): less verbose output

- release/ami/Earthfile
> assume yes for yum update

- cmd/earthly/org_cmds.go
- cmd/earthly/project_cmds.go
- cmd/earthly/secret_cmds.go
Add some helpful success messages for some of the new commands.
> Improve new command UX with success messages

- docs/earthfile/earthfile.md
> docs: WAIT block

- docs/earthly-command/earthly-command.md
> docs: document EARTHLY_TOKEN under account create-token command

- release/Earthfile
- release/release.sh
> push prerelease tag on staging deploys

- CHANGELOG.md
> CHANGELOG v0.6.24 fix

- .github/workflows/reusable-bootstrap-integrations.yml
- .github/workflows/reusable-example.yml
- .github/workflows/reusable-test-local.yml
- .github/workflows/reusable-test.yml
The conditionals were missing brackets and not evaluating properly.
> [ci]: fix the conditional around whether to use a satellite

- examples/README.md
- examples/next-js-netlify/.gitignore
- examples/next-js-netlify/Earthfile
- examples/next-js-netlify/README.md
- examples/next-js-netlify/netlify.toml
- examples/next-js-netlify/next-env.d.ts
- examples/next-js-netlify/package-lock.json
- examples/next-js-netlify/package.json
- examples/next-js-netlify/pages/index.tsx
- examples/next-js-netlify/styles.module.css
- examples/next-js-netlify/tsconfig.json
Added an example for a Next.js website deployed to Netlify
> added an example for a Next.js website deployed to Netlify

- docs/basics/part-1-a-simple-earthfile.md
- docs/basics/part-2-outputs.md
- docs/basics/part-3-adding-dependencies-with-caching.md
- docs/basics/part-4-args.md
- docs/basics/part-5-importing.md
- docs/basics/part-6-using-docker-with-earthly.md
- examples/tutorial/go/part1/Earthfile
- examples/tutorial/go/part2/Earthfile
- examples/tutorial/go/part3/Earthfile
- examples/tutorial/go/part4/Earthfile
- examples/tutorial/go/part5/Earthfile
- examples/tutorial/go/part5/services/service-one/Earthfile
- examples/tutorial/go/part6/Earthfile
Let me know how you feel about the updates to the go-example in the first part. Once we feel good about how things are named, I can go back and update all the other examples in the other sections, since many of them build off this first example.
> Docs updates

- util/containerutil/docker.go
- util/containerutil/podman.go
- util/containerutil/shell_shared.go
Also, add verbose printing on executed frontend-related commands.
Re #2247
> Retry some frontend commands

- docs/SUMMARY.md
- docs/earthly-command/earthly-command.md
- docs/public-key-auth/public-key-auth.md
Documentation on how public-key authentication works between earthly and the server.
> docs: public-key-auth

- .github/workflows/reusable-misc-tests.yml
- .github/workflows/reusable-test-local.yml
> increase timeouts for tests

- CHANGELOG.md
> CHANGELOG for 0.6.28

- buildkitd/Earthfile
- go.mod
- go.sum
The old merge contained a Dockerfile change that didn't use the earthly version.
> Update buldkit SHA

- CHANGELOG.md
- earthfile2llb/converter.go
- tests/Earthfile
- tests/cache-cmd.earth
Fixes https://github.com/earthly/earthly/issues/2330
> Add persistent cache support to IF, ARG, FOR and others

- .github/workflows/reusable-misc-tests.yml
> increase interactive debugger test timeout

- go.mod
- go.sum
- logbus/formatter/formatter.go
- util/deltautil/apply.go
- util/deltautil/go.mod
- util/deltautil/go.sum
Also, add the application of the satellite name delta.
> More robust delta manifest application function

- examples/cache-command/npm/package-lock.json
- examples/tutorial/js/part3/package-lock.json
- examples/tutorial/js/part4/package-lock.json
- examples/tutorial/js/part5/services/service-one/package-lock.json
- examples/tutorial/js/part6/api/package-lock.json
- examples/tutorial/js/part6/app/package-lock.json
- tests/remote-cache/test2/package-lock.json
> update npm packages used in examples/tests

- .github/workflows/ci-docker-ubuntu.yml
- .github/workflows/ci-podman-ubuntu.yml
Currently we have to force-merge docs which is not possible for user's without admin; additionaly it raises a warning in our tracker for non-tested PRs.
> run tests on docs

- conslogging/conslogging.go
This reduces the number of deltas that go into logstream by 80%.
> Add some basic buffering to conslogging

- buildcontext/gitlookup.go
- go.mod
- go.sum
I have an upstream PR open for the netrc package. https://github.com/jdxcode/netrc/pull/11
> Add NETRC_CONTENT env for directly specifying netrc content

- .github/workflows/reusable-misc-tests.yml
- CHANGELOG.md
- earthly-entrypoint.sh
- scripts/tests/earthly-image.sh
> Make the Earthly Docker image work without privileged and without docker in some situations

- cmd/earthly/build_cmd.go
- cmd/earthly/flags.go
- cmd/earthly/main.go
- earthfile2llb/interpreter.go
- earthfile2llb/interpretererror.go
- go.mod
- go.sum
- logbus/command.go
- logbus/formatter/formatter.go
- logbus/run.go
- logbus/setup/setup.go
- logbus/solvermon/solvermon.go
- logbus/target.go
- util/deltautil/go.mod
- util/deltautil/go.sum
Also, there is now a way to dump the manifest at the end of the build via `--logstream-debug-manifest-file manifest.json`.
<details>
<summary>Sample manifest</summary>
```json
{
"build_id":  "123d0a3b-b38c-4cbf-999f-ec10641142ba",
"version":  2,
"created_at_unix_nanos":  "1668820430697567000",
"started_at_unix_nanos":  "1668820431813101250",
"ended_at_unix_nanos":  "1668820434473080208",
"status":  "RUN_STATUS_SUCCESS",
"targets":  {
"978e8d41-eb51-4129-9705-da880cacd30a":  {
"name":  "+base",
"canonical_name":  "github.com/earthly/earthly:vlad/logstream-errors+base",
"override_args":  [],
"initial_platform":  "linux/arm64",
"final_platform":  "linux/arm64",
"satellite_name":  "",
"status":  "RUN_STATUS_SUCCESS",
"started_at_unix_nanos":  "1668820432976550875",
"ended_at_unix_nanos": …
```
> Populate errors and build status information in logstream

- docs/cloud/cloud-secrets.md
- docs/cloud/satellites.md
- docs/earthfile/earthfile.md
- docs/remote-caching.md
> docs: fix broken links

- util/progressbar/progressbar.go
> Less visually intrusive progress bar

- buildcontext/resolver.go
- builder/builder.go
- cmd/earthly/build_cmd.go
- cmd/earthly/main.go
- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- earthfile2llb/interpreter.go
- earthfile2llb/interpretererror.go
- go.mod
- go.sum
- logbus/formatter/formatter.go
- logbus/run.go
- logbus/setup/setup.go
- logbus/solvermon/solvermon.go
- util/deltautil/apply.go
- util/deltautil/go.mod
- util/deltautil/go.sum
- util/vertexmeta/vertexmeta.go
* Set the org and project from the PROJECT command
* Set the main target ID
* Add runner name
* Fix canceled status
> Logstream metadata improvements

- CHANGELOG.md
- cmd/debugger/main.go
- cmd/earthly/build_cmd.go
- debugger/common/common.go
> fix: support saving large files on failure

- cmd/earthly/build_cmd.go
- conslogging/bundle.go
* Also, fix a race detector issue that randomly popped up.
> Update the logstream logs URL

- CHANGELOG.md
update changelog to reflect previous fix eee3db502797bfb74e91886db59e685434e15ccc
> update changelog for save image race fix

- features/features.go
group Features struct variables by version
> seperate features by version

- CHANGELOG.md
- ast/listener.go
- earthfile2llb/converter.go
- earthfile2llb/converter_test.go
- util/shell/env_var_name.go
This validates the secret env name is a valid sh environment name.
> validate secret env name

- docs/earthly-config/earthly-config.md
moved docs to own PR as requested
> docs: add docs for `git_image` in config #2027

- .github/workflows/ci-staging-deploy.yml
- release/Earthfile
- release/release.sh
> rename automation account

- Earthfile
This adds a (very slow) target to the Earthfile that checks for any dependencies in our submodules that cycle back to the core earthly project, failing if it finds any.
Discussion points:
- `.Deps` is definitely more comprehensive, but maybe _too_ much so? it recurses through _everything_.
- `.Imports` gets the imports only for the package being checked, which is probably good enough in most cases. But we don't need this check to be run constantly. Does the speed of the check matter that much?
> Earthfile: add a target to check for core dependencies in submodules

- .github/workflows/ci-docker-ubuntu.yml
- .github/workflows/reusable-git-metadata-test.yml
- tests/Earthfile
This test has been flaky -- we will move it to a seperate job, so it doesn't hold up other tests.
See https://github.com/earthly/earthly/issues/2567 for details.
> move git-metadata+test to a seperate GHA job

- scripts/tests/auth/test-self-hosted.sh
> update test-self-hosted.sh to use VERSION 0.7

- .github/workflows/ci-staging-deploy.yml
> staging release process requires new secrets cli

- release/Earthfile
- release/release.sh
> update release.sh secrets to use v0.7

- release/release.sh
> release.sh: fix version guard

- docs/earthly-command/earthly-command.md
Follow-up to #2613 because of my itchy merge finger.
> docs/earthly-command: clarify 'earthly ls --long'

- docs/earthfile/earthfile.md
> doc: --keep-own must also exist in SAVE ARTIFACT

- cloud/satellite.go
In the unlikely case that a build starts while a satellite is in the middle of an auto-update or manual update, this timeout should be long enough that the reserve call won't timeout.
> Increase Satellite Reserve Timeout (In case of auto-updates)

- cloud/client.go
- cloud/secret_new.go
- cmd/earthly/registry_cmds.go
- cmd/earthly/secret_cmds.go
Creates a new function to fetch v2 user or project secrets
> new cloud.GetUserOrProjectSecret for v2 secrets

- docs/README.md
Updated the readme/introduction page in the docs.
> updated the readme/introduction page in the docs for Earthly 0.7

- docs/SUMMARY.md
- docs/cloud/cloud-secrets.md
- docs/cloud/earthly-ci.md
- docs/cloud/managing-permissions.md
- docs/cloud/overview.md
- docs/cloud/satellites.md
- docs/earthfile/earthfile.md
Preview: https://app.gitbook.com/s/yi347RZ02JXdgz9BJx5u/~/revisions/Ek8qmnA2K1jfQLYLUCt4/
> Add docs for getting started with Earthly CI, and managing permissions

- docs/cloud/satellites/managing.md
Explains how to turn on weekend only mode for maintenance schedules.
> Docs: Weekend-only mode for satellite auto-updates

- docs/ci-integration/guides/gh-actions-integration.md
Update the GHA example to include an example of using the
earthly/actions/setup-earthly action.
> Reference the setup-earthly github actions

- CHANGELOG.md
- earthfile2llb/converter.go
- earthfile2llb/flags.go
- earthfile2llb/interpreter.go
- features/features.go
- tests/Earthfile
- tests/no-network.earth
Introduces ability to prevent programs from using network resources.
> RUN --network=none support

- buildkitd/Earthfile
- go.mod
- go.sum
https://github.com/earthly/buildkit/pull/117
> Update buildkit (support rosetta)

- .circleci/config.yml
- docs/ci-integration/guides/circle-integration.md
> Update machine image used by circle ci in test and doc

- cmd/earthly/main.go
- cmd/earthly/project_cmds.go
- cmd/earthly/root_cmds.go
* Be more clear about what is being deleted in a project
* Ask for confirmation before deleting the project (unless `-f` flag is provided).
* Can use `-p` flag as alias to `--project`
> Project command tweaks

- cmd/earthly/flags.go
- cmd/earthly/main.go
- tests/bootstrap/test-bootstrap.sh
- tests/config/Earthfile
Fixes https://github.com/earthly/earthly/issues/2796
> Use the installation name as the installation directory

- docs/cloud/satellites.md
- docs/cloud/satellites/using.md
Some things in the satellites doc page were out of date.
> Satellites doc updates

- docs/SUMMARY.md
- docs/ci-integration/guides/bitbucket-pipelines-integration.md
Re-doing this PR to the correct branch (sorry 😅 )
> bitbucket pipelines

- earthfile2llb/converter.go
- earthfile2llb/with_docker_run_base.go
- earthfile2llb/with_docker_run_tar.go
- outmon/solvermon.go
- outmon/vertexmon.go
- tests/Earthfile
- tests/secrets-args-precedence.earth
- util/vertexmeta/vertexmeta.go
> earthfile2llb: make secrets take precedence over args

- docs/cloud/satellites/managing.md
Perhaps we should wait to merge this until https://github.com/earthly/earthly/pull/2932 is merged and released.
> Docs for changing satellite size

- release/apt-repo/postinst
- release/apt-repo/postrm
- release/yum-repo/earthly.spec
The post install script was incomplete, but was only triggered when docker was found.
fixes #2962
> fix post install for when docker is found

- earthfile2llb/with_docker_run_reg.go
This watches for ctx.Done() when looping through the res.ResultChan channel from MultiImageSolver.SolveImages when handling a WITH DOCKER RUN command that uses the registry.
> earthfile2llb: respect ctx.Done() in withDockerRunRegistry

- buildkitd/Earthfile
- buildkitd/entrypoint.sh
- cmd/earthly/debug_cmds.go
- go.mod
- go.sum
Debug command to test the new session history endpoint in buildkit. This PR also enables session history at 1h duration by default.
> Debug Command for Buildkist Session History 

- docs/ci-integration/guides/gh-actions-integration.md
> docs: fix bad link

- cmd/earthly/main.go
- cmd/earthly/org_cmds.go
* Remove deprecated values on `org select`
* Improve error messages (incorporates language from #3075)
> Improve org select

- buildkitd/buildkitd.go
If the file-lock blocks for more than 3 seconds, display a warning:
waiting on lock "/home/alex/.earthly-dev/buildkitd-startup.lock"
to give the user some feedback; otherwise, the user will have to wait 5 minutes until getting stack-trace error:
Error stack trace:
github.com/earthly/earthly/buildkitd.maybeStart
/earthly/buildkitd/buildkitd.go:181
github.com/earthly/earthly/buildkitd.NewClient
/earthly/buildkitd/buildkitd.go:111
main.(*earthlyApp).actionBuildImp
/earthly/cmd/earthly/build_cmd.go:301
main.(*earthlyApp).actionBuild
/earthly/cmd/earthly/build_cmd.go:86
github.com/urfave/cli/v2.(*App).RunContext
/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322
main.(*earthlyApp).run
/earthly/cmd/earthly/main.go:716
main.main
/earthly/cmd/earthly/main.go:323
runtime.main …
> warn if file-lock takes more than 3 seconds

- .github/workflows/reusable-misc-tests.yml
- cmd/earthly/org_cmds.go
- cmd/earthly/satellite_cmds.go
- scripts/tests/earthly-image.sh
- scripts/tests/satellites-integration.sh
The selected org set in the config (via the new `org selected` command) was not being used in satellite commands.
> Use selected org in satellite cmds

- cmd/earthly/satellite_cmds.go
- scripts/tests/satellites-integration.sh
Fixes  https://github.com/earthly/earthly/issues/3100
> Fix issue with selected satellite not showing displaying in list

- docs/earthly-config/earthly-config.md
Documented new session timeout value in buildkit. I've also broken down the buildkit config sections into smaller subsections so it's easy to document and link to individual configs within those entires.
> Docs: Session Timeout

- cmd/earthly/build_cmd.go
> Mention Earthly Satellites when not logged in

- .github/workflows/ci-docker-ubuntu.yml
The previous version has been erroring with a "BAD PATCH".
> update dockerhub-description GHA version

- .github/workflows/ci-docker-ubuntu.yml
- .github/workflows/update-docker-hub-readmes.yml
- docs/docker-images/dind.md
This additionally moves the docker hub readme update scripts to a separate workflow file.
> Update dind docker hub readme

- Earthfile
- cmd/earthly/subcmd/account_cmds.go
- cmd/earthly/subcmd/registry_cmds.go
- tests/registry-command/test-dockerhub-user.sh
This changes the registry password prompt to wait for a newline rather than EOF.
> registry setup password prompt

- buildkitd/Earthfile
- go.mod
- go.sum
Includes https://github.com/earthly/buildkit/pull/23
> Update buildkit to c7693ebc3b039d047ed3def2d1bcda90de27876e

- buildcontext/gitlookup.go
> verbose print known_hosts to make it easier to debug git related commands

- earthly
Enable this feature in `./earthly` for further testing.
> Enable global wait-end in ./earthly

- .github/ISSUE_TEMPLATE/feature-proposal.md
reword the description to make it more clear that we want user's ideas.
> change feature-proposal description

- release/changelogparser.py
The changelogparser was not appending the "Additional Info" section to the body, which meant it was never saved into the notes.txt file which is produced by the +release-notes target, which ultimately prevented it from being uploaded to the github release notes.
> changelog-parser: emit additional info section

- .github/workflows/README.md
- .github/workflows/ci-docker-ubuntu.yml
- .github/workflows/ci-podman-ubuntu.yml
- .github/workflows/reusable-find-pr-changes.yaml
Disabling skipping GH jobs due to issue with required checks and generated names.
See README update in this PR
> Disable GH skipping for docs

- inputgraph/inputgraph.go
- tests/autoskip/Earthfile
- tests/autoskip/no-project.earth
- tests/autoskip/wait.earth
- util/buildkitskipper/hasher/hasher.go
- util/buildkitskipper/hasher/hasher_test.go
This PR adds AutoSkip support for `WAIT...END` blocks.
> Auto-skip: Basic support for WAIT

- inputgraph/inputgraph.go
- tests/autoskip/Earthfile
- tests/autoskip/if-else.earth
- util/buildkitskipper/hasher/hasher.go
Adds auto-skip support for if statements. 
https://github.com/earthly/earthly/issues/3040
> Auto-skip: handle if-else statements

- Earthfile
Fixes a test failure in `main`.
> Upgrade Docker version for +dind

- inputgraph/inputgraph.go
- tests/autoskip/Earthfile
- tests/autoskip/for.earth
Basic AutoSkip support for `FOR...IN`.
> Auto-skip: add support for loops

- docs/examples/examples.md
- examples/README.md
Share larger examples and community-generated examples that are not included in this repository. 
cc @vladaionescu
> Adding more examples to example docs

- buildkitd/dockerd-wrapper.sh
Should close https://github.com/earthly/earthly/issues/2351
And also its making things bit faster..
In case of one of my project tests time dropped from 66s to 53s.
> Make download via registry faster and less spammy

- cloud/logstream.go
- cloud/logstream_test.go
- logbus/ship/ship.go
- logbus/ship/ship_test.go
Addresses: https://github.com/earthly/earthly/issues/3381
This test was essentially stuck in an infinite retry loop as the backoff time was always 0. This PR includes some revised error handling and test tweaks to fix the retry issue. The error handling changes ensure errors are always reported when the CLI exits.
> Logstream: fixes flaky test & improves error handling

- .github/workflows/ci-docker-satellites.yml
- .github/workflows/ci-docker-ubuntu.yml
- .github/workflows/ci-podman-ubuntu.yml
- Earthfile
- tests/Earthfile
The tests-no-qemu-quick no longer is, split it up into two seperate parts.
> split up tests-no-qemu-quick

- Earthfile
- inputgraph/hash_test.go
* Fixes test that I thought was flaky (even though I wrote it)
* Fixes `+test` which may not have been updated for `quickN` change
> Update auto-skip unit test

- .github/workflows/ci-docker-satellites.yml
- .github/workflows/ci-docker-ubuntu.yml
- .github/workflows/ci-podman-ubuntu.yml
- Earthfile
- tests/Earthfile
Split up the "normal" tests into two groups, and rename the "quick" tests to "group".
> split up tests

- docs/best-practices/best-practices.md
- docs/caching/caching-in-earthfiles.md
Adding tip. 
Had to start new PR and cherry pick @vladaionescu
> Docs: Adding SAVE IMAGE tip

- Earthfile
Sadly, a `--DOCKER_VERSION=~23.0.6` attempt led to push failures.
> Bump dind docker to 23.0.6-r7

- Earthfile
The `INCLUDE_TARGET_TAG_DOCKER` was not being picked up by `--all-dind`.
> Add --pass-args to +all-dind

- inputgraph/loader.go
- inputgraph/loader_test.go
A minor improvement over the previous string contents check.
> Auto-skip: improved shell expression parsing

- .gitbook.yaml
- .github/ISSUE_TEMPLATE/feature-proposal.md
- docs/SUMMARY.md
- docs/best-practices/best-practices.md
- docs/earthfile/earthfile.md
- docs/guides/functions.md
- docs/guides/importing.md
[Preview](https://app.gitbook.com/o/-MB5s2W0v8S4xFU5ELti/s/yi347RZ02JXdgz9BJx5u/~/revisions/XiqHEn0Vb5T0Zr7ufgL2/docs/guides/functions)
> Rename UDCs to functions in the docs

- .github/workflows/ci-scheduled-codeql-analysis.yml
Found a solution here: https://github.com/github/codeql-action/issues/1842
> Fix CodeQL

- tests/do-not-track/api-earthly-stub-server.py
Wait for the stub API server to start before proceeding with the do-not-track test
> do-not-track test: wait for stub server to start

- Earthfile
This was the last place that couldn't be updated until PR #3533 was merged.
> prevent deprecation message by switching to FUNCTION keyword

- .github/renovate.json5
- CHANGELOG.md
- ast/tests/git-clone.ast.json
- buildcontext/git.go
- tests/git-clone.earth
- tests/git-ssh-server/git-clone-private-ssh.earth
- tests/private-https/git-clone-private-https.earth
- tests/public-https/git-clone-public-https.earth
Also:
- Update version used in tests
- Set Renovate rule to update the image in the repo from now on
> Update alpine/git default image

- cmd/earthly/subcmd/build_cmd.go
- util/llbutil/authprovider/authprovider.go
- util/llbutil/authprovider/multiauthprovider_test.go
Make it more clear which authprovider is used for which host
> log which authprovider is used

- .github/workflows/ci-docker-ubuntu.yml
- .github/workflows/reusable-race-test.yml
- .github/workflows/reusable-wait-block-target.yml
- tests/Earthfile
Starting out with some of the more obviously suitable cases.
Example:
> Use --auto-skip where possible in tests

- CHANGELOG.md
- ast/commandflag/flags.go
- ast/tests/smoke.ast.json
- docs/earthfile/earthfile.md
- earthfile2llb/converter.go
- earthfile2llb/interpreter.go
- states/image/image.go
- tests/smoke.earth
> Add --start-interval flag to HEALTHCHECK command

- docs/earthly-config/earthly-config.md
> docs for ssh_command

- CHANGELOG.md
Release is planned for Monday morning
> update the future release date for v0.7.23

- docs/SUMMARY.md
- docs/basics/part-7-using-remote-runners.md
- docs/earthfile/earthfile.md
- docs/earthly-command/earthly-command.md
- docs/guides/build-args.md
- docs/guides/secrets.md
> Update the args and secrets docs

- cloud/satellite.go
- go.mod
- go.sum
As discussed on our last core chats, this PR collects the name of the environment variables, a passes them in a new field of the input message of `ReserveSatellite` RPC
> Collects client metadata on satellite builds

- Earthfile
> Remove +chaos-test

- README.md
> README: point build badge to staging release

- cloud/satellite.go
- cmd/earthly/subcmd/satellite_cmds.go
Adds support for our upcoming (2,3,4)xlarge instances
> Add support for additional sizes to launch and update satellite commands

- CHANGELOG.md
- earthfile2llb/converter.go
- util/llbutil/authprovider/cloudauth/authprovider.go
I have a hard time spelling propagate :)
> spelling: there's no I in propagate

- docs/cloud/satellites/best-practices.md
A guide within our cloud/satellites doc section to help users get the most from their satellite usage.
Open to adding more best practices here if anyone has ideas.
> Satellites best practices guide

- Earthfile
Addresses: https://github.com/earthly/earthly/issues/3736
See comment in Earthfile :slightly_smiling_face:
> Disable registry proxy when running in container

- buildkitd/Earthfile
- go.mod
- go.sum
up to 585d8c719ab77ed07380656dd95a986628bca78c
> update buildkit up to 585d8c71

- cmd/earthly/subcmd/build_cmd.go
- go.mod
- go.sum
- logbus/setup/setup.go
- util/deltautil/apply.go
- util/deltautil/go.mod
- util/deltautil/go.sum
These new fields will be used to display user information in the UI.
> Logstream: capture & send Git author & CI status

- cmd/earthly/subcmd/build_cmd.go
Moved a complex bit of code to a new method.
> Tidy up target parsing in build action

- buildkitd/Earthfile
- cmd/earthly/app/run.go
- go.mod
- go.sum
Update for https://github.com/earthly/buildkit/pull/42
> BK update for max exec timeout

- .github/renovate.json5
- docs/SUMMARY.md
- docs/ci-integration/guides/kubernetes.md
- docs/ci-integration/remote-buildkit.md
- docs/cloud/satellites/managing.md
- docs/cloud/satellites/self-hosted.md
- docs/remote-runners.md
New doc page for self-hosted satellites.
> Docs: Self-Hosted Satellites

- CHANGELOG.md
This contains all of the user-facing changes for the release delta: 
https://github.com/earthly/earthly/compare/v0.8.3...main
> Update changelog for v0.8.4

- util/llbutil/secretprovider/secrets.go
> Temp PR to merge main to docs-0.8

- logbus/command.go
Some of the new command manifest values are being marked as failures rather than cancellations.
> Capture more command cancellations

- CHANGELOG.md
- cmd/earthly/flag/global.go
- docs/caching/caching-via-registry.md
- docs/earthly-command/earthly-command.md
Update changelog and docs for v0.8.6
> update changelog and documentation for v0.8.6

- docs/earthfile/earthfile.md
Addresses https://github.com/earthly/earthly/issues/3917
> Update docs on --load option without explicit image name

- scripts/install-all-versions.sh
> install-all-versions: arm64 support

- cmd/earthly/app/run.go
- go.mod
- go.sum
- logbus/run.go
- logbus/solvermon/solvermon.go
To enable the display of help text in the new UI.
> Logstream: pass help message to backend when available

- ast/tests/host.ast.json
- earthfile2llb/interpreter.go
- tests/Earthfile
- tests/host.earth
This should fix [#1743](https://github.com/earthly/earthly/issues/1743)
> Expand args on the HOST command so you can have dynamic hostnames

- .github/renovate.json5
earthly/earthly - any time (asap)
all others: starting Monday morning PST
> Renovate config - set schedule for packages

- CHANGELOG.md
- inputgraph/loader.go
- tests/autoskip/Earthfile
- tests/autoskip/expand-let.earth
- tests/autoskip/expand-set.earth
- tests/wildcard-copy.earth
Address https://github.com/earthly/earthly/issues/3996
> Support Let/Set in autoskip

- CHANGELOG.md
- docs/earthfile/earthfile.md
- docs/earthfile/features.md
Docs and change logs I missed in previous PR. Thanks @idodod 
Previous: https://github.com/earthly/earthly/pull/4023
> Adding docs and change log changes for `--raw-output`

- docs/earthfile/earthfile.md
> docs: include example IF that uses a custom script

- earthfile2llb/converter.go
- earthfile2llb/earthfile2llb.go
- earthfile2llb/interpreter.go
- earthfile2llb/with_docker_run_local_reg.go
- earthfile2llb/with_docker_run_local_tar.go
- earthfile2llb/with_docker_run_reg.go
- earthfile2llb/with_docker_run_tar.go
- tests/autoskip/Earthfile
- tests/autoskip/build-multiplatform-failure.earth
> fix: BUILD --auto-skip saving hashes from failures

- buildkitd/buildkitd.go
- cmd/earthly/app/before.go
- util/containerutil/frontend.go
- util/containerutil/settings_test.go
- util/containerutil/shell_shared.go
- util/containerutil/types.go
fixes https://github.com/earthly/earthly/issues/4122
> fix: --buildkit-container-name was ignored when --no-buildkit-update was set

- Earthfile
extends the `+for-linux` and `+for-darwin` commands to also produce a `-ticktock` version of buildkit using the commit sha stored under `earthly-next`.
> build ticktock version locally

- earthfile2llb/converter.go
- tests/Earthfile
- tests/run-no-cache-save-artifact.earth
> fix: force cache bust when --no-cache used

- buildkitd/buildkitd.go
This makes it easier for self-hosted satellites to be deployed on localhost.
> Allow localhost as remote address when using satellites

- buildkitd/dockerd-wrapper.sh
When using a self-hosted satellite with the `--docker-cache` experimental feature enabled, it was found that leftover bad state in the cached data-root could cause builds to start failing. In particular, a leftover, stopped container making use of one of the images that the `dockerd-wrapper.sh` attempts to `rmi` would result in a `unable to remove repository reference` error. Some additional debugging revealed that other types of docker objects are potentially left behind in the data-root. This change modifies the `docker-wrapper.sh` to do some housekeeping of these undesirable objects, and also makes changes to avoid having builds fail due to unanticipated leftover state.
> Dockerd wrapper housekeeping (#4267)
